/* testcanciones.c generated by valac 0.26.0, the Vala compiler
 * generated from testcanciones.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "modelos.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GEE_TYPE_TEST_CASE (gee_test_case_get_type ())
#define GEE_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_TEST_CASE, GeeTestCase))
#define GEE_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_TEST_CASE, GeeTestCaseClass))
#define GEE_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_TEST_CASE))
#define GEE_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_TEST_CASE))
#define GEE_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_TEST_CASE, GeeTestCaseClass))

typedef struct _GeeTestCase GeeTestCase;
typedef struct _GeeTestCaseClass GeeTestCaseClass;
typedef struct _GeeTestCasePrivate GeeTestCasePrivate;

#define GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS (graph_media_test_base_de_datos_get_type ())
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatos))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))

typedef struct _GraphMediaTestBaseDeDatos GraphMediaTestBaseDeDatos;
typedef struct _GraphMediaTestBaseDeDatosClass GraphMediaTestBaseDeDatosClass;
typedef struct _GraphMediaTestBaseDeDatosPrivate GraphMediaTestBaseDeDatosPrivate;

#define GRAPH_MEDIA_TYPE_TEST_CANCIONES (graph_media_test_canciones_get_type ())
#define GRAPH_MEDIA_TEST_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_CANCIONES, GraphMediaTestCanciones))
#define GRAPH_MEDIA_TEST_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_CANCIONES, GraphMediaTestCancionesClass))
#define GRAPH_MEDIA_IS_TEST_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_CANCIONES))
#define GRAPH_MEDIA_IS_TEST_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_CANCIONES))
#define GRAPH_MEDIA_TEST_CANCIONES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_CANCIONES, GraphMediaTestCancionesClass))

typedef struct _GraphMediaTestCanciones GraphMediaTestCanciones;
typedef struct _GraphMediaTestCancionesClass GraphMediaTestCancionesClass;
typedef struct _GraphMediaTestCancionesPrivate GraphMediaTestCancionesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _graph_media_base_datos_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_base_datos_unref (var), NULL)))
#define _graph_media_modelos_archivo_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_modelos_archivo_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GeeTestCase {
	GObject parent_instance;
	GeeTestCasePrivate * priv;
};

struct _GeeTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GeeTestCase* self);
	void (*tear_down) (GeeTestCase* self);
};

struct _GraphMediaTestBaseDeDatos {
	GeeTestCase parent_instance;
	GraphMediaTestBaseDeDatosPrivate * priv;
	GraphMediaBaseDatos* base_de_datos;
	GraphMediaModelosArtistas* artistas;
	GraphMediaModelosAlbumsMusicales* albums_m;
	GraphMediaGenerador* generador;
	gint COTA_SUPERIOR;
};

struct _GraphMediaTestBaseDeDatosClass {
	GeeTestCaseClass parent_class;
};

struct _GraphMediaTestCanciones {
	GraphMediaTestBaseDeDatos parent_instance;
	GraphMediaTestCancionesPrivate * priv;
};

struct _GraphMediaTestCancionesClass {
	GraphMediaTestBaseDeDatosClass parent_class;
};

struct _GraphMediaTestCancionesPrivate {
	GraphMediaModelosCanciones* canciones;
};

typedef void (*GeeTestCaseTestMethod) (void* user_data);

static gpointer graph_media_test_canciones_parent_class = NULL;

GType gee_test_case_get_type (void) G_GNUC_CONST;
GType graph_media_test_base_de_datos_get_type (void) G_GNUC_CONST;
GType graph_media_test_canciones_get_type (void) G_GNUC_CONST;
#define GRAPH_MEDIA_TEST_CANCIONES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRAPH_MEDIA_TYPE_TEST_CANCIONES, GraphMediaTestCancionesPrivate))
enum  {
	GRAPH_MEDIA_TEST_CANCIONES_DUMMY_PROPERTY
};
GraphMediaTestCanciones* graph_media_test_canciones_new (void);
GraphMediaTestCanciones* graph_media_test_canciones_construct (GType object_type);
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_new (void);
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_construct (GType object_type);
void gee_test_case_add_test (GeeTestCase* self, const gchar* name, GeeTestCaseTestMethod test, void* test_target);
static void graph_media_test_canciones_agregar_cancion (GraphMediaTestCanciones* self);
static void _graph_media_test_canciones_agregar_cancion_gee_test_case_test_method (gpointer self);
static void graph_media_test_canciones_editar_cancion (GraphMediaTestCanciones* self);
static void _graph_media_test_canciones_editar_cancion_gee_test_case_test_method (gpointer self);
static void graph_media_test_canciones_eliminar_cancion (GraphMediaTestCanciones* self);
static void _graph_media_test_canciones_eliminar_cancion_gee_test_case_test_method (gpointer self);
static void graph_media_test_canciones_listar_canciones (GraphMediaTestCanciones* self);
static void _graph_media_test_canciones_listar_canciones_gee_test_case_test_method (gpointer self);
static void graph_media_test_canciones_real_set_up (GeeTestCase* base);
static void graph_media_test_canciones_finalize (GObject* obj);


static void _graph_media_test_canciones_agregar_cancion_gee_test_case_test_method (gpointer self) {
	graph_media_test_canciones_agregar_cancion ((GraphMediaTestCanciones*) self);
}


static void _graph_media_test_canciones_editar_cancion_gee_test_case_test_method (gpointer self) {
	graph_media_test_canciones_editar_cancion ((GraphMediaTestCanciones*) self);
}


static void _graph_media_test_canciones_eliminar_cancion_gee_test_case_test_method (gpointer self) {
	graph_media_test_canciones_eliminar_cancion ((GraphMediaTestCanciones*) self);
}


static void _graph_media_test_canciones_listar_canciones_gee_test_case_test_method (gpointer self) {
	graph_media_test_canciones_listar_canciones ((GraphMediaTestCanciones*) self);
}


GraphMediaTestCanciones* graph_media_test_canciones_construct (GType object_type) {
	GraphMediaTestCanciones * self = NULL;
	FILE* _tmp0_ = NULL;
	self = (GraphMediaTestCanciones*) graph_media_test_base_de_datos_construct (object_type);
	_tmp0_ = stdout;
	fprintf (_tmp0_, " *** Tests AlbumsMusicales ***");
	gee_test_case_add_test ((GeeTestCase*) self, "agregar cancion", _graph_media_test_canciones_agregar_cancion_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "editar cancion", _graph_media_test_canciones_editar_cancion_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "eliminar cancion", _graph_media_test_canciones_eliminar_cancion_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "listar canciones", _graph_media_test_canciones_listar_canciones_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "agregar cancion", _graph_media_test_canciones_agregar_cancion_gee_test_case_test_method, self);
	return self;
}


GraphMediaTestCanciones* graph_media_test_canciones_new (void) {
	return graph_media_test_canciones_construct (GRAPH_MEDIA_TYPE_TEST_CANCIONES);
}


static void graph_media_test_canciones_real_set_up (GeeTestCase* base) {
	GraphMediaTestCanciones * self;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaBaseDatos* _tmp1_ = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaBaseDatos* _tmp3_ = NULL;
	GraphMediaModelosCanciones* _tmp4_ = NULL;
	GraphMediaGenerador* _tmp5_ = NULL;
	GraphMediaGenerador* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	self = (GraphMediaTestCanciones*) base;
	_tmp0_ = graph_media_base_datos_new ();
	_graph_media_base_datos_unref0 (((GraphMediaTestBaseDeDatos*) self)->base_de_datos);
	((GraphMediaTestBaseDeDatos*) self)->base_de_datos = _tmp0_;
	_tmp1_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	graph_media_base_datos_seleccionar_archivo (_tmp1_, "src/test/base_prueba.db");
	_tmp2_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	graph_media_base_datos_inicializar (_tmp2_);
	_tmp3_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	_tmp4_ = graph_media_base_datos_get_canciones (_tmp3_);
	_g_object_unref0 (self->priv->canciones);
	self->priv->canciones = _tmp4_;
	_tmp5_ = graph_media_generador_new ("src/test/lista.txt");
	_g_object_unref0 (((GraphMediaTestBaseDeDatos*) self)->generador);
	((GraphMediaTestBaseDeDatos*) self)->generador = _tmp5_;
	_tmp6_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp7_ = graph_media_generador_edad_aleatoria (_tmp6_);
	((GraphMediaTestBaseDeDatos*) self)->COTA_SUPERIOR = _tmp7_;
}


static void graph_media_test_canciones_agregar_cancion (GraphMediaTestCanciones* self) {
	GraphMediaModelosCanciones* _tmp0_ = NULL;
	gint n = 0;
	GraphMediaModelosCanciones* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GraphMediaModelosCancion* cancion = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaModelosCancion* _tmp4_ = NULL;
	GraphMediaModelosCancion* _tmp5_ = NULL;
	gint64 _tmp6_ = 0LL;
	GraphMediaModelosCanciones* _tmp7_ = NULL;
	GraphMediaModelosCancion* _tmp8_ = NULL;
	GraphMediaModelosCancion* _tmp9_ = NULL;
	GraphMediaModelosCancion* _tmp10_ = NULL;
	GraphMediaModelosCanciones* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	GraphMediaModelosCancion* _tmp13_ = NULL;
	gint64 _tmp14_ = 0LL;
	GraphMediaModelosCancion* registrado = NULL;
	GraphMediaModelosCanciones* _tmp15_ = NULL;
	GraphMediaModelosCancion* _tmp16_ = NULL;
	gint64 _tmp17_ = 0LL;
	GraphMediaModelosCancion* _tmp18_ = NULL;
	GraphMediaModelosCancion* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->canciones;
	_vala_assert (_tmp0_ != NULL, "canciones != null");
	_tmp1_ = self->priv->canciones;
	_tmp2_ = graph_media_modelos_canciones_get_total_canciones (_tmp1_);
	n = _tmp2_;
	_tmp3_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp4_ = graph_media_generador_cancion_aleatoria (_tmp3_);
	cancion = _tmp4_;
	_tmp5_ = cancion;
	_tmp6_ = ((GraphMediaModelosArchivo*) _tmp5_)->id;
	_vala_assert (_tmp6_ == ((gint64) (-1)), "cancion.id == -1");
	_tmp7_ = self->priv->canciones;
	_tmp8_ = cancion;
	_tmp9_ = graph_media_modelos_canciones_agregar (_tmp7_, _tmp8_);
	_graph_media_modelos_archivo_unref0 (cancion);
	cancion = _tmp9_;
	_tmp10_ = cancion;
	_vala_assert (_tmp10_ != NULL, "cancion != null");
	_tmp11_ = self->priv->canciones;
	_tmp12_ = graph_media_modelos_canciones_get_total_canciones (_tmp11_);
	_vala_assert (_tmp12_ == (n + 1), "canciones.get_total_canciones() == n+1");
	_tmp13_ = cancion;
	_tmp14_ = ((GraphMediaModelosArchivo*) _tmp13_)->id;
	_vala_assert (_tmp14_ != ((gint64) (-1)), "cancion.id != -1");
	_tmp15_ = self->priv->canciones;
	_tmp16_ = cancion;
	_tmp17_ = ((GraphMediaModelosArchivo*) _tmp16_)->id;
	_tmp18_ = graph_media_modelos_canciones_get_cancion_por_id (_tmp15_, _tmp17_);
	registrado = _tmp18_;
	_vala_assert (registrado != NULL, "registrado != null");
	_tmp19_ = cancion;
	_tmp20_ = ((GraphMediaModelosArchivo*) _tmp19_)->nombre;
	_tmp21_ = ((GraphMediaModelosArchivo*) registrado)->nombre;
	_vala_assert (g_strcmp0 (_tmp20_, _tmp21_) == 0, "cancion.nombre == registrado.nombre");
	_graph_media_modelos_archivo_unref0 (registrado);
	_graph_media_modelos_archivo_unref0 (cancion);
}


static void graph_media_test_canciones_eliminar_cancion (GraphMediaTestCanciones* self) {
	GraphMediaModelosCanciones* _tmp0_ = NULL;
	gint n = 0;
	GraphMediaModelosCanciones* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GraphMediaModelosCancion* cancion = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaModelosCancion* _tmp4_ = NULL;
	GraphMediaModelosCancion* _tmp5_ = NULL;
	gint64 _tmp6_ = 0LL;
	GraphMediaModelosCanciones* _tmp7_ = NULL;
	GraphMediaModelosCancion* _tmp8_ = NULL;
	GraphMediaModelosCancion* _tmp9_ = NULL;
	GraphMediaModelosCanciones* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	GraphMediaModelosCancion* registrado = NULL;
	GraphMediaModelosCanciones* _tmp12_ = NULL;
	GraphMediaModelosCancion* _tmp13_ = NULL;
	gint64 _tmp14_ = 0LL;
	GraphMediaModelosCancion* _tmp15_ = NULL;
	GraphMediaModelosCanciones* _tmp16_ = NULL;
	GraphMediaModelosCancion* _tmp17_ = NULL;
	GraphMediaModelosCancion* _tmp18_ = NULL;
	GraphMediaModelosCanciones* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	GraphMediaModelosCancion* _tmp21_ = NULL;
	gint64 _tmp22_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->canciones;
	_vala_assert (_tmp0_ != NULL, "canciones != null");
	_tmp1_ = self->priv->canciones;
	_tmp2_ = graph_media_modelos_canciones_get_total_canciones (_tmp1_);
	n = _tmp2_;
	_tmp3_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp4_ = graph_media_generador_cancion_aleatoria (_tmp3_);
	cancion = _tmp4_;
	_tmp5_ = cancion;
	_tmp6_ = ((GraphMediaModelosArchivo*) _tmp5_)->id;
	_vala_assert (_tmp6_ == ((gint64) (-1)), "cancion.id == -1");
	_tmp7_ = self->priv->canciones;
	_tmp8_ = cancion;
	_tmp9_ = graph_media_modelos_canciones_agregar (_tmp7_, _tmp8_);
	_graph_media_modelos_archivo_unref0 (cancion);
	cancion = _tmp9_;
	_tmp10_ = self->priv->canciones;
	_tmp11_ = graph_media_modelos_canciones_get_total_canciones (_tmp10_);
	_vala_assert (_tmp11_ == (n + 1), "canciones.get_total_canciones() == n+1");
	_tmp12_ = self->priv->canciones;
	_tmp13_ = cancion;
	_tmp14_ = ((GraphMediaModelosArchivo*) _tmp13_)->id;
	_tmp15_ = graph_media_modelos_canciones_get_cancion_por_id (_tmp12_, _tmp14_);
	registrado = _tmp15_;
	_tmp16_ = self->priv->canciones;
	_tmp17_ = registrado;
	_tmp18_ = graph_media_modelos_canciones_eliminar (_tmp16_, _tmp17_);
	_graph_media_modelos_archivo_unref0 (registrado);
	registrado = _tmp18_;
	_tmp19_ = self->priv->canciones;
	_tmp20_ = graph_media_modelos_canciones_get_total_canciones (_tmp19_);
	_vala_assert (_tmp20_ == n, "canciones.get_total_canciones() == n");
	_tmp21_ = registrado;
	_tmp22_ = ((GraphMediaModelosArchivo*) _tmp21_)->id;
	_vala_assert (_tmp22_ == ((gint64) (-1)), "registrado.id == -1");
	_graph_media_modelos_archivo_unref0 (registrado);
	_graph_media_modelos_archivo_unref0 (cancion);
}


static void graph_media_test_canciones_listar_canciones (GraphMediaTestCanciones* self) {
	gint lim = 0;
	GeeArrayList* resultados = NULL;
	GraphMediaModelosCanciones* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GeeArrayList* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GeeArrayList* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	g_return_if_fail (self != NULL);
	lim = 5;
	_tmp0_ = self->priv->canciones;
	_tmp1_ = lim;
	_tmp2_ = graph_media_modelos_canciones_buscar_canciones_por_nombre (_tmp0_, "a", _tmp1_, "popularidad");
	resultados = _tmp2_;
	_tmp4_ = resultados;
	_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ >= 0) {
		GeeArrayList* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		_tmp7_ = resultados;
		_tmp8_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = lim;
		_tmp3_ = _tmp9_ <= _tmp10_;
	} else {
		_tmp3_ = FALSE;
	}
	_vala_assert (_tmp3_, "resultados.size >= 0 && resultados.size <= lim");
	_g_object_unref0 (resultados);
}


static void graph_media_test_canciones_editar_cancion (GraphMediaTestCanciones* self) {
	GraphMediaModelosCancion* cancion = NULL;
	GraphMediaGenerador* _tmp0_ = NULL;
	GraphMediaModelosCancion* _tmp1_ = NULL;
	GraphMediaModelosCancion* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	GraphMediaModelosCanciones* _tmp4_ = NULL;
	GraphMediaModelosCancion* _tmp5_ = NULL;
	GraphMediaModelosCancion* _tmp6_ = NULL;
	GraphMediaModelosCancion* registrado = NULL;
	GraphMediaModelosCanciones* _tmp7_ = NULL;
	GraphMediaModelosCancion* _tmp8_ = NULL;
	gint64 _tmp9_ = 0LL;
	GraphMediaModelosCancion* _tmp10_ = NULL;
	GraphMediaModelosCancion* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GraphMediaModelosCanciones* _tmp13_ = NULL;
	GraphMediaModelosCancion* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	GraphMediaModelosCanciones* _tmp16_ = NULL;
	GraphMediaModelosCancion* _tmp17_ = NULL;
	gint64 _tmp18_ = 0LL;
	GraphMediaModelosCancion* _tmp19_ = NULL;
	GraphMediaModelosCancion* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	GraphMediaModelosCancion* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	GraphMediaModelosCanciones* _tmp24_ = NULL;
	GraphMediaModelosCancion* _tmp25_ = NULL;
	gboolean _tmp26_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp1_ = graph_media_generador_cancion_aleatoria (_tmp0_);
	cancion = _tmp1_;
	_tmp2_ = cancion;
	_tmp3_ = ((GraphMediaModelosArchivo*) _tmp2_)->id;
	_vala_assert (_tmp3_ == ((gint64) (-1)), "cancion.id == -1");
	_tmp4_ = self->priv->canciones;
	_tmp5_ = cancion;
	_tmp6_ = graph_media_modelos_canciones_agregar (_tmp4_, _tmp5_);
	_graph_media_modelos_archivo_unref0 (cancion);
	cancion = _tmp6_;
	_tmp7_ = self->priv->canciones;
	_tmp8_ = cancion;
	_tmp9_ = ((GraphMediaModelosArchivo*) _tmp8_)->id;
	_tmp10_ = graph_media_modelos_canciones_get_cancion_por_id (_tmp7_, _tmp9_);
	registrado = _tmp10_;
	_tmp11_ = registrado;
	_tmp12_ = g_strdup ("I'm aquarius");
	_g_free0 (((GraphMediaModelosArchivo*) _tmp11_)->nombre);
	((GraphMediaModelosArchivo*) _tmp11_)->nombre = _tmp12_;
	_tmp13_ = self->priv->canciones;
	_tmp14_ = registrado;
	_tmp15_ = graph_media_modelos_canciones_editar (_tmp13_, _tmp14_);
	_vala_assert (_tmp15_, "canciones.editar(registrado)");
	_tmp16_ = self->priv->canciones;
	_tmp17_ = cancion;
	_tmp18_ = ((GraphMediaModelosArchivo*) _tmp17_)->id;
	_tmp19_ = graph_media_modelos_canciones_get_cancion_por_id (_tmp16_, _tmp18_);
	_graph_media_modelos_archivo_unref0 (registrado);
	registrado = _tmp19_;
	_tmp20_ = registrado;
	_tmp21_ = ((GraphMediaModelosArchivo*) _tmp20_)->nombre;
	_vala_assert (g_strcmp0 (_tmp21_, "I'm aquarius") == 0, "registrado.nombre == \"I'm aquarius\"");
	_tmp22_ = registrado;
	_tmp23_ = g_strdup ("");
	_g_free0 (((GraphMediaModelosArchivo*) _tmp22_)->nombre);
	((GraphMediaModelosArchivo*) _tmp22_)->nombre = _tmp23_;
	_tmp24_ = self->priv->canciones;
	_tmp25_ = registrado;
	_tmp26_ = graph_media_modelos_canciones_editar (_tmp24_, _tmp25_);
	_vala_assert (!_tmp26_, "!canciones.editar(registrado)");
	_graph_media_modelos_archivo_unref0 (registrado);
	_graph_media_modelos_archivo_unref0 (cancion);
}


static void graph_media_test_canciones_class_init (GraphMediaTestCancionesClass * klass) {
	graph_media_test_canciones_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraphMediaTestCancionesPrivate));
	((GeeTestCaseClass *) klass)->set_up = graph_media_test_canciones_real_set_up;
	G_OBJECT_CLASS (klass)->finalize = graph_media_test_canciones_finalize;
}


static void graph_media_test_canciones_instance_init (GraphMediaTestCanciones * self) {
	self->priv = GRAPH_MEDIA_TEST_CANCIONES_GET_PRIVATE (self);
}


static void graph_media_test_canciones_finalize (GObject* obj) {
	GraphMediaTestCanciones * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_TYPE_TEST_CANCIONES, GraphMediaTestCanciones);
	_g_object_unref0 (self->priv->canciones);
	G_OBJECT_CLASS (graph_media_test_canciones_parent_class)->finalize (obj);
}


GType graph_media_test_canciones_get_type (void) {
	static volatile gsize graph_media_test_canciones_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_test_canciones_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaTestCancionesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_test_canciones_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaTestCanciones), 0, (GInstanceInitFunc) graph_media_test_canciones_instance_init, NULL };
		GType graph_media_test_canciones_type_id;
		graph_media_test_canciones_type_id = g_type_register_static (GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, "GraphMediaTestCanciones", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_test_canciones_type_id__volatile, graph_media_test_canciones_type_id);
	}
	return graph_media_test_canciones_type_id__volatile;
}



