/* testbasedatos.c generated by valac 0.26.0, the Vala compiler
 * generated from testbasedatos.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "modelos.h"
#include <stdlib.h>
#include <string.h>


#define GEE_TYPE_TEST_CASE (gee_test_case_get_type ())
#define GEE_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_TEST_CASE, GeeTestCase))
#define GEE_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_TEST_CASE, GeeTestCaseClass))
#define GEE_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_TEST_CASE))
#define GEE_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_TEST_CASE))
#define GEE_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_TEST_CASE, GeeTestCaseClass))

typedef struct _GeeTestCase GeeTestCase;
typedef struct _GeeTestCaseClass GeeTestCaseClass;
typedef struct _GeeTestCasePrivate GeeTestCasePrivate;

#define GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS (graph_media_test_base_de_datos_get_type ())
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatos))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))

typedef struct _GraphMediaTestBaseDeDatos GraphMediaTestBaseDeDatos;
typedef struct _GraphMediaTestBaseDeDatosClass GraphMediaTestBaseDeDatosClass;
typedef struct _GraphMediaTestBaseDeDatosPrivate GraphMediaTestBaseDeDatosPrivate;
#define _graph_media_base_datos_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_base_datos_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GeeTestCase {
	GObject parent_instance;
	GeeTestCasePrivate * priv;
};

struct _GeeTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GeeTestCase* self);
	void (*tear_down) (GeeTestCase* self);
};

struct _GraphMediaTestBaseDeDatos {
	GeeTestCase parent_instance;
	GraphMediaTestBaseDeDatosPrivate * priv;
	GraphMediaBaseDatos* base_de_datos;
	GraphMediaModelosArtistas* artistas;
	GraphMediaModelosAlbumsMusicales* albums_m;
	GraphMediaGenerador* generador;
	gint COTA_SUPERIOR;
};

struct _GraphMediaTestBaseDeDatosClass {
	GeeTestCaseClass parent_class;
};

typedef void (*GeeTestCaseTestMethod) (void* user_data);

static gpointer graph_media_test_base_de_datos_parent_class = NULL;

GType gee_test_case_get_type (void) G_GNUC_CONST;
GType graph_media_test_base_de_datos_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_TEST_BASE_DE_DATOS_DUMMY_PROPERTY
};
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_new (void);
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_construct (GType object_type);
GeeTestCase* gee_test_case_construct (GType object_type, const gchar* name);
void gee_test_case_add_test (GeeTestCase* self, const gchar* name, GeeTestCaseTestMethod test, void* test_target);
static void graph_media_test_base_de_datos_abrir_base (GraphMediaTestBaseDeDatos* self);
static void _graph_media_test_base_de_datos_abrir_base_gee_test_case_test_method (gpointer self);
static void graph_media_test_base_de_datos_conexion_funciona (GraphMediaTestBaseDeDatos* self);
static void _graph_media_test_base_de_datos_conexion_funciona_gee_test_case_test_method (gpointer self);
static void graph_media_test_base_de_datos_get_sentimientos (GraphMediaTestBaseDeDatos* self);
static void _graph_media_test_base_de_datos_get_sentimientos_gee_test_case_test_method (gpointer self);
static void graph_media_test_base_de_datos_get_albums_musicales (GraphMediaTestBaseDeDatos* self);
static void _graph_media_test_base_de_datos_get_albums_musicales_gee_test_case_test_method (gpointer self);
static void graph_media_test_base_de_datos_get_artistas (GraphMediaTestBaseDeDatos* self);
static void _graph_media_test_base_de_datos_get_artistas_gee_test_case_test_method (gpointer self);
static void graph_media_test_base_de_datos_real_set_up (GeeTestCase* base);
static void graph_media_test_base_de_datos_real_tear_down (GeeTestCase* base);
static void graph_media_test_base_de_datos_finalize (GObject* obj);


static void _graph_media_test_base_de_datos_abrir_base_gee_test_case_test_method (gpointer self) {
	graph_media_test_base_de_datos_abrir_base ((GraphMediaTestBaseDeDatos*) self);
}


static void _graph_media_test_base_de_datos_conexion_funciona_gee_test_case_test_method (gpointer self) {
	graph_media_test_base_de_datos_conexion_funciona ((GraphMediaTestBaseDeDatos*) self);
}


static void _graph_media_test_base_de_datos_get_sentimientos_gee_test_case_test_method (gpointer self) {
	graph_media_test_base_de_datos_get_sentimientos ((GraphMediaTestBaseDeDatos*) self);
}


static void _graph_media_test_base_de_datos_get_albums_musicales_gee_test_case_test_method (gpointer self) {
	graph_media_test_base_de_datos_get_albums_musicales ((GraphMediaTestBaseDeDatos*) self);
}


static void _graph_media_test_base_de_datos_get_artistas_gee_test_case_test_method (gpointer self) {
	graph_media_test_base_de_datos_get_artistas ((GraphMediaTestBaseDeDatos*) self);
}


GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_construct (GType object_type) {
	GraphMediaTestBaseDeDatos * self = NULL;
	self = (GraphMediaTestBaseDeDatos*) gee_test_case_construct (object_type, "BD");
	gee_test_case_add_test ((GeeTestCase*) self, "abrir archivos", _graph_media_test_base_de_datos_abrir_base_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "conexion", _graph_media_test_base_de_datos_conexion_funciona_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "singleton sentimientos", _graph_media_test_base_de_datos_get_sentimientos_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "singleton albums musicales", _graph_media_test_base_de_datos_get_albums_musicales_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "singleton albums imagenes", _graph_media_test_base_de_datos_get_albums_musicales_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "singleton artistas", _graph_media_test_base_de_datos_get_artistas_gee_test_case_test_method, self);
	return self;
}


GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_new (void) {
	return graph_media_test_base_de_datos_construct (GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS);
}


static void graph_media_test_base_de_datos_real_set_up (GeeTestCase* base) {
	GraphMediaTestBaseDeDatos * self;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaBaseDatos* _tmp1_ = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaGenerador* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GraphMediaBaseDatos* _tmp6_ = NULL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	GraphMediaBaseDatos* _tmp8_ = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp9_ = NULL;
	self = (GraphMediaTestBaseDeDatos*) base;
	_tmp0_ = graph_media_base_datos_new ();
	_graph_media_base_datos_unref0 (self->base_de_datos);
	self->base_de_datos = _tmp0_;
	_tmp1_ = self->base_de_datos;
	graph_media_base_datos_seleccionar_archivo (_tmp1_, "src/test/base_prueba.db");
	_tmp2_ = self->base_de_datos;
	graph_media_base_datos_inicializar (_tmp2_);
	_tmp3_ = graph_media_generador_new ("src/test/lista.txt");
	_g_object_unref0 (self->generador);
	self->generador = _tmp3_;
	_tmp4_ = self->generador;
	_tmp5_ = graph_media_generador_edad_aleatoria (_tmp4_);
	self->COTA_SUPERIOR = _tmp5_;
	_tmp6_ = self->base_de_datos;
	_tmp7_ = graph_media_base_datos_get_artistas (_tmp6_);
	_g_object_unref0 (self->artistas);
	self->artistas = _tmp7_;
	_tmp8_ = self->base_de_datos;
	_tmp9_ = graph_media_base_datos_get_albums_musicales (_tmp8_);
	_g_object_unref0 (self->albums_m);
	self->albums_m = _tmp9_;
}


static void graph_media_test_base_de_datos_real_tear_down (GeeTestCase* base) {
	GraphMediaTestBaseDeDatos * self;
	self = (GraphMediaTestBaseDeDatos*) base;
}


static void graph_media_test_base_de_datos_abrir_base (GraphMediaTestBaseDeDatos* self) {
	GraphMediaBaseDatos* v = NULL;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	gboolean detecta_error = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = graph_media_base_datos_new ();
	v = _tmp0_;
	detecta_error = TRUE;
	{
		graph_media_base_datos_seleccionar_archivo (v, "src/test/base_prueba.db");
	}
	goto __finally0;
	__catch0_graph_media_modelos_error_base_datos:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		detecta_error = FALSE;
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_base_datos_unref0 (v);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (detecta_error, "detecta_error");
	_graph_media_base_datos_unref0 (v);
}


static void graph_media_test_base_de_datos_conexion_funciona (GraphMediaTestBaseDeDatos* self) {
	GraphMediaModelosArtistas* p1 = NULL;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaModelosArtistas* _tmp1_ = NULL;
	GraphMediaModelosArtistas* p2 = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaModelosArtistas* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->base_de_datos;
	_tmp1_ = graph_media_base_datos_get_artistas (_tmp0_);
	p1 = _tmp1_;
	_tmp2_ = self->base_de_datos;
	_tmp3_ = graph_media_base_datos_get_artistas (_tmp2_);
	p2 = _tmp3_;
	_vala_assert (p1 != NULL, "p1 != null");
	_vala_assert (p1 == p2, "p1 == p2");
	_tmp4_ = graph_media_modelos_artistas_get_total_artistas (p1);
	_vala_assert (_tmp4_ != (-1), "p1.get_total_artistas() != -1");
	_g_object_unref0 (p2);
	_g_object_unref0 (p1);
}


static void graph_media_test_base_de_datos_get_sentimientos (GraphMediaTestBaseDeDatos* self) {
	GraphMediaModelosSentimientos* a = NULL;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaModelosSentimientos* _tmp1_ = NULL;
	GraphMediaModelosSentimientos* b = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaModelosSentimientos* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->base_de_datos;
	_tmp1_ = graph_media_base_datos_get_sentimientos (_tmp0_);
	a = _tmp1_;
	_tmp2_ = self->base_de_datos;
	_tmp3_ = graph_media_base_datos_get_sentimientos (_tmp2_);
	b = _tmp3_;
	_vala_assert (a != NULL, "a != null");
	_vala_assert (a == b, "a == b");
	_g_object_unref0 (b);
	_g_object_unref0 (a);
}


static void graph_media_test_base_de_datos_get_artistas (GraphMediaTestBaseDeDatos* self) {
	GraphMediaModelosArtistas* a = NULL;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaModelosArtistas* _tmp1_ = NULL;
	GraphMediaModelosArtistas* b = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaModelosArtistas* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->base_de_datos;
	_tmp1_ = graph_media_base_datos_get_artistas (_tmp0_);
	a = _tmp1_;
	_tmp2_ = self->base_de_datos;
	_tmp3_ = graph_media_base_datos_get_artistas (_tmp2_);
	b = _tmp3_;
	_vala_assert (a != NULL, "a != null");
	_vala_assert (a == b, "a == b");
	_g_object_unref0 (b);
	_g_object_unref0 (a);
}


static void graph_media_test_base_de_datos_get_albums_musicales (GraphMediaTestBaseDeDatos* self) {
	GraphMediaModelosAlbumsMusicales* a = NULL;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp1_ = NULL;
	GraphMediaModelosAlbumsMusicales* b = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->base_de_datos;
	_tmp1_ = graph_media_base_datos_get_albums_musicales (_tmp0_);
	a = _tmp1_;
	_tmp2_ = self->base_de_datos;
	_tmp3_ = graph_media_base_datos_get_albums_musicales (_tmp2_);
	b = _tmp3_;
	_vala_assert (a != NULL, "a != null");
	_vala_assert (a == b, "a == b");
	_g_object_unref0 (b);
	_g_object_unref0 (a);
}


static void graph_media_test_base_de_datos_class_init (GraphMediaTestBaseDeDatosClass * klass) {
	graph_media_test_base_de_datos_parent_class = g_type_class_peek_parent (klass);
	((GeeTestCaseClass *) klass)->set_up = graph_media_test_base_de_datos_real_set_up;
	((GeeTestCaseClass *) klass)->tear_down = graph_media_test_base_de_datos_real_tear_down;
	G_OBJECT_CLASS (klass)->finalize = graph_media_test_base_de_datos_finalize;
}


static void graph_media_test_base_de_datos_instance_init (GraphMediaTestBaseDeDatos * self) {
	self->COTA_SUPERIOR = 50;
}


static void graph_media_test_base_de_datos_finalize (GObject* obj) {
	GraphMediaTestBaseDeDatos * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatos);
	_graph_media_base_datos_unref0 (self->base_de_datos);
	_g_object_unref0 (self->artistas);
	_g_object_unref0 (self->albums_m);
	_g_object_unref0 (self->generador);
	G_OBJECT_CLASS (graph_media_test_base_de_datos_parent_class)->finalize (obj);
}


GType graph_media_test_base_de_datos_get_type (void) {
	static volatile gsize graph_media_test_base_de_datos_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_test_base_de_datos_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaTestBaseDeDatosClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_test_base_de_datos_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaTestBaseDeDatos), 0, (GInstanceInitFunc) graph_media_test_base_de_datos_instance_init, NULL };
		GType graph_media_test_base_de_datos_type_id;
		graph_media_test_base_de_datos_type_id = g_type_register_static (GEE_TYPE_TEST_CASE, "GraphMediaTestBaseDeDatos", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_test_base_de_datos_type_id__volatile, graph_media_test_base_de_datos_type_id);
	}
	return graph_media_test_base_de_datos_type_id__volatile;
}



