/* testartistas.c generated by valac 0.26.0, the Vala compiler
 * generated from testartistas.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "modelos.h"
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define GEE_TYPE_TEST_CASE (gee_test_case_get_type ())
#define GEE_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_TEST_CASE, GeeTestCase))
#define GEE_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_TEST_CASE, GeeTestCaseClass))
#define GEE_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_TEST_CASE))
#define GEE_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_TEST_CASE))
#define GEE_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_TEST_CASE, GeeTestCaseClass))

typedef struct _GeeTestCase GeeTestCase;
typedef struct _GeeTestCaseClass GeeTestCaseClass;
typedef struct _GeeTestCasePrivate GeeTestCasePrivate;

#define GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS (graph_media_test_base_de_datos_get_type ())
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatos))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_IS_TEST_BASE_DE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS))
#define GRAPH_MEDIA_TEST_BASE_DE_DATOS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, GraphMediaTestBaseDeDatosClass))

typedef struct _GraphMediaTestBaseDeDatos GraphMediaTestBaseDeDatos;
typedef struct _GraphMediaTestBaseDeDatosClass GraphMediaTestBaseDeDatosClass;
typedef struct _GraphMediaTestBaseDeDatosPrivate GraphMediaTestBaseDeDatosPrivate;

#define GRAPH_MEDIA_TYPE_TEST_ARTISTAS (graph_media_test_artistas_get_type ())
#define GRAPH_MEDIA_TEST_ARTISTAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_ARTISTAS, GraphMediaTestArtistas))
#define GRAPH_MEDIA_TEST_ARTISTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_ARTISTAS, GraphMediaTestArtistasClass))
#define GRAPH_MEDIA_IS_TEST_ARTISTAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_ARTISTAS))
#define GRAPH_MEDIA_IS_TEST_ARTISTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_ARTISTAS))
#define GRAPH_MEDIA_TEST_ARTISTAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_ARTISTAS, GraphMediaTestArtistasClass))

typedef struct _GraphMediaTestArtistas GraphMediaTestArtistas;
typedef struct _GraphMediaTestArtistasClass GraphMediaTestArtistasClass;
typedef struct _GraphMediaTestArtistasPrivate GraphMediaTestArtistasPrivate;
#define _graph_media_base_datos_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_base_datos_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _graph_media_modelos_persona_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_modelos_persona_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GeeTestCase {
	GObject parent_instance;
	GeeTestCasePrivate * priv;
};

struct _GeeTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GeeTestCase* self);
	void (*tear_down) (GeeTestCase* self);
};

struct _GraphMediaTestBaseDeDatos {
	GeeTestCase parent_instance;
	GraphMediaTestBaseDeDatosPrivate * priv;
	GraphMediaBaseDatos* base_de_datos;
	GraphMediaModelosArtistas* artistas;
	GraphMediaModelosAlbumsMusicales* albums_m;
	GraphMediaGenerador* generador;
	gint COTA_SUPERIOR;
};

struct _GraphMediaTestBaseDeDatosClass {
	GeeTestCaseClass parent_class;
};

struct _GraphMediaTestArtistas {
	GraphMediaTestBaseDeDatos parent_instance;
	GraphMediaTestArtistasPrivate * priv;
};

struct _GraphMediaTestArtistasClass {
	GraphMediaTestBaseDeDatosClass parent_class;
};

typedef void (*GeeTestCaseTestMethod) (void* user_data);

static gpointer graph_media_test_artistas_parent_class = NULL;

GType gee_test_case_get_type (void) G_GNUC_CONST;
GType graph_media_test_base_de_datos_get_type (void) G_GNUC_CONST;
GType graph_media_test_artistas_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_TEST_ARTISTAS_DUMMY_PROPERTY
};
GraphMediaTestArtistas* graph_media_test_artistas_new (void);
GraphMediaTestArtistas* graph_media_test_artistas_construct (GType object_type);
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_new (void);
GraphMediaTestBaseDeDatos* graph_media_test_base_de_datos_construct (GType object_type);
void gee_test_case_add_test (GeeTestCase* self, const gchar* name, GeeTestCaseTestMethod test, void* test_target);
static void graph_media_test_artistas_editar_artista (GraphMediaTestArtistas* self);
static void _graph_media_test_artistas_editar_artista_gee_test_case_test_method (gpointer self);
static void graph_media_test_artistas_registrar_artista (GraphMediaTestArtistas* self);
static void _graph_media_test_artistas_registrar_artista_gee_test_case_test_method (gpointer self);
static void graph_media_test_artistas_eliminar_artista (GraphMediaTestArtistas* self);
static void _graph_media_test_artistas_eliminar_artista_gee_test_case_test_method (gpointer self);
static void graph_media_test_artistas_listar_artistas (GraphMediaTestArtistas* self);
static void _graph_media_test_artistas_listar_artistas_gee_test_case_test_method (gpointer self);
static void graph_media_test_artistas_get_artista_por_id (GraphMediaTestArtistas* self);
static void _graph_media_test_artistas_get_artista_por_id_gee_test_case_test_method (gpointer self);
static void graph_media_test_artistas_real_set_up (GeeTestCase* base);


static void _graph_media_test_artistas_editar_artista_gee_test_case_test_method (gpointer self) {
	graph_media_test_artistas_editar_artista ((GraphMediaTestArtistas*) self);
}


static void _graph_media_test_artistas_registrar_artista_gee_test_case_test_method (gpointer self) {
	graph_media_test_artistas_registrar_artista ((GraphMediaTestArtistas*) self);
}


static void _graph_media_test_artistas_eliminar_artista_gee_test_case_test_method (gpointer self) {
	graph_media_test_artistas_eliminar_artista ((GraphMediaTestArtistas*) self);
}


static void _graph_media_test_artistas_listar_artistas_gee_test_case_test_method (gpointer self) {
	graph_media_test_artistas_listar_artistas ((GraphMediaTestArtistas*) self);
}


static void _graph_media_test_artistas_get_artista_por_id_gee_test_case_test_method (gpointer self) {
	graph_media_test_artistas_get_artista_por_id ((GraphMediaTestArtistas*) self);
}


GraphMediaTestArtistas* graph_media_test_artistas_construct (GType object_type) {
	GraphMediaTestArtistas * self = NULL;
	self = (GraphMediaTestArtistas*) graph_media_test_base_de_datos_construct (object_type);
	gee_test_case_add_test ((GeeTestCase*) self, "editar artista", _graph_media_test_artistas_editar_artista_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "registrar artista", _graph_media_test_artistas_registrar_artista_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "eliminar artista", _graph_media_test_artistas_eliminar_artista_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "listar artistas", _graph_media_test_artistas_listar_artistas_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "artista por id ", _graph_media_test_artistas_get_artista_por_id_gee_test_case_test_method, self);
	return self;
}


GraphMediaTestArtistas* graph_media_test_artistas_new (void) {
	return graph_media_test_artistas_construct (GRAPH_MEDIA_TYPE_TEST_ARTISTAS);
}


static void graph_media_test_artistas_real_set_up (GeeTestCase* base) {
	GraphMediaTestArtistas * self;
	GraphMediaBaseDatos* _tmp0_ = NULL;
	GraphMediaBaseDatos* _tmp1_ = NULL;
	GraphMediaBaseDatos* _tmp2_ = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaGenerador* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GraphMediaBaseDatos* _tmp6_ = NULL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	self = (GraphMediaTestArtistas*) base;
	_tmp0_ = graph_media_base_datos_new ();
	_graph_media_base_datos_unref0 (((GraphMediaTestBaseDeDatos*) self)->base_de_datos);
	((GraphMediaTestBaseDeDatos*) self)->base_de_datos = _tmp0_;
	_tmp1_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	graph_media_base_datos_seleccionar_archivo (_tmp1_, "src/test/base_prueba.db");
	_tmp2_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	graph_media_base_datos_inicializar (_tmp2_);
	_tmp3_ = graph_media_generador_new ("src/test/lista.txt");
	_g_object_unref0 (((GraphMediaTestBaseDeDatos*) self)->generador);
	((GraphMediaTestBaseDeDatos*) self)->generador = _tmp3_;
	_tmp4_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp5_ = graph_media_generador_edad_aleatoria (_tmp4_);
	((GraphMediaTestBaseDeDatos*) self)->COTA_SUPERIOR = _tmp5_;
	_tmp6_ = ((GraphMediaTestBaseDeDatos*) self)->base_de_datos;
	_tmp7_ = graph_media_base_datos_get_artistas (_tmp6_);
	_g_object_unref0 (((GraphMediaTestBaseDeDatos*) self)->artistas);
	((GraphMediaTestBaseDeDatos*) self)->artistas = _tmp7_;
}


static void graph_media_test_artistas_registrar_artista (GraphMediaTestArtistas* self) {
	GraphMediaModelosArtistas* _tmp0_ = NULL;
	gint n = 0;
	GraphMediaModelosArtistas* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GraphMediaModelosArtista* artista = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaModelosArtista* _tmp4_ = NULL;
	GraphMediaModelosArtista* _tmp5_ = NULL;
	gint64 _tmp6_ = 0LL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	GraphMediaModelosArtista* _tmp8_ = NULL;
	GraphMediaModelosArtista* _tmp9_ = NULL;
	GraphMediaModelosArtistas* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	GraphMediaModelosArtista* _tmp12_ = NULL;
	gint64 _tmp13_ = 0LL;
	GraphMediaModelosArtista* registrado = NULL;
	GraphMediaModelosArtistas* _tmp14_ = NULL;
	GraphMediaModelosArtista* _tmp15_ = NULL;
	gint64 _tmp16_ = 0LL;
	GraphMediaModelosArtista* _tmp17_ = NULL;
	GraphMediaModelosArtista* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GraphMediaModelosArtista* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_vala_assert (_tmp0_ != NULL, "artistas != null");
	_tmp1_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp2_ = graph_media_modelos_artistas_get_total_artistas (_tmp1_);
	n = _tmp2_;
	_tmp3_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp4_ = graph_media_generador_artista_aleatorio (_tmp3_);
	artista = _tmp4_;
	_tmp5_ = artista;
	_tmp6_ = ((GraphMediaModelosPersona*) _tmp5_)->id;
	_vala_assert (_tmp6_ == ((gint64) (-1)), "artista.id == -1");
	_tmp7_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp8_ = artista;
	_tmp9_ = graph_media_modelos_artistas_agregar (_tmp7_, _tmp8_);
	_graph_media_modelos_persona_unref0 (artista);
	artista = _tmp9_;
	_tmp10_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp11_ = graph_media_modelos_artistas_get_total_artistas (_tmp10_);
	_vala_assert (_tmp11_ == (n + 1), "artistas.get_total_artistas() == n+1");
	_tmp12_ = artista;
	_tmp13_ = ((GraphMediaModelosPersona*) _tmp12_)->id;
	_vala_assert (_tmp13_ != ((gint64) (-1)), "artista.id != -1");
	_tmp14_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp15_ = artista;
	_tmp16_ = ((GraphMediaModelosPersona*) _tmp15_)->id;
	_tmp17_ = graph_media_modelos_artistas_get_artista_por_id (_tmp14_, _tmp16_, &_inner_error_);
	registrado = _tmp17_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_vala_assert (registrado != NULL, "registrado != null");
	_tmp18_ = artista;
	_tmp19_ = ((GraphMediaModelosPersona*) _tmp18_)->nombre;
	_tmp20_ = ((GraphMediaModelosPersona*) registrado)->nombre;
	_vala_assert (g_strcmp0 (_tmp19_, _tmp20_) == 0, "artista.nombre == registrado.nombre");
	_tmp21_ = artista;
	_tmp22_ = ((GraphMediaModelosPersona*) _tmp21_)->imagen;
	_tmp23_ = ((GraphMediaModelosPersona*) registrado)->imagen;
	_vala_assert (g_strcmp0 (_tmp22_, _tmp23_) == 0, "artista.imagen == registrado.imagen");
	_graph_media_modelos_persona_unref0 (registrado);
	_graph_media_modelos_persona_unref0 (artista);
}


static void graph_media_test_artistas_eliminar_artista (GraphMediaTestArtistas* self) {
	GraphMediaModelosArtistas* _tmp0_ = NULL;
	gint n = 0;
	GraphMediaModelosArtistas* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GraphMediaModelosArtista* artista = NULL;
	GraphMediaGenerador* _tmp3_ = NULL;
	GraphMediaModelosArtista* _tmp4_ = NULL;
	GraphMediaModelosArtista* _tmp5_ = NULL;
	gint64 _tmp6_ = 0LL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	GraphMediaModelosArtista* _tmp8_ = NULL;
	GraphMediaModelosArtista* _tmp9_ = NULL;
	GraphMediaModelosArtistas* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	GraphMediaModelosArtista* registrado = NULL;
	GraphMediaModelosArtistas* _tmp12_ = NULL;
	GraphMediaModelosArtista* _tmp13_ = NULL;
	gint64 _tmp14_ = 0LL;
	GraphMediaModelosArtista* _tmp15_ = NULL;
	GraphMediaModelosArtistas* _tmp16_ = NULL;
	GraphMediaModelosArtista* _tmp17_ = NULL;
	GraphMediaModelosArtista* _tmp18_ = NULL;
	GraphMediaModelosArtista* _tmp19_ = NULL;
	gint64 _tmp20_ = 0LL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_vala_assert (_tmp0_ != NULL, "artistas != null");
	_tmp1_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp2_ = graph_media_modelos_artistas_get_total_artistas (_tmp1_);
	n = _tmp2_;
	_tmp3_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp4_ = graph_media_generador_artista_aleatorio (_tmp3_);
	artista = _tmp4_;
	_tmp5_ = artista;
	_tmp6_ = ((GraphMediaModelosPersona*) _tmp5_)->id;
	_vala_assert (_tmp6_ == ((gint64) (-1)), "artista.id == -1");
	_tmp7_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp8_ = artista;
	_tmp9_ = graph_media_modelos_artistas_agregar (_tmp7_, _tmp8_);
	_graph_media_modelos_persona_unref0 (artista);
	artista = _tmp9_;
	_tmp10_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp11_ = graph_media_modelos_artistas_get_total_artistas (_tmp10_);
	_vala_assert (_tmp11_ == (n + 1), "artistas.get_total_artistas() == n+1");
	_tmp12_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp13_ = artista;
	_tmp14_ = ((GraphMediaModelosPersona*) _tmp13_)->id;
	_tmp15_ = graph_media_modelos_artistas_get_artista_por_id (_tmp12_, _tmp14_, &_inner_error_);
	registrado = _tmp15_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp16_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp17_ = registrado;
	_tmp18_ = graph_media_modelos_artistas_eliminar (_tmp16_, _tmp17_);
	_graph_media_modelos_persona_unref0 (registrado);
	registrado = _tmp18_;
	_tmp19_ = registrado;
	_tmp20_ = ((GraphMediaModelosPersona*) _tmp19_)->id;
	_vala_assert (_tmp20_ == ((gint64) (-1)), "registrado.id == -1");
	_graph_media_modelos_persona_unref0 (registrado);
	_graph_media_modelos_persona_unref0 (artista);
}


static void graph_media_test_artistas_listar_artistas (GraphMediaTestArtistas* self) {
	gint lim = 0;
	GeeArrayList* resultados = NULL;
	GraphMediaModelosArtistas* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GeeArrayList* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GeeArrayList* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	g_return_if_fail (self != NULL);
	lim = 5;
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp1_ = lim;
	_tmp2_ = graph_media_modelos_artistas_buscar_artistas_por_nombre (_tmp0_, "Andrade", _tmp1_);
	resultados = _tmp2_;
	_tmp4_ = resultados;
	_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ >= 0) {
		GeeArrayList* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		_tmp7_ = resultados;
		_tmp8_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = lim;
		_tmp3_ = _tmp9_ <= _tmp10_;
	} else {
		_tmp3_ = FALSE;
	}
	_vala_assert (_tmp3_, "resultados.size >= 0 && resultados.size <= lim");
	_g_object_unref0 (resultados);
}


static void graph_media_test_artistas_editar_artista (GraphMediaTestArtistas* self) {
	GraphMediaModelosArtista* artista = NULL;
	GraphMediaGenerador* _tmp0_ = NULL;
	GraphMediaModelosArtista* _tmp1_ = NULL;
	GraphMediaModelosArtista* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	GraphMediaModelosArtistas* _tmp4_ = NULL;
	GraphMediaModelosArtista* _tmp5_ = NULL;
	GraphMediaModelosArtista* _tmp6_ = NULL;
	GraphMediaModelosArtista* registrado = NULL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	GraphMediaModelosArtista* _tmp8_ = NULL;
	gint64 _tmp9_ = 0LL;
	GraphMediaModelosArtista* _tmp10_ = NULL;
	GraphMediaModelosArtista* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GraphMediaModelosArtistas* _tmp13_ = NULL;
	GraphMediaModelosArtista* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	GraphMediaModelosArtista* _tmp16_ = NULL;
	GraphMediaModelosArtistas* _tmp17_ = NULL;
	GraphMediaModelosArtista* _tmp18_ = NULL;
	gint64 _tmp19_ = 0LL;
	GraphMediaModelosArtista* _tmp20_ = NULL;
	GraphMediaModelosArtista* _tmp21_ = NULL;
	GraphMediaModelosArtista* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	GraphMediaModelosArtista* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	GraphMediaModelosArtistas* _tmp26_ = NULL;
	GraphMediaModelosArtista* _tmp27_ = NULL;
	gboolean _tmp28_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp1_ = graph_media_generador_artista_aleatorio (_tmp0_);
	artista = _tmp1_;
	_tmp2_ = artista;
	_tmp3_ = ((GraphMediaModelosPersona*) _tmp2_)->id;
	_vala_assert (_tmp3_ == ((gint64) (-1)), "artista.id == -1");
	_tmp4_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp5_ = artista;
	_tmp6_ = graph_media_modelos_artistas_agregar (_tmp4_, _tmp5_);
	_graph_media_modelos_persona_unref0 (artista);
	artista = _tmp6_;
	_tmp7_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp8_ = artista;
	_tmp9_ = ((GraphMediaModelosPersona*) _tmp8_)->id;
	_tmp10_ = graph_media_modelos_artistas_get_artista_por_id (_tmp7_, _tmp9_, &_inner_error_);
	registrado = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = registrado;
	_tmp12_ = g_strdup ("Jonathan Andrade");
	_g_free0 (((GraphMediaModelosPersona*) _tmp11_)->nombre);
	((GraphMediaModelosPersona*) _tmp11_)->nombre = _tmp12_;
	_tmp13_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp14_ = registrado;
	_tmp15_ = graph_media_modelos_artistas_editar (_tmp13_, _tmp14_);
	_vala_assert (_tmp15_, "artistas.editar(registrado)");
	_tmp17_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp18_ = artista;
	_tmp19_ = ((GraphMediaModelosPersona*) _tmp18_)->id;
	_tmp20_ = graph_media_modelos_artistas_get_artista_por_id (_tmp17_, _tmp19_, &_inner_error_);
	_tmp16_ = _tmp20_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (registrado);
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp21_ = _tmp16_;
	_tmp16_ = NULL;
	_graph_media_modelos_persona_unref0 (registrado);
	registrado = _tmp21_;
	_tmp22_ = registrado;
	_tmp23_ = ((GraphMediaModelosPersona*) _tmp22_)->nombre;
	_vala_assert (g_strcmp0 (_tmp23_, "Jonathan Andrade") == 0, "registrado.nombre == \"Jonathan Andrade\"");
	_tmp24_ = registrado;
	_tmp25_ = g_strdup ("");
	_g_free0 (((GraphMediaModelosPersona*) _tmp24_)->nombre);
	((GraphMediaModelosPersona*) _tmp24_)->nombre = _tmp25_;
	_tmp26_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp27_ = registrado;
	_tmp28_ = graph_media_modelos_artistas_editar (_tmp26_, _tmp27_);
	_vala_assert (!_tmp28_, "!artistas.editar(registrado)");
	_graph_media_modelos_persona_unref0 (_tmp16_);
	_graph_media_modelos_persona_unref0 (registrado);
	_graph_media_modelos_persona_unref0 (artista);
}


static void graph_media_test_artistas_get_artista_por_id (GraphMediaTestArtistas* self) {
	GraphMediaModelosArtista* artista = NULL;
	GraphMediaGenerador* _tmp0_ = NULL;
	GraphMediaModelosArtista* _tmp1_ = NULL;
	GraphMediaModelosArtista* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	GraphMediaModelosArtistas* _tmp4_ = NULL;
	GraphMediaModelosArtista* _tmp5_ = NULL;
	GraphMediaModelosArtista* _tmp6_ = NULL;
	GraphMediaModelosArtista* registrado = NULL;
	GraphMediaModelosArtistas* _tmp7_ = NULL;
	GraphMediaModelosArtista* _tmp8_ = NULL;
	gint64 _tmp9_ = 0LL;
	GraphMediaModelosArtista* _tmp10_ = NULL;
	GraphMediaModelosArtista* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GraphMediaModelosArtistas* _tmp13_ = NULL;
	GraphMediaModelosArtista* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	GraphMediaModelosArtista* _tmp16_ = NULL;
	GraphMediaModelosArtistas* _tmp17_ = NULL;
	GraphMediaModelosArtista* _tmp18_ = NULL;
	gint64 _tmp19_ = 0LL;
	GraphMediaModelosArtista* _tmp20_ = NULL;
	GraphMediaModelosArtista* _tmp21_ = NULL;
	GraphMediaModelosArtista* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((GraphMediaTestBaseDeDatos*) self)->generador;
	_tmp1_ = graph_media_generador_artista_aleatorio (_tmp0_);
	artista = _tmp1_;
	_tmp2_ = artista;
	_tmp3_ = ((GraphMediaModelosPersona*) _tmp2_)->id;
	_vala_assert (_tmp3_ == ((gint64) (-1)), "artista.id == -1");
	_tmp4_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp5_ = artista;
	_tmp6_ = graph_media_modelos_artistas_agregar (_tmp4_, _tmp5_);
	_graph_media_modelos_persona_unref0 (artista);
	artista = _tmp6_;
	_tmp7_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp8_ = artista;
	_tmp9_ = ((GraphMediaModelosPersona*) _tmp8_)->id;
	_tmp10_ = graph_media_modelos_artistas_get_artista_por_id (_tmp7_, _tmp9_, &_inner_error_);
	registrado = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = registrado;
	_tmp12_ = g_strdup ("Jonathan Andrade");
	_g_free0 (((GraphMediaModelosPersona*) _tmp11_)->nombre);
	((GraphMediaModelosPersona*) _tmp11_)->nombre = _tmp12_;
	_tmp13_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp14_ = registrado;
	_tmp15_ = graph_media_modelos_artistas_editar (_tmp13_, _tmp14_);
	_vala_assert (_tmp15_, "artistas.editar(registrado)");
	_tmp17_ = ((GraphMediaTestBaseDeDatos*) self)->artistas;
	_tmp18_ = artista;
	_tmp19_ = ((GraphMediaModelosPersona*) _tmp18_)->id;
	_tmp20_ = graph_media_modelos_artistas_get_artista_por_id (_tmp17_, _tmp19_, &_inner_error_);
	_tmp16_ = _tmp20_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_graph_media_modelos_persona_unref0 (registrado);
		_graph_media_modelos_persona_unref0 (artista);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp21_ = _tmp16_;
	_tmp16_ = NULL;
	_graph_media_modelos_persona_unref0 (registrado);
	registrado = _tmp21_;
	_tmp22_ = registrado;
	_tmp23_ = ((GraphMediaModelosPersona*) _tmp22_)->nombre;
	_vala_assert (g_strcmp0 (_tmp23_, "Jonathan Andrade") == 0, "registrado.nombre == \"Jonathan Andrade\"");
	_graph_media_modelos_persona_unref0 (_tmp16_);
	_graph_media_modelos_persona_unref0 (registrado);
	_graph_media_modelos_persona_unref0 (artista);
}


static void graph_media_test_artistas_class_init (GraphMediaTestArtistasClass * klass) {
	graph_media_test_artistas_parent_class = g_type_class_peek_parent (klass);
	((GeeTestCaseClass *) klass)->set_up = graph_media_test_artistas_real_set_up;
}


static void graph_media_test_artistas_instance_init (GraphMediaTestArtistas * self) {
}


GType graph_media_test_artistas_get_type (void) {
	static volatile gsize graph_media_test_artistas_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_test_artistas_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaTestArtistasClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_test_artistas_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaTestArtistas), 0, (GInstanceInitFunc) graph_media_test_artistas_instance_init, NULL };
		GType graph_media_test_artistas_type_id;
		graph_media_test_artistas_type_id = g_type_register_static (GRAPH_MEDIA_TYPE_TEST_BASE_DE_DATOS, "GraphMediaTestArtistas", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_test_artistas_type_id__volatile, graph_media_test_artistas_type_id);
	}
	return graph_media_test_artistas_type_id__volatile;
}



