/* testgenerador.c generated by valac 0.26.0, the Vala compiler
 * generated from testgenerador.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "modelos.h"
#include <stdlib.h>
#include <string.h>


#define GEE_TYPE_TEST_CASE (gee_test_case_get_type ())
#define GEE_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_TEST_CASE, GeeTestCase))
#define GEE_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_TEST_CASE, GeeTestCaseClass))
#define GEE_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_TEST_CASE))
#define GEE_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_TEST_CASE))
#define GEE_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_TEST_CASE, GeeTestCaseClass))

typedef struct _GeeTestCase GeeTestCase;
typedef struct _GeeTestCaseClass GeeTestCaseClass;
typedef struct _GeeTestCasePrivate GeeTestCasePrivate;

#define GRAPH_MEDIA_TYPE_TEST_GENERADOR (graph_media_test_generador_get_type ())
#define GRAPH_MEDIA_TEST_GENERADOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_TEST_GENERADOR, GraphMediaTestGenerador))
#define GRAPH_MEDIA_TEST_GENERADOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_TEST_GENERADOR, GraphMediaTestGeneradorClass))
#define GRAPH_MEDIA_IS_TEST_GENERADOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_TEST_GENERADOR))
#define GRAPH_MEDIA_IS_TEST_GENERADOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_TEST_GENERADOR))
#define GRAPH_MEDIA_TEST_GENERADOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_TEST_GENERADOR, GraphMediaTestGeneradorClass))

typedef struct _GraphMediaTestGenerador GraphMediaTestGenerador;
typedef struct _GraphMediaTestGeneradorClass GraphMediaTestGeneradorClass;
typedef struct _GraphMediaTestGeneradorPrivate GraphMediaTestGeneradorPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GeeTestCase {
	GObject parent_instance;
	GeeTestCasePrivate * priv;
};

struct _GeeTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (GeeTestCase* self);
	void (*tear_down) (GeeTestCase* self);
};

struct _GraphMediaTestGenerador {
	GeeTestCase parent_instance;
	GraphMediaTestGeneradorPrivate * priv;
};

struct _GraphMediaTestGeneradorClass {
	GeeTestCaseClass parent_class;
};

struct _GraphMediaTestGeneradorPrivate {
	GraphMediaGenerador* gen;
	gint COTA_SUPERIOR;
};

typedef void (*GeeTestCaseTestMethod) (void* user_data);

static gpointer graph_media_test_generador_parent_class = NULL;

GType gee_test_case_get_type (void) G_GNUC_CONST;
GType graph_media_test_generador_get_type (void) G_GNUC_CONST;
#define GRAPH_MEDIA_TEST_GENERADOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRAPH_MEDIA_TYPE_TEST_GENERADOR, GraphMediaTestGeneradorPrivate))
enum  {
	GRAPH_MEDIA_TEST_GENERADOR_DUMMY_PROPERTY
};
GraphMediaTestGenerador* graph_media_test_generador_new (void);
GraphMediaTestGenerador* graph_media_test_generador_construct (GType object_type);
GeeTestCase* gee_test_case_construct (GType object_type, const gchar* name);
void gee_test_case_add_test (GeeTestCase* self, const gchar* name, GeeTestCaseTestMethod test, void* test_target);
static void graph_media_test_generador_palabra_aleatoria (GraphMediaTestGenerador* self);
static void _graph_media_test_generador_palabra_aleatoria_gee_test_case_test_method (gpointer self);
static void graph_media_test_generador_nombre_aleatorio (GraphMediaTestGenerador* self);
static void _graph_media_test_generador_nombre_aleatorio_gee_test_case_test_method (gpointer self);
static void graph_media_test_generador_ruta_aleatoria (GraphMediaTestGenerador* self);
static void _graph_media_test_generador_ruta_aleatoria_gee_test_case_test_method (gpointer self);
static void graph_media_test_generador_real_set_up (GeeTestCase* base);
static void graph_media_test_generador_real_tear_down (GeeTestCase* base);
static void graph_media_test_generador_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _graph_media_test_generador_palabra_aleatoria_gee_test_case_test_method (gpointer self) {
	graph_media_test_generador_palabra_aleatoria ((GraphMediaTestGenerador*) self);
}


static void _graph_media_test_generador_nombre_aleatorio_gee_test_case_test_method (gpointer self) {
	graph_media_test_generador_nombre_aleatorio ((GraphMediaTestGenerador*) self);
}


static void _graph_media_test_generador_ruta_aleatoria_gee_test_case_test_method (gpointer self) {
	graph_media_test_generador_ruta_aleatoria ((GraphMediaTestGenerador*) self);
}


GraphMediaTestGenerador* graph_media_test_generador_construct (GType object_type) {
	GraphMediaTestGenerador * self = NULL;
	self = (GraphMediaTestGenerador*) gee_test_case_construct (object_type, "Test.Generador");
	gee_test_case_add_test ((GeeTestCase*) self, "palabra aleatoria", _graph_media_test_generador_palabra_aleatoria_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "nombre aleatorio", _graph_media_test_generador_nombre_aleatorio_gee_test_case_test_method, self);
	gee_test_case_add_test ((GeeTestCase*) self, "ruta aleatoria", _graph_media_test_generador_ruta_aleatoria_gee_test_case_test_method, self);
	return self;
}


GraphMediaTestGenerador* graph_media_test_generador_new (void) {
	return graph_media_test_generador_construct (GRAPH_MEDIA_TYPE_TEST_GENERADOR);
}


static void graph_media_test_generador_real_set_up (GeeTestCase* base) {
	GraphMediaTestGenerador * self;
	GraphMediaGenerador* _tmp0_ = NULL;
	GraphMediaGenerador* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (GraphMediaTestGenerador*) base;
	_tmp0_ = graph_media_generador_new ("src/test/lista.txt");
	_g_object_unref0 (self->priv->gen);
	self->priv->gen = _tmp0_;
	_tmp1_ = self->priv->gen;
	_tmp2_ = graph_media_generador_edad_aleatoria (_tmp1_);
	self->priv->COTA_SUPERIOR = _tmp2_;
}


static void graph_media_test_generador_real_tear_down (GeeTestCase* base) {
	GraphMediaTestGenerador * self;
	self = (GraphMediaTestGenerador*) base;
}


static void graph_media_test_generador_palabra_aleatoria (GraphMediaTestGenerador* self) {
	gchar* s = NULL;
	GraphMediaGenerador* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gsize _tmp2_ = 0UL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->gen;
	_tmp1_ = graph_media_generador_palabra_aleatoria (_tmp0_);
	s = _tmp1_;
	_vala_assert (s != NULL, "s != null");
	_tmp2_ = strlen (s);
	_vala_assert (_tmp2_ != ((gsize) 0), "s.size() != 0");
	_g_free0 (s);
}


static void graph_media_test_generador_nombre_aleatorio (GraphMediaTestGenerador* self) {
	gint n = 0;
	gchar* nombre = NULL;
	GraphMediaGenerador* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar** split = NULL;
	const gchar* _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gint split_length1 = 0;
	gint _split_size_ = 0;
	GraphMediaGenerador* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar** _tmp9_ = NULL;
	gchar** _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	n = 4;
	_tmp0_ = self->priv->gen;
	_tmp1_ = graph_media_generador_nombre_aleatorio (_tmp0_, 2);
	nombre = _tmp1_;
	_tmp2_ = nombre;
	_vala_assert (_tmp2_ != NULL, "nombre != null");
	_tmp3_ = nombre;
	_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, " ", 0);
	split = _tmp5_;
	split_length1 = _vala_array_length (_tmp4_);
	_split_size_ = split_length1;
	_tmp6_ = self->priv->gen;
	_tmp7_ = graph_media_generador_nombre_aleatorio (_tmp6_, n);
	_g_free0 (nombre);
	nombre = _tmp7_;
	_tmp8_ = nombre;
	_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, " ", 0);
	split = (_vala_array_free (split, split_length1, (GDestroyNotify) g_free), NULL);
	split = _tmp10_;
	split_length1 = _vala_array_length (_tmp9_);
	_split_size_ = split_length1;
	split = (_vala_array_free (split, split_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (nombre);
}


static void graph_media_test_generador_ruta_aleatoria (GraphMediaTestGenerador* self) {
	gchar* ruta = NULL;
	gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	ruta = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				gint _tmp4_ = 0;
				gint n = 0;
				GraphMediaGenerador* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				GraphMediaGenerador* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gchar* _tmp9_ = NULL;
				const gchar* _tmp10_ = NULL;
				gchar** split = NULL;
				const gchar* _tmp11_ = NULL;
				gchar** _tmp12_ = NULL;
				gchar** _tmp13_ = NULL;
				gint split_length1 = 0;
				gint _split_size_ = 0;
				gchar** _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				gint _tmp15_ = 0;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->COTA_SUPERIOR;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = self->priv->gen;
				_tmp6_ = graph_media_generador_edad_aleatoria (_tmp5_);
				n = _tmp6_;
				_tmp7_ = self->priv->gen;
				_tmp8_ = n;
				_tmp9_ = graph_media_generador_ruta_aleatoria (_tmp7_, _tmp8_);
				_g_free0 (ruta);
				ruta = _tmp9_;
				_tmp10_ = ruta;
				_vala_assert (_tmp10_ != NULL, "ruta != null");
				_tmp11_ = ruta;
				_tmp13_ = _tmp12_ = g_strsplit (_tmp11_, "/", 0);
				split = _tmp13_;
				split_length1 = _vala_array_length (_tmp12_);
				_split_size_ = split_length1;
				_tmp14_ = split;
				_tmp14__length1 = split_length1;
				_tmp15_ = n;
				_vala_assert (_tmp14__length1 == _tmp15_, "split.length == n");
				split = (_vala_array_free (split, split_length1, (GDestroyNotify) g_free), NULL);
			}
		}
	}
	_g_free0 (ruta);
}


static void graph_media_test_generador_class_init (GraphMediaTestGeneradorClass * klass) {
	graph_media_test_generador_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraphMediaTestGeneradorPrivate));
	((GeeTestCaseClass *) klass)->set_up = graph_media_test_generador_real_set_up;
	((GeeTestCaseClass *) klass)->tear_down = graph_media_test_generador_real_tear_down;
	G_OBJECT_CLASS (klass)->finalize = graph_media_test_generador_finalize;
}


static void graph_media_test_generador_instance_init (GraphMediaTestGenerador * self) {
	self->priv = GRAPH_MEDIA_TEST_GENERADOR_GET_PRIVATE (self);
	self->priv->COTA_SUPERIOR = 50;
}


static void graph_media_test_generador_finalize (GObject* obj) {
	GraphMediaTestGenerador * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_TYPE_TEST_GENERADOR, GraphMediaTestGenerador);
	_g_object_unref0 (self->priv->gen);
	G_OBJECT_CLASS (graph_media_test_generador_parent_class)->finalize (obj);
}


GType graph_media_test_generador_get_type (void) {
	static volatile gsize graph_media_test_generador_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_test_generador_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaTestGeneradorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_test_generador_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaTestGenerador), 0, (GInstanceInitFunc) graph_media_test_generador_instance_init, NULL };
		GType graph_media_test_generador_type_id;
		graph_media_test_generador_type_id = g_type_register_static (GEE_TYPE_TEST_CASE, "GraphMediaTestGenerador", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_test_generador_type_id__volatile, graph_media_test_generador_type_id);
	}
	return graph_media_test_generador_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



