# Makefile.in generated by automake 1.13.4 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/graphmedia
pkgincludedir = $(includedir)/graphmedia
pkglibdir = $(libdir)/graphmedia
pkglibexecdir = $(libexecdir)/graphmedia
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = bin/graphmedia$(EXEEXT) test/run$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	src/controlador/graphmedia.c src/controlador/appgui.c \
	src/controlador/apppreferences.c src/controlador/dialogos.c \
	src/controlador/dialogoalbum.c \
	src/controlador/dialogoarchivo.c src/db/basedatos.c \
	src/db/tablas.c src/db/persona.c src/db/artista.c \
	src/db/archivo.c src/db/cancion.c src/db/imagen.c \
	src/db/album.c src/db/albumcanciones.c src/db/epoca.c \
	src/db/sentimientos.c src/test/generador.c src/main.c \
	src/test/testcase.c src/test/testpersona.c \
	src/test/testgenerador.c src/test/testbasedatos.c \
	src/test/testartistas.c src/test/testalbums.c \
	src/test/testsentimientos.c src/test/testcanciones.c \
	src/test/testimagenes.c src/test/main.c \
	$(top_srcdir)/build-aux/depcomp $(srcdir)/test_run_vala.stamp \
	$(srcdir)/bin_graphmedia_vala.stamp $(srcdir)/src/modelos.vapi \
	$(srcdir)/src/modelos.h $(srcdir)/src_libmodelos_la_vala.stamp \
	build-aux/compile build-aux/config.guess build-aux/config.sub \
	build-aux/depcomp build-aux/install-sh build-aux/missing \
	build-aux/ltmain.sh $(top_srcdir)/build-aux/compile \
	$(top_srcdir)/build-aux/config.guess \
	$(top_srcdir)/build-aux/config.sub \
	$(top_srcdir)/build-aux/install-sh \
	$(top_srcdir)/build-aux/ltmain.sh \
	$(top_srcdir)/build-aux/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LTLIBRARIES = $(noinst_LTLIBRARIES)
src_libmodelos_la_DEPENDENCIES =
am__dirstamp = $(am__leading_dot)dirstamp
am_src_libmodelos_la_OBJECTS =  \
	src/controlador/src_libmodelos_la-graphmedia.lo \
	src/controlador/src_libmodelos_la-appgui.lo \
	src/controlador/src_libmodelos_la-apppreferences.lo \
	src/controlador/src_libmodelos_la-dialogos.lo \
	src/controlador/src_libmodelos_la-dialogoalbum.lo \
	src/controlador/src_libmodelos_la-dialogoarchivo.lo \
	src/db/src_libmodelos_la-basedatos.lo \
	src/db/src_libmodelos_la-tablas.lo \
	src/db/src_libmodelos_la-persona.lo \
	src/db/src_libmodelos_la-artista.lo \
	src/db/src_libmodelos_la-archivo.lo \
	src/db/src_libmodelos_la-cancion.lo \
	src/db/src_libmodelos_la-imagen.lo \
	src/db/src_libmodelos_la-album.lo \
	src/db/src_libmodelos_la-albumcanciones.lo \
	src/db/src_libmodelos_la-epoca.lo \
	src/db/src_libmodelos_la-sentimientos.lo \
	src/test/src_libmodelos_la-generador.lo
src_libmodelos_la_OBJECTS = $(am_src_libmodelos_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
src_libmodelos_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(src_libmodelos_la_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_bin_graphmedia_OBJECTS = src/bin_graphmedia-main.$(OBJEXT) \
	src/bin_graphmedia-resources.$(OBJEXT)
bin_graphmedia_OBJECTS = $(am_bin_graphmedia_OBJECTS)
bin_graphmedia_DEPENDENCIES = src/libmodelos.la
bin_graphmedia_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(bin_graphmedia_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o \
	$@
am_test_run_OBJECTS = src/test/test_run-testcase.$(OBJEXT) \
	src/test/test_run-testpersona.$(OBJEXT) \
	src/test/test_run-testgenerador.$(OBJEXT) \
	src/test/test_run-testbasedatos.$(OBJEXT) \
	src/test/test_run-testartistas.$(OBJEXT) \
	src/test/test_run-testalbums.$(OBJEXT) \
	src/test/test_run-testsentimientos.$(OBJEXT) \
	src/test/test_run-testcanciones.$(OBJEXT) \
	src/test/test_run-testimagenes.$(OBJEXT) \
	src/test/test_run-main.$(OBJEXT)
test_run_OBJECTS = $(am_test_run_OBJECTS)
test_run_DEPENDENCIES = src/libmodelos.la
test_run_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(test_run_CFLAGS) \
	$(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
VALACOMPILE = $(VALAC) $(AM_VALAFLAGS) $(VALAFLAGS)
LTVALACOMPILE = $(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(VALAC) $(AM_VALAFLAGS) \
	$(VALAFLAGS)
AM_V_VALAC = $(am__v_VALAC_$(V))
am__v_VALAC_ = $(am__v_VALAC_$(AM_DEFAULT_VERBOSITY))
am__v_VALAC_0 = @echo "  VALAC   " $@;
am__v_VALAC_1 = 
SOURCES = $(src_libmodelos_la_SOURCES) $(bin_graphmedia_SOURCES) \
	$(test_run_SOURCES)
DIST_SOURCES = $(src_libmodelos_la_SOURCES) $(bin_graphmedia_SOURCES) \
	$(test_run_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(noinst_DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
GZIP_ENV = --best
DIST_ARCHIVES = $(distdir).tar.xz
DIST_TARGETS = dist-xz
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/missing aclocal-1.13
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/missing autoconf
AUTOHEADER = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/missing autoheader
AUTOMAKE = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/missing automake-1.13
AWK = gawk
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"graphmedia\" -DPACKAGE_TARNAME=\"graphmedia\" -DPACKAGE_VERSION=\"0.0\" -DPACKAGE_STRING=\"graphmedia\ 0.0\" -DPACKAGE_BUGREPORT=\"http://somesite.com\" -DPACKAGE_URL=\"https://somesite.com/bugs\" -DPACKAGE=\"graphmedia\" -DVERSION=\"0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DGETTEXT_PACKAGE=\"graphmedia\"
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GETTEXT_PACKAGE = graphmedia
GLIB_COMPILE_RESOURCES = /usr/bin/glib-compile-resources
GLIB_COMPILE_SCHEMAS = glib-compile-schemas
GRAPHMEDIA_CFLAGS = -pthread -I/usr/include/gee-0.8 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 
GRAPHMEDIA_LIBS = -lgee-0.8 -lsqlite3 -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 
GRAPHMEDIA_PACKAGES = --pkg gee-0.8 --pkg sqlite3 --pkg gtk+-3.0 --pkg gdk-x11-3.0 
GREP = /bin/grep
GSETTINGS_DISABLE_SCHEMAS_COMPILE = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = graphmedia
PACKAGE_BUGREPORT = http://somesite.com
PACKAGE_NAME = graphmedia
PACKAGE_STRING = graphmedia 0.0
PACKAGE_TARNAME = graphmedia
PACKAGE_URL = https://somesite.com/bugs
PACKAGE_VERSION = 0.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VALAC = /usr/local/bin/valac
VERSION = 0.0
abs_builddir = /home/ndrd/Desktop/graphmedia
abs_srcdir = /home/ndrd/Desktop/graphmedia
abs_top_builddir = /home/ndrd/Desktop/graphmedia
abs_top_srcdir = /home/ndrd/Desktop/graphmedia
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gsettingsschemadir = ${datarootdir}/glib-2.0/schemas
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/ndrd/Desktop/graphmedia/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
noinst_LTLIBRARIES = src/libmodelos.la
src_libmodelos_la_SOURCES = \
	src/controlador/graphmedia.vala \
	src/controlador/appgui.vala \
	src/controlador/apppreferences.vala \
	src/controlador/dialogos.vala \
	src/controlador/dialogoalbum.vala \
	src/controlador/dialogoarchivo.vala \
	src/db/basedatos.vala \
	src/db/tablas.vala \
	src/db/persona.vala \
	src/db/artista.vala \
	src/db/archivo.vala \
	src/db/cancion.vala \
	src/db/imagen.vala \
	src/db/album.vala \
	src/db/albumcanciones.vala \
	src/db/epoca.vala \
	src/db/sentimientos.vala \
	src/test/generador.vala \
	$(NULL)

src_libmodelos_la_VALAFLAGS = \
	--target-glib=2.38	\
	--pkg gmodule-2.0 \
	--vapi src/modelos.vapi \
	--header src/modelos.h \
	--gresources $(gresource_file)		\
	--pkg gee-0.8 --pkg sqlite3 --pkg gtk+-3.0 --pkg gdk-x11-3.0 		\
	$(NULL)

src_libmodelos_la_CFLAGS = \
	-pthread -I/usr/include/gee-0.8 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 		\
	-w

src_libmodelos_la_LIBADD = \
	-lgee-0.8 -lsqlite3 -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 		\
	$(NULL)

bin_graphmedia_SOURCES = \
	src/main.vala \
	src/modelos.vapi \
	src/resources.c \
	$(NULL)

bin_graphmedia_VALAFLAGS = \
	--target-glib=2.38	\
	--gresources $(gresource_file)		\
	--pkg gmodule-2.0 \
	--pkg gee-0.8 --pkg sqlite3 --pkg gtk+-3.0 --pkg gdk-x11-3.0 		\
	$(NULL)

bin_graphmedia_CFLAGS = \
	-pthread -I/usr/include/gee-0.8 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 		\
	-I$(srcdir)/src \
	-export-dynamic	\
	-w

bin_graphmedia_LDADD = \
	-lgee-0.8 -lsqlite3 -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 		\
	src/libmodelos.la \
	$(NULL)

gresource_file = $(top_srcdir)/src/ui/graphmedia.gresource.xml
resource_files = \
	$(top_srcdir)/src/ui/window.ui		\
	$(top_srcdir)/src/ui/gears-menu.ui		\
	$(top_srcdir)/src/ui/app-menu.ui		\
	$(top_srcdir)/src/ui/dialogs.ui		\
	$(top_srcdir)/src/ui/prefs.ui		\
	$(top_srcdir)/src/ui/home.ui		\
	$(top_srcdir)/src/ui/context.ui		\
	$(top_srcdir)/src/ui/details.ui		\
	$(top_srcdir)/src/ui/dialogoarchivo.ui		\
	$(top_srcdir)/src/ui/dialogoalbums.ui		\
	$(NULL)

schema_file = $(top_srcdir)/src/ui/org.gtk.graphmedia.gschema.xml
gsettings_SCHEMAS = \
	$(schema_file)				\
	$(NULL)

test_run_SOURCES = \
	src/test/testcase.vala \
	src/test/testpersona.vala \
	src/test/testgenerador.vala \
	src/test/testbasedatos.vala \
	src/test/testartistas.vala \
	src/test/testalbums.vala \
	src/test/testsentimientos.vala \
	src/test/testcanciones.vala \
	src/test/testimagenes.vala \
	src/test/main.vala \
	src/modelos.vapi \
	$(NULL)

test_run_VALAFLAGS = \
	--target-glib=2.38	\
	--pkg gee-0.8 --pkg sqlite3 --pkg gtk+-3.0 --pkg gdk-x11-3.0 		\
	$(NULL)

test_run_CFLAGS = \
	-pthread -I/usr/include/gee-0.8 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 		\
	-I$(srcdir)/src \
	-w \
	$(NULL)

test_run_LDADD = \
	-lgee-0.8 -lsqlite3 -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 		\
	src/libmodelos.la \
	$(NULL)

noinst_DATA = \
	$(gresource_file)			\
	$(resource_files)			\
	$(NULL)

EXTRA_DIST = \
	src/ui/graphmedia.desktop.in		\
	src/ui/graphmedia.gresource.xml		\
	$(resource_files)			\
	$(schema_file)				\
	$(NULL)

DISTCLEANFILES = \
	$(src/ui_desktop_DATA)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
	@list='$(noinst_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/controlador/$(am__dirstamp):
	@$(MKDIR_P) src/controlador
	@: > src/controlador/$(am__dirstamp)
src/controlador/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/controlador/$(DEPDIR)
	@: > src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-graphmedia.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-appgui.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-apppreferences.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-dialogos.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-dialogoalbum.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/controlador/src_libmodelos_la-dialogoarchivo.lo:  \
	src/controlador/$(am__dirstamp) \
	src/controlador/$(DEPDIR)/$(am__dirstamp)
src/db/$(am__dirstamp):
	@$(MKDIR_P) src/db
	@: > src/db/$(am__dirstamp)
src/db/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/db/$(DEPDIR)
	@: > src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-basedatos.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-tablas.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-persona.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-artista.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-archivo.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-cancion.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-imagen.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-album.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-albumcanciones.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-epoca.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/db/src_libmodelos_la-sentimientos.lo: src/db/$(am__dirstamp) \
	src/db/$(DEPDIR)/$(am__dirstamp)
src/test/$(am__dirstamp):
	@$(MKDIR_P) src/test
	@: > src/test/$(am__dirstamp)
src/test/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/test/$(DEPDIR)
	@: > src/test/$(DEPDIR)/$(am__dirstamp)
src/test/src_libmodelos_la-generador.lo: src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)

src/libmodelos.la: $(src_libmodelos_la_OBJECTS) $(src_libmodelos_la_DEPENDENCIES) $(EXTRA_src_libmodelos_la_DEPENDENCIES) src/$(am__dirstamp)
	$(AM_V_CCLD)$(src_libmodelos_la_LINK)  $(src_libmodelos_la_OBJECTS) $(src_libmodelos_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/bin_graphmedia-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/bin_graphmedia-resources.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
bin/$(am__dirstamp):
	@$(MKDIR_P) bin
	@: > bin/$(am__dirstamp)

bin/graphmedia$(EXEEXT): $(bin_graphmedia_OBJECTS) $(bin_graphmedia_DEPENDENCIES) $(EXTRA_bin_graphmedia_DEPENDENCIES) bin/$(am__dirstamp)
	@rm -f bin/graphmedia$(EXEEXT)
	$(AM_V_CCLD)$(bin_graphmedia_LINK) $(bin_graphmedia_OBJECTS) $(bin_graphmedia_LDADD) $(LIBS)
src/test/test_run-testcase.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testpersona.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testgenerador.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testbasedatos.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testartistas.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testalbums.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testsentimientos.$(OBJEXT):  \
	src/test/$(am__dirstamp) src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testcanciones.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-testimagenes.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
src/test/test_run-main.$(OBJEXT): src/test/$(am__dirstamp) \
	src/test/$(DEPDIR)/$(am__dirstamp)
test/$(am__dirstamp):
	@$(MKDIR_P) test
	@: > test/$(am__dirstamp)

test/run$(EXEEXT): $(test_run_OBJECTS) $(test_run_DEPENDENCIES) $(EXTRA_test_run_DEPENDENCIES) test/$(am__dirstamp)
	@rm -f test/run$(EXEEXT)
	$(AM_V_CCLD)$(test_run_LINK) $(test_run_OBJECTS) $(test_run_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/controlador/*.$(OBJEXT)
	-rm -f src/controlador/*.lo
	-rm -f src/db/*.$(OBJEXT)
	-rm -f src/db/*.lo
	-rm -f src/test/*.$(OBJEXT)
	-rm -f src/test/*.lo

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/bin_graphmedia-main.Po
include src/$(DEPDIR)/bin_graphmedia-resources.Po
include src/controlador/$(DEPDIR)/src_libmodelos_la-appgui.Plo
include src/controlador/$(DEPDIR)/src_libmodelos_la-apppreferences.Plo
include src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoalbum.Plo
include src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoarchivo.Plo
include src/controlador/$(DEPDIR)/src_libmodelos_la-dialogos.Plo
include src/controlador/$(DEPDIR)/src_libmodelos_la-graphmedia.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-album.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-albumcanciones.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-archivo.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-artista.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-basedatos.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-cancion.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-epoca.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-imagen.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-persona.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-sentimientos.Plo
include src/db/$(DEPDIR)/src_libmodelos_la-tablas.Plo
include src/test/$(DEPDIR)/src_libmodelos_la-generador.Plo
include src/test/$(DEPDIR)/test_run-main.Po
include src/test/$(DEPDIR)/test_run-testalbums.Po
include src/test/$(DEPDIR)/test_run-testartistas.Po
include src/test/$(DEPDIR)/test_run-testbasedatos.Po
include src/test/$(DEPDIR)/test_run-testcanciones.Po
include src/test/$(DEPDIR)/test_run-testcase.Po
include src/test/$(DEPDIR)/test_run-testgenerador.Po
include src/test/$(DEPDIR)/test_run-testimagenes.Po
include src/test/$(DEPDIR)/test_run-testpersona.Po
include src/test/$(DEPDIR)/test_run-testsentimientos.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

src/controlador/src_libmodelos_la-graphmedia.lo: src/controlador/graphmedia.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-graphmedia.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-graphmedia.Tpo -c -o src/controlador/src_libmodelos_la-graphmedia.lo `test -f 'src/controlador/graphmedia.c' || echo '$(srcdir)/'`src/controlador/graphmedia.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-graphmedia.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-graphmedia.Plo
#	$(AM_V_CC)source='src/controlador/graphmedia.c' object='src/controlador/src_libmodelos_la-graphmedia.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-graphmedia.lo `test -f 'src/controlador/graphmedia.c' || echo '$(srcdir)/'`src/controlador/graphmedia.c

src/controlador/src_libmodelos_la-appgui.lo: src/controlador/appgui.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-appgui.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-appgui.Tpo -c -o src/controlador/src_libmodelos_la-appgui.lo `test -f 'src/controlador/appgui.c' || echo '$(srcdir)/'`src/controlador/appgui.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-appgui.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-appgui.Plo
#	$(AM_V_CC)source='src/controlador/appgui.c' object='src/controlador/src_libmodelos_la-appgui.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-appgui.lo `test -f 'src/controlador/appgui.c' || echo '$(srcdir)/'`src/controlador/appgui.c

src/controlador/src_libmodelos_la-apppreferences.lo: src/controlador/apppreferences.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-apppreferences.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-apppreferences.Tpo -c -o src/controlador/src_libmodelos_la-apppreferences.lo `test -f 'src/controlador/apppreferences.c' || echo '$(srcdir)/'`src/controlador/apppreferences.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-apppreferences.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-apppreferences.Plo
#	$(AM_V_CC)source='src/controlador/apppreferences.c' object='src/controlador/src_libmodelos_la-apppreferences.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-apppreferences.lo `test -f 'src/controlador/apppreferences.c' || echo '$(srcdir)/'`src/controlador/apppreferences.c

src/controlador/src_libmodelos_la-dialogos.lo: src/controlador/dialogos.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-dialogos.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-dialogos.Tpo -c -o src/controlador/src_libmodelos_la-dialogos.lo `test -f 'src/controlador/dialogos.c' || echo '$(srcdir)/'`src/controlador/dialogos.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-dialogos.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-dialogos.Plo
#	$(AM_V_CC)source='src/controlador/dialogos.c' object='src/controlador/src_libmodelos_la-dialogos.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-dialogos.lo `test -f 'src/controlador/dialogos.c' || echo '$(srcdir)/'`src/controlador/dialogos.c

src/controlador/src_libmodelos_la-dialogoalbum.lo: src/controlador/dialogoalbum.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-dialogoalbum.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoalbum.Tpo -c -o src/controlador/src_libmodelos_la-dialogoalbum.lo `test -f 'src/controlador/dialogoalbum.c' || echo '$(srcdir)/'`src/controlador/dialogoalbum.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoalbum.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoalbum.Plo
#	$(AM_V_CC)source='src/controlador/dialogoalbum.c' object='src/controlador/src_libmodelos_la-dialogoalbum.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-dialogoalbum.lo `test -f 'src/controlador/dialogoalbum.c' || echo '$(srcdir)/'`src/controlador/dialogoalbum.c

src/controlador/src_libmodelos_la-dialogoarchivo.lo: src/controlador/dialogoarchivo.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/controlador/src_libmodelos_la-dialogoarchivo.lo -MD -MP -MF src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoarchivo.Tpo -c -o src/controlador/src_libmodelos_la-dialogoarchivo.lo `test -f 'src/controlador/dialogoarchivo.c' || echo '$(srcdir)/'`src/controlador/dialogoarchivo.c
	$(AM_V_at)$(am__mv) src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoarchivo.Tpo src/controlador/$(DEPDIR)/src_libmodelos_la-dialogoarchivo.Plo
#	$(AM_V_CC)source='src/controlador/dialogoarchivo.c' object='src/controlador/src_libmodelos_la-dialogoarchivo.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/controlador/src_libmodelos_la-dialogoarchivo.lo `test -f 'src/controlador/dialogoarchivo.c' || echo '$(srcdir)/'`src/controlador/dialogoarchivo.c

src/db/src_libmodelos_la-basedatos.lo: src/db/basedatos.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-basedatos.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-basedatos.Tpo -c -o src/db/src_libmodelos_la-basedatos.lo `test -f 'src/db/basedatos.c' || echo '$(srcdir)/'`src/db/basedatos.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-basedatos.Tpo src/db/$(DEPDIR)/src_libmodelos_la-basedatos.Plo
#	$(AM_V_CC)source='src/db/basedatos.c' object='src/db/src_libmodelos_la-basedatos.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-basedatos.lo `test -f 'src/db/basedatos.c' || echo '$(srcdir)/'`src/db/basedatos.c

src/db/src_libmodelos_la-tablas.lo: src/db/tablas.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-tablas.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-tablas.Tpo -c -o src/db/src_libmodelos_la-tablas.lo `test -f 'src/db/tablas.c' || echo '$(srcdir)/'`src/db/tablas.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-tablas.Tpo src/db/$(DEPDIR)/src_libmodelos_la-tablas.Plo
#	$(AM_V_CC)source='src/db/tablas.c' object='src/db/src_libmodelos_la-tablas.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-tablas.lo `test -f 'src/db/tablas.c' || echo '$(srcdir)/'`src/db/tablas.c

src/db/src_libmodelos_la-persona.lo: src/db/persona.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-persona.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-persona.Tpo -c -o src/db/src_libmodelos_la-persona.lo `test -f 'src/db/persona.c' || echo '$(srcdir)/'`src/db/persona.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-persona.Tpo src/db/$(DEPDIR)/src_libmodelos_la-persona.Plo
#	$(AM_V_CC)source='src/db/persona.c' object='src/db/src_libmodelos_la-persona.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-persona.lo `test -f 'src/db/persona.c' || echo '$(srcdir)/'`src/db/persona.c

src/db/src_libmodelos_la-artista.lo: src/db/artista.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-artista.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-artista.Tpo -c -o src/db/src_libmodelos_la-artista.lo `test -f 'src/db/artista.c' || echo '$(srcdir)/'`src/db/artista.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-artista.Tpo src/db/$(DEPDIR)/src_libmodelos_la-artista.Plo
#	$(AM_V_CC)source='src/db/artista.c' object='src/db/src_libmodelos_la-artista.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-artista.lo `test -f 'src/db/artista.c' || echo '$(srcdir)/'`src/db/artista.c

src/db/src_libmodelos_la-archivo.lo: src/db/archivo.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-archivo.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-archivo.Tpo -c -o src/db/src_libmodelos_la-archivo.lo `test -f 'src/db/archivo.c' || echo '$(srcdir)/'`src/db/archivo.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-archivo.Tpo src/db/$(DEPDIR)/src_libmodelos_la-archivo.Plo
#	$(AM_V_CC)source='src/db/archivo.c' object='src/db/src_libmodelos_la-archivo.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-archivo.lo `test -f 'src/db/archivo.c' || echo '$(srcdir)/'`src/db/archivo.c

src/db/src_libmodelos_la-cancion.lo: src/db/cancion.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-cancion.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-cancion.Tpo -c -o src/db/src_libmodelos_la-cancion.lo `test -f 'src/db/cancion.c' || echo '$(srcdir)/'`src/db/cancion.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-cancion.Tpo src/db/$(DEPDIR)/src_libmodelos_la-cancion.Plo
#	$(AM_V_CC)source='src/db/cancion.c' object='src/db/src_libmodelos_la-cancion.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-cancion.lo `test -f 'src/db/cancion.c' || echo '$(srcdir)/'`src/db/cancion.c

src/db/src_libmodelos_la-imagen.lo: src/db/imagen.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-imagen.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-imagen.Tpo -c -o src/db/src_libmodelos_la-imagen.lo `test -f 'src/db/imagen.c' || echo '$(srcdir)/'`src/db/imagen.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-imagen.Tpo src/db/$(DEPDIR)/src_libmodelos_la-imagen.Plo
#	$(AM_V_CC)source='src/db/imagen.c' object='src/db/src_libmodelos_la-imagen.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-imagen.lo `test -f 'src/db/imagen.c' || echo '$(srcdir)/'`src/db/imagen.c

src/db/src_libmodelos_la-album.lo: src/db/album.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-album.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-album.Tpo -c -o src/db/src_libmodelos_la-album.lo `test -f 'src/db/album.c' || echo '$(srcdir)/'`src/db/album.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-album.Tpo src/db/$(DEPDIR)/src_libmodelos_la-album.Plo
#	$(AM_V_CC)source='src/db/album.c' object='src/db/src_libmodelos_la-album.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-album.lo `test -f 'src/db/album.c' || echo '$(srcdir)/'`src/db/album.c

src/db/src_libmodelos_la-albumcanciones.lo: src/db/albumcanciones.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-albumcanciones.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-albumcanciones.Tpo -c -o src/db/src_libmodelos_la-albumcanciones.lo `test -f 'src/db/albumcanciones.c' || echo '$(srcdir)/'`src/db/albumcanciones.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-albumcanciones.Tpo src/db/$(DEPDIR)/src_libmodelos_la-albumcanciones.Plo
#	$(AM_V_CC)source='src/db/albumcanciones.c' object='src/db/src_libmodelos_la-albumcanciones.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-albumcanciones.lo `test -f 'src/db/albumcanciones.c' || echo '$(srcdir)/'`src/db/albumcanciones.c

src/db/src_libmodelos_la-epoca.lo: src/db/epoca.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-epoca.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-epoca.Tpo -c -o src/db/src_libmodelos_la-epoca.lo `test -f 'src/db/epoca.c' || echo '$(srcdir)/'`src/db/epoca.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-epoca.Tpo src/db/$(DEPDIR)/src_libmodelos_la-epoca.Plo
#	$(AM_V_CC)source='src/db/epoca.c' object='src/db/src_libmodelos_la-epoca.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-epoca.lo `test -f 'src/db/epoca.c' || echo '$(srcdir)/'`src/db/epoca.c

src/db/src_libmodelos_la-sentimientos.lo: src/db/sentimientos.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/db/src_libmodelos_la-sentimientos.lo -MD -MP -MF src/db/$(DEPDIR)/src_libmodelos_la-sentimientos.Tpo -c -o src/db/src_libmodelos_la-sentimientos.lo `test -f 'src/db/sentimientos.c' || echo '$(srcdir)/'`src/db/sentimientos.c
	$(AM_V_at)$(am__mv) src/db/$(DEPDIR)/src_libmodelos_la-sentimientos.Tpo src/db/$(DEPDIR)/src_libmodelos_la-sentimientos.Plo
#	$(AM_V_CC)source='src/db/sentimientos.c' object='src/db/src_libmodelos_la-sentimientos.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/db/src_libmodelos_la-sentimientos.lo `test -f 'src/db/sentimientos.c' || echo '$(srcdir)/'`src/db/sentimientos.c

src/test/src_libmodelos_la-generador.lo: src/test/generador.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -MT src/test/src_libmodelos_la-generador.lo -MD -MP -MF src/test/$(DEPDIR)/src_libmodelos_la-generador.Tpo -c -o src/test/src_libmodelos_la-generador.lo `test -f 'src/test/generador.c' || echo '$(srcdir)/'`src/test/generador.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/src_libmodelos_la-generador.Tpo src/test/$(DEPDIR)/src_libmodelos_la-generador.Plo
#	$(AM_V_CC)source='src/test/generador.c' object='src/test/src_libmodelos_la-generador.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(src_libmodelos_la_CFLAGS) $(CFLAGS) -c -o src/test/src_libmodelos_la-generador.lo `test -f 'src/test/generador.c' || echo '$(srcdir)/'`src/test/generador.c

src/bin_graphmedia-main.o: src/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -MT src/bin_graphmedia-main.o -MD -MP -MF src/$(DEPDIR)/bin_graphmedia-main.Tpo -c -o src/bin_graphmedia-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/bin_graphmedia-main.Tpo src/$(DEPDIR)/bin_graphmedia-main.Po
#	$(AM_V_CC)source='src/main.c' object='src/bin_graphmedia-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -c -o src/bin_graphmedia-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c

src/bin_graphmedia-main.obj: src/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -MT src/bin_graphmedia-main.obj -MD -MP -MF src/$(DEPDIR)/bin_graphmedia-main.Tpo -c -o src/bin_graphmedia-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/bin_graphmedia-main.Tpo src/$(DEPDIR)/bin_graphmedia-main.Po
#	$(AM_V_CC)source='src/main.c' object='src/bin_graphmedia-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -c -o src/bin_graphmedia-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`

src/bin_graphmedia-resources.o: src/resources.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -MT src/bin_graphmedia-resources.o -MD -MP -MF src/$(DEPDIR)/bin_graphmedia-resources.Tpo -c -o src/bin_graphmedia-resources.o `test -f 'src/resources.c' || echo '$(srcdir)/'`src/resources.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/bin_graphmedia-resources.Tpo src/$(DEPDIR)/bin_graphmedia-resources.Po
#	$(AM_V_CC)source='src/resources.c' object='src/bin_graphmedia-resources.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -c -o src/bin_graphmedia-resources.o `test -f 'src/resources.c' || echo '$(srcdir)/'`src/resources.c

src/bin_graphmedia-resources.obj: src/resources.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -MT src/bin_graphmedia-resources.obj -MD -MP -MF src/$(DEPDIR)/bin_graphmedia-resources.Tpo -c -o src/bin_graphmedia-resources.obj `if test -f 'src/resources.c'; then $(CYGPATH_W) 'src/resources.c'; else $(CYGPATH_W) '$(srcdir)/src/resources.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/bin_graphmedia-resources.Tpo src/$(DEPDIR)/bin_graphmedia-resources.Po
#	$(AM_V_CC)source='src/resources.c' object='src/bin_graphmedia-resources.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_graphmedia_CFLAGS) $(CFLAGS) -c -o src/bin_graphmedia-resources.obj `if test -f 'src/resources.c'; then $(CYGPATH_W) 'src/resources.c'; else $(CYGPATH_W) '$(srcdir)/src/resources.c'; fi`

src/test/test_run-testcase.o: src/test/testcase.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testcase.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testcase.Tpo -c -o src/test/test_run-testcase.o `test -f 'src/test/testcase.c' || echo '$(srcdir)/'`src/test/testcase.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testcase.Tpo src/test/$(DEPDIR)/test_run-testcase.Po
#	$(AM_V_CC)source='src/test/testcase.c' object='src/test/test_run-testcase.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testcase.o `test -f 'src/test/testcase.c' || echo '$(srcdir)/'`src/test/testcase.c

src/test/test_run-testcase.obj: src/test/testcase.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testcase.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testcase.Tpo -c -o src/test/test_run-testcase.obj `if test -f 'src/test/testcase.c'; then $(CYGPATH_W) 'src/test/testcase.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testcase.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testcase.Tpo src/test/$(DEPDIR)/test_run-testcase.Po
#	$(AM_V_CC)source='src/test/testcase.c' object='src/test/test_run-testcase.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testcase.obj `if test -f 'src/test/testcase.c'; then $(CYGPATH_W) 'src/test/testcase.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testcase.c'; fi`

src/test/test_run-testpersona.o: src/test/testpersona.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testpersona.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testpersona.Tpo -c -o src/test/test_run-testpersona.o `test -f 'src/test/testpersona.c' || echo '$(srcdir)/'`src/test/testpersona.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testpersona.Tpo src/test/$(DEPDIR)/test_run-testpersona.Po
#	$(AM_V_CC)source='src/test/testpersona.c' object='src/test/test_run-testpersona.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testpersona.o `test -f 'src/test/testpersona.c' || echo '$(srcdir)/'`src/test/testpersona.c

src/test/test_run-testpersona.obj: src/test/testpersona.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testpersona.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testpersona.Tpo -c -o src/test/test_run-testpersona.obj `if test -f 'src/test/testpersona.c'; then $(CYGPATH_W) 'src/test/testpersona.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testpersona.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testpersona.Tpo src/test/$(DEPDIR)/test_run-testpersona.Po
#	$(AM_V_CC)source='src/test/testpersona.c' object='src/test/test_run-testpersona.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testpersona.obj `if test -f 'src/test/testpersona.c'; then $(CYGPATH_W) 'src/test/testpersona.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testpersona.c'; fi`

src/test/test_run-testgenerador.o: src/test/testgenerador.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testgenerador.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testgenerador.Tpo -c -o src/test/test_run-testgenerador.o `test -f 'src/test/testgenerador.c' || echo '$(srcdir)/'`src/test/testgenerador.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testgenerador.Tpo src/test/$(DEPDIR)/test_run-testgenerador.Po
#	$(AM_V_CC)source='src/test/testgenerador.c' object='src/test/test_run-testgenerador.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testgenerador.o `test -f 'src/test/testgenerador.c' || echo '$(srcdir)/'`src/test/testgenerador.c

src/test/test_run-testgenerador.obj: src/test/testgenerador.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testgenerador.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testgenerador.Tpo -c -o src/test/test_run-testgenerador.obj `if test -f 'src/test/testgenerador.c'; then $(CYGPATH_W) 'src/test/testgenerador.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testgenerador.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testgenerador.Tpo src/test/$(DEPDIR)/test_run-testgenerador.Po
#	$(AM_V_CC)source='src/test/testgenerador.c' object='src/test/test_run-testgenerador.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testgenerador.obj `if test -f 'src/test/testgenerador.c'; then $(CYGPATH_W) 'src/test/testgenerador.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testgenerador.c'; fi`

src/test/test_run-testbasedatos.o: src/test/testbasedatos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testbasedatos.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testbasedatos.Tpo -c -o src/test/test_run-testbasedatos.o `test -f 'src/test/testbasedatos.c' || echo '$(srcdir)/'`src/test/testbasedatos.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testbasedatos.Tpo src/test/$(DEPDIR)/test_run-testbasedatos.Po
#	$(AM_V_CC)source='src/test/testbasedatos.c' object='src/test/test_run-testbasedatos.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testbasedatos.o `test -f 'src/test/testbasedatos.c' || echo '$(srcdir)/'`src/test/testbasedatos.c

src/test/test_run-testbasedatos.obj: src/test/testbasedatos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testbasedatos.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testbasedatos.Tpo -c -o src/test/test_run-testbasedatos.obj `if test -f 'src/test/testbasedatos.c'; then $(CYGPATH_W) 'src/test/testbasedatos.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testbasedatos.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testbasedatos.Tpo src/test/$(DEPDIR)/test_run-testbasedatos.Po
#	$(AM_V_CC)source='src/test/testbasedatos.c' object='src/test/test_run-testbasedatos.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testbasedatos.obj `if test -f 'src/test/testbasedatos.c'; then $(CYGPATH_W) 'src/test/testbasedatos.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testbasedatos.c'; fi`

src/test/test_run-testartistas.o: src/test/testartistas.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testartistas.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testartistas.Tpo -c -o src/test/test_run-testartistas.o `test -f 'src/test/testartistas.c' || echo '$(srcdir)/'`src/test/testartistas.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testartistas.Tpo src/test/$(DEPDIR)/test_run-testartistas.Po
#	$(AM_V_CC)source='src/test/testartistas.c' object='src/test/test_run-testartistas.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testartistas.o `test -f 'src/test/testartistas.c' || echo '$(srcdir)/'`src/test/testartistas.c

src/test/test_run-testartistas.obj: src/test/testartistas.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testartistas.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testartistas.Tpo -c -o src/test/test_run-testartistas.obj `if test -f 'src/test/testartistas.c'; then $(CYGPATH_W) 'src/test/testartistas.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testartistas.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testartistas.Tpo src/test/$(DEPDIR)/test_run-testartistas.Po
#	$(AM_V_CC)source='src/test/testartistas.c' object='src/test/test_run-testartistas.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testartistas.obj `if test -f 'src/test/testartistas.c'; then $(CYGPATH_W) 'src/test/testartistas.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testartistas.c'; fi`

src/test/test_run-testalbums.o: src/test/testalbums.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testalbums.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testalbums.Tpo -c -o src/test/test_run-testalbums.o `test -f 'src/test/testalbums.c' || echo '$(srcdir)/'`src/test/testalbums.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testalbums.Tpo src/test/$(DEPDIR)/test_run-testalbums.Po
#	$(AM_V_CC)source='src/test/testalbums.c' object='src/test/test_run-testalbums.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testalbums.o `test -f 'src/test/testalbums.c' || echo '$(srcdir)/'`src/test/testalbums.c

src/test/test_run-testalbums.obj: src/test/testalbums.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testalbums.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testalbums.Tpo -c -o src/test/test_run-testalbums.obj `if test -f 'src/test/testalbums.c'; then $(CYGPATH_W) 'src/test/testalbums.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testalbums.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testalbums.Tpo src/test/$(DEPDIR)/test_run-testalbums.Po
#	$(AM_V_CC)source='src/test/testalbums.c' object='src/test/test_run-testalbums.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testalbums.obj `if test -f 'src/test/testalbums.c'; then $(CYGPATH_W) 'src/test/testalbums.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testalbums.c'; fi`

src/test/test_run-testsentimientos.o: src/test/testsentimientos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testsentimientos.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testsentimientos.Tpo -c -o src/test/test_run-testsentimientos.o `test -f 'src/test/testsentimientos.c' || echo '$(srcdir)/'`src/test/testsentimientos.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testsentimientos.Tpo src/test/$(DEPDIR)/test_run-testsentimientos.Po
#	$(AM_V_CC)source='src/test/testsentimientos.c' object='src/test/test_run-testsentimientos.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testsentimientos.o `test -f 'src/test/testsentimientos.c' || echo '$(srcdir)/'`src/test/testsentimientos.c

src/test/test_run-testsentimientos.obj: src/test/testsentimientos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testsentimientos.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testsentimientos.Tpo -c -o src/test/test_run-testsentimientos.obj `if test -f 'src/test/testsentimientos.c'; then $(CYGPATH_W) 'src/test/testsentimientos.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testsentimientos.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testsentimientos.Tpo src/test/$(DEPDIR)/test_run-testsentimientos.Po
#	$(AM_V_CC)source='src/test/testsentimientos.c' object='src/test/test_run-testsentimientos.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testsentimientos.obj `if test -f 'src/test/testsentimientos.c'; then $(CYGPATH_W) 'src/test/testsentimientos.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testsentimientos.c'; fi`

src/test/test_run-testcanciones.o: src/test/testcanciones.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testcanciones.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testcanciones.Tpo -c -o src/test/test_run-testcanciones.o `test -f 'src/test/testcanciones.c' || echo '$(srcdir)/'`src/test/testcanciones.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testcanciones.Tpo src/test/$(DEPDIR)/test_run-testcanciones.Po
#	$(AM_V_CC)source='src/test/testcanciones.c' object='src/test/test_run-testcanciones.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testcanciones.o `test -f 'src/test/testcanciones.c' || echo '$(srcdir)/'`src/test/testcanciones.c

src/test/test_run-testcanciones.obj: src/test/testcanciones.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testcanciones.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testcanciones.Tpo -c -o src/test/test_run-testcanciones.obj `if test -f 'src/test/testcanciones.c'; then $(CYGPATH_W) 'src/test/testcanciones.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testcanciones.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testcanciones.Tpo src/test/$(DEPDIR)/test_run-testcanciones.Po
#	$(AM_V_CC)source='src/test/testcanciones.c' object='src/test/test_run-testcanciones.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testcanciones.obj `if test -f 'src/test/testcanciones.c'; then $(CYGPATH_W) 'src/test/testcanciones.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testcanciones.c'; fi`

src/test/test_run-testimagenes.o: src/test/testimagenes.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testimagenes.o -MD -MP -MF src/test/$(DEPDIR)/test_run-testimagenes.Tpo -c -o src/test/test_run-testimagenes.o `test -f 'src/test/testimagenes.c' || echo '$(srcdir)/'`src/test/testimagenes.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testimagenes.Tpo src/test/$(DEPDIR)/test_run-testimagenes.Po
#	$(AM_V_CC)source='src/test/testimagenes.c' object='src/test/test_run-testimagenes.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testimagenes.o `test -f 'src/test/testimagenes.c' || echo '$(srcdir)/'`src/test/testimagenes.c

src/test/test_run-testimagenes.obj: src/test/testimagenes.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-testimagenes.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-testimagenes.Tpo -c -o src/test/test_run-testimagenes.obj `if test -f 'src/test/testimagenes.c'; then $(CYGPATH_W) 'src/test/testimagenes.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testimagenes.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-testimagenes.Tpo src/test/$(DEPDIR)/test_run-testimagenes.Po
#	$(AM_V_CC)source='src/test/testimagenes.c' object='src/test/test_run-testimagenes.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-testimagenes.obj `if test -f 'src/test/testimagenes.c'; then $(CYGPATH_W) 'src/test/testimagenes.c'; else $(CYGPATH_W) '$(srcdir)/src/test/testimagenes.c'; fi`

src/test/test_run-main.o: src/test/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-main.o -MD -MP -MF src/test/$(DEPDIR)/test_run-main.Tpo -c -o src/test/test_run-main.o `test -f 'src/test/main.c' || echo '$(srcdir)/'`src/test/main.c
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-main.Tpo src/test/$(DEPDIR)/test_run-main.Po
#	$(AM_V_CC)source='src/test/main.c' object='src/test/test_run-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-main.o `test -f 'src/test/main.c' || echo '$(srcdir)/'`src/test/main.c

src/test/test_run-main.obj: src/test/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -MT src/test/test_run-main.obj -MD -MP -MF src/test/$(DEPDIR)/test_run-main.Tpo -c -o src/test/test_run-main.obj `if test -f 'src/test/main.c'; then $(CYGPATH_W) 'src/test/main.c'; else $(CYGPATH_W) '$(srcdir)/src/test/main.c'; fi`
	$(AM_V_at)$(am__mv) src/test/$(DEPDIR)/test_run-main.Tpo src/test/$(DEPDIR)/test_run-main.Po
#	$(AM_V_CC)source='src/test/main.c' object='src/test/test_run-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_run_CFLAGS) $(CFLAGS) -c -o src/test/test_run-main.obj `if test -f 'src/test/main.c'; then $(CYGPATH_W) 'src/test/main.c'; else $(CYGPATH_W) '$(srcdir)/src/test/main.c'; fi`
$(srcdir)/src/test/testcase.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testpersona.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testgenerador.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testbasedatos.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testartistas.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testalbums.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testsentimientos.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testcanciones.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/testimagenes.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/src/test/main.c: $(srcdir)/test_run_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/test_run_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/test_run_vala.stamp; \
	fi
$(srcdir)/test_run_vala.stamp: src/test/testcase.vala src/test/testpersona.vala src/test/testgenerador.vala src/test/testbasedatos.vala src/test/testartistas.vala src/test/testalbums.vala src/test/testsentimientos.vala src/test/testcanciones.vala src/test/testimagenes.vala src/test/main.vala src/modelos.vapi
	$(AM_V_at)rm -f $@ && echo stamp > $@-t
	$(AM_V_VALAC)$(am__cd) $(srcdir) && $(VALAC) $(test_run_VALAFLAGS) $(VALAFLAGS) -C src/test/testcase.vala src/test/testpersona.vala src/test/testgenerador.vala src/test/testbasedatos.vala src/test/testartistas.vala src/test/testalbums.vala src/test/testsentimientos.vala src/test/testcanciones.vala src/test/testimagenes.vala src/test/main.vala src/modelos.vapi
	$(AM_V_at)mv -f $@-t $@
$(srcdir)/src/main.c: $(srcdir)/bin_graphmedia_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/bin_graphmedia_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/bin_graphmedia_vala.stamp; \
	fi
$(srcdir)/bin_graphmedia_vala.stamp: src/main.vala src/modelos.vapi
	$(AM_V_at)rm -f $@ && echo stamp > $@-t
	$(AM_V_VALAC)$(am__cd) $(srcdir) && $(VALAC) $(bin_graphmedia_VALAFLAGS) $(VALAFLAGS) -C src/main.vala src/modelos.vapi
	$(AM_V_at)mv -f $@-t $@
$(srcdir)/src/controlador/graphmedia.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/controlador/appgui.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/controlador/apppreferences.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/controlador/dialogos.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/controlador/dialogoalbum.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/controlador/dialogoarchivo.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/basedatos.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/tablas.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/persona.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/artista.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/archivo.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/cancion.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/imagen.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/album.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/albumcanciones.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/epoca.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/db/sentimientos.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/test/generador.c: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/modelos.vapi: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src/modelos.h: $(srcdir)/src_libmodelos_la_vala.stamp
	@if test -f $@; then :; else rm -f $(srcdir)/src_libmodelos_la_vala.stamp; fi
	@if test -f $@; then :; else \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/src_libmodelos_la_vala.stamp; \
	fi
$(srcdir)/src_libmodelos_la_vala.stamp: src/controlador/graphmedia.vala src/controlador/appgui.vala src/controlador/apppreferences.vala src/controlador/dialogos.vala src/controlador/dialogoalbum.vala src/controlador/dialogoarchivo.vala src/db/basedatos.vala src/db/tablas.vala src/db/persona.vala src/db/artista.vala src/db/archivo.vala src/db/cancion.vala src/db/imagen.vala src/db/album.vala src/db/albumcanciones.vala src/db/epoca.vala src/db/sentimientos.vala src/test/generador.vala
	$(AM_V_at)rm -f $@ && echo stamp > $@-t
	$(AM_V_VALAC)$(am__cd) $(srcdir) && $(VALAC) $(src_libmodelos_la_VALAFLAGS) $(VALAFLAGS) -C src/controlador/graphmedia.vala src/controlador/appgui.vala src/controlador/apppreferences.vala src/controlador/dialogos.vala src/controlador/dialogoalbum.vala src/controlador/dialogoarchivo.vala src/db/basedatos.vala src/db/tablas.vala src/db/persona.vala src/db/artista.vala src/db/archivo.vala src/db/cancion.vala src/db/imagen.vala src/db/album.vala src/db/albumcanciones.vala src/db/epoca.vala src/db/sentimientos.vala src/test/generador.vala
	$(AM_V_at)mv -f $@-t $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf bin/.libs bin/_libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/controlador/.libs src/controlador/_libs
	-rm -rf src/db/.libs src/db/_libs
	-rm -rf src/test/.libs src/test/_libs
	-rm -rf test/.libs test/_libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)
dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f bin/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/controlador/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/controlador/$(am__dirstamp)
	-rm -f src/db/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/db/$(am__dirstamp)
	-rm -f src/test/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/test/$(am__dirstamp)
	-rm -f test/$(am__dirstamp)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f $(srcdir)/bin_graphmedia_vala.stamp
	-rm -f $(srcdir)/src/controlador/appgui.c
	-rm -f $(srcdir)/src/controlador/apppreferences.c
	-rm -f $(srcdir)/src/controlador/dialogoalbum.c
	-rm -f $(srcdir)/src/controlador/dialogoarchivo.c
	-rm -f $(srcdir)/src/controlador/dialogos.c
	-rm -f $(srcdir)/src/controlador/graphmedia.c
	-rm -f $(srcdir)/src/db/album.c
	-rm -f $(srcdir)/src/db/albumcanciones.c
	-rm -f $(srcdir)/src/db/archivo.c
	-rm -f $(srcdir)/src/db/artista.c
	-rm -f $(srcdir)/src/db/basedatos.c
	-rm -f $(srcdir)/src/db/cancion.c
	-rm -f $(srcdir)/src/db/epoca.c
	-rm -f $(srcdir)/src/db/imagen.c
	-rm -f $(srcdir)/src/db/persona.c
	-rm -f $(srcdir)/src/db/sentimientos.c
	-rm -f $(srcdir)/src/db/tablas.c
	-rm -f $(srcdir)/src/main.c
	-rm -f $(srcdir)/src/modelos.h
	-rm -f $(srcdir)/src/modelos.vapi
	-rm -f $(srcdir)/src/test/generador.c
	-rm -f $(srcdir)/src/test/main.c
	-rm -f $(srcdir)/src/test/testalbums.c
	-rm -f $(srcdir)/src/test/testartistas.c
	-rm -f $(srcdir)/src/test/testbasedatos.c
	-rm -f $(srcdir)/src/test/testcanciones.c
	-rm -f $(srcdir)/src/test/testcase.c
	-rm -f $(srcdir)/src/test/testgenerador.c
	-rm -f $(srcdir)/src/test/testimagenes.c
	-rm -f $(srcdir)/src/test/testpersona.c
	-rm -f $(srcdir)/src/test/testsentimientos.c
	-rm -f $(srcdir)/src_libmodelos_la_vala.stamp
	-rm -f $(srcdir)/test_run_vala.stamp
	-rm -f src/controlador/appgui.c
	-rm -f src/controlador/apppreferences.c
	-rm -f src/controlador/dialogoalbum.c
	-rm -f src/controlador/dialogoarchivo.c
	-rm -f src/controlador/dialogos.c
	-rm -f src/controlador/graphmedia.c
	-rm -f src/db/album.c
	-rm -f src/db/albumcanciones.c
	-rm -f src/db/archivo.c
	-rm -f src/db/artista.c
	-rm -f src/db/basedatos.c
	-rm -f src/db/cancion.c
	-rm -f src/db/epoca.c
	-rm -f src/db/imagen.c
	-rm -f src/db/persona.c
	-rm -f src/db/sentimientos.c
	-rm -f src/db/tablas.c
	-rm -f src/main.c
	-rm -f src/test/generador.c
	-rm -f src/test/main.c
	-rm -f src/test/testalbums.c
	-rm -f src/test/testartistas.c
	-rm -f src/test/testbasedatos.c
	-rm -f src/test/testcanciones.c
	-rm -f src/test/testcase.c
	-rm -f src/test/testgenerador.c
	-rm -f src/test/testimagenes.c
	-rm -f src/test/testpersona.c
	-rm -f src/test/testsentimientos.c
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool \
	clean-noinstLTLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/controlador/$(DEPDIR) src/db/$(DEPDIR) src/test/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/controlador/$(DEPDIR) src/db/$(DEPDIR) src/test/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic clean-libtool \
	clean-noinstLTLIBRARIES cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS

	-export-dynamic	\
	-dynamic-export \
	-rdynamic \
	$(NULL)
	$(NULL)

src/resources.c: $(gresource_file) $(resource_files)
	$(AM_V_GEN) $(GLIB_COMPILE_RESOURCES) 	\
		--target=$@			\
		--sourcedir=$(top_srcdir)/src/ui	\
		--generate-source $<


.PHONY : uninstall-gsettings-schemas install-gsettings-schemas clean-gsettings-schemas

mostlyclean-am: clean-gsettings-schemas

gsettings__enum_file = $(addsuffix .enums.xml,$(gsettings_ENUM_NAMESPACE))

%.gschema.valid: %.gschema.xml $(gsettings__enum_file)
	$(AM_V_GEN) $(GLIB_COMPILE_SCHEMAS) --strict --dry-run $(addprefix --schema-file=,$(gsettings__enum_file)) --schema-file=$< && mkdir -p $(@D) && touch $@

all-am: $(gsettings_SCHEMAS:.xml=.valid)
uninstall-am: uninstall-gsettings-schemas
install-data-am: install-gsettings-schemas

.SECONDARY: $(gsettings_SCHEMAS)

install-gsettings-schemas: $(gsettings_SCHEMAS) $(gsettings__enum_file)
	@$(NORMAL_INSTALL)
	if test -n "$^"; then \
		test -z "$(gsettingsschemadir)" || $(MKDIR_P) "$(DESTDIR)$(gsettingsschemadir)"; \
		$(INSTALL_DATA) $^ "$(DESTDIR)$(gsettingsschemadir)"; \
		test -n "$(GSETTINGS_DISABLE_SCHEMAS_COMPILE)$(DESTDIR)" || $(GLIB_COMPILE_SCHEMAS) $(gsettingsschemadir); \
	fi

uninstall-gsettings-schemas:
	@$(NORMAL_UNINSTALL)
	@list='$(gsettings_SCHEMAS) $(gsettings__enum_file)'; test -n "$(gsettingsschemadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(gsettingsschemadir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(gsettingsschemadir)" && rm -f $$files
	test -n "$(GSETTINGS_DISABLE_SCHEMAS_COMPILE)$(DESTDIR)" || $(GLIB_COMPILE_SCHEMAS) $(gsettingsschemadir)

clean-gsettings-schemas:
	rm -f $(gsettings_SCHEMAS:.xml=.valid) $(gsettings__enum_file)

ifdef gsettings_ENUM_NAMESPACE
$(gsettings__enum_file): $(gsettings_ENUM_FILES)
	$(AM_V_GEN) glib-mkenums --comments '<!-- @comment@ -->' --fhead "<schemalist>" --vhead "  <@type@ id='$(gsettings_ENUM_NAMESPACE).@EnumName@'>" --vprod "    <value nick='@valuenick@' value='@valuenum@'/>" --vtail "  </@type@>" --ftail "</schemalist>" $^ > $@.tmp && mv $@.tmp $@
endif


data/gschemas.compiled: $(schema_file)
	$(GLIB_COMPILE_SCHEMAS) $(top_srcdir)/src/ui

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
