/* album.c generated by valac 0.26.0, the Vala compiler
 * generated from album.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gtk/gtk.h>
#include <sqlite3.h>
#include <stdio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gobject/gvaluecollector.h>


#define GRAPH_MEDIA_MODELOS_TYPE_ALBUM (graph_media_modelos_album_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM, GraphMediaModelosAlbum))
#define GRAPH_MEDIA_MODELOS_ALBUM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM, GraphMediaModelosAlbumClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM))
#define GRAPH_MEDIA_MODELOS_ALBUM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM, GraphMediaModelosAlbumClass))

typedef struct _GraphMediaModelosAlbum GraphMediaModelosAlbum;
typedef struct _GraphMediaModelosAlbumClass GraphMediaModelosAlbumClass;
typedef struct _GraphMediaModelosAlbumPrivate GraphMediaModelosAlbumPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES (graph_media_modelos_album_imagenes_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUM_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, GraphMediaModelosAlbumImagenes))
#define GRAPH_MEDIA_MODELOS_ALBUM_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, GraphMediaModelosAlbumImagenesClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES))
#define GRAPH_MEDIA_MODELOS_ALBUM_IMAGENES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, GraphMediaModelosAlbumImagenesClass))

typedef struct _GraphMediaModelosAlbumImagenes GraphMediaModelosAlbumImagenes;
typedef struct _GraphMediaModelosAlbumImagenesClass GraphMediaModelosAlbumImagenesClass;
#define _graph_media_modelos_album_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_modelos_album_unref (var), NULL)))

#define GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES (graph_media_modelos_album_canciones_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUM_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES, GraphMediaModelosAlbumCanciones))
#define GRAPH_MEDIA_MODELOS_ALBUM_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES, GraphMediaModelosAlbumCancionesClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES))
#define GRAPH_MEDIA_MODELOS_IS_ALBUM_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES))
#define GRAPH_MEDIA_MODELOS_ALBUM_CANCIONES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES, GraphMediaModelosAlbumCancionesClass))

typedef struct _GraphMediaModelosAlbumCanciones GraphMediaModelosAlbumCanciones;
typedef struct _GraphMediaModelosAlbumCancionesClass GraphMediaModelosAlbumCancionesClass;
typedef struct _GraphMediaModelosParamSpecAlbum GraphMediaModelosParamSpecAlbum;
typedef struct _GraphMediaModelosAlbumImagenesPrivate GraphMediaModelosAlbumImagenesPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_EPOCA (graph_media_modelos_epoca_get_type ())
typedef struct _GraphMediaModelosEpoca GraphMediaModelosEpoca;

#define GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO (graph_media_modelos_archivo_get_type ())
#define GRAPH_MEDIA_MODELOS_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivo))
#define GRAPH_MEDIA_MODELOS_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivoClass))
#define GRAPH_MEDIA_MODELOS_IS_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_IS_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_ARCHIVO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivoClass))

typedef struct _GraphMediaModelosArchivo GraphMediaModelosArchivo;
typedef struct _GraphMediaModelosArchivoClass GraphMediaModelosArchivoClass;

#define GRAPH_MEDIA_MODELOS_TYPE_IMAGEN (graph_media_modelos_imagen_get_type ())
#define GRAPH_MEDIA_MODELOS_IMAGEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGEN, GraphMediaModelosImagen))
#define GRAPH_MEDIA_MODELOS_IMAGEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_IMAGEN, GraphMediaModelosImagenClass))
#define GRAPH_MEDIA_MODELOS_IS_IMAGEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGEN))
#define GRAPH_MEDIA_MODELOS_IS_IMAGEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_IMAGEN))
#define GRAPH_MEDIA_MODELOS_IMAGEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGEN, GraphMediaModelosImagenClass))

typedef struct _GraphMediaModelosImagen GraphMediaModelosImagen;
typedef struct _GraphMediaModelosImagenClass GraphMediaModelosImagenClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GRAPH_MEDIA_MODELOS_TYPE_TABLAS (graph_media_modelos_tablas_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablas))
#define GRAPH_MEDIA_MODELOS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_TABLAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))

typedef struct _GraphMediaModelosTablas GraphMediaModelosTablas;
typedef struct _GraphMediaModelosTablasClass GraphMediaModelosTablasClass;
typedef struct _GraphMediaModelosTablasPrivate GraphMediaModelosTablasPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_FILTRABLE (graph_media_modelos_filtrable_get_type ())
#define GRAPH_MEDIA_MODELOS_FILTRABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_FILTRABLE, GraphMediaModelosFiltrable))
#define GRAPH_MEDIA_MODELOS_IS_FILTRABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_FILTRABLE))
#define GRAPH_MEDIA_MODELOS_FILTRABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GRAPH_MEDIA_MODELOS_TYPE_FILTRABLE, GraphMediaModelosFiltrableIface))

typedef struct _GraphMediaModelosFiltrable GraphMediaModelosFiltrable;
typedef struct _GraphMediaModelosFiltrableIface GraphMediaModelosFiltrableIface;

#define GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES (graph_media_modelos_albums_imagenes_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenes))
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenesClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES))
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenesClass))

typedef struct _GraphMediaModelosAlbumsImagenes GraphMediaModelosAlbumsImagenes;
typedef struct _GraphMediaModelosAlbumsImagenesClass GraphMediaModelosAlbumsImagenesClass;
typedef struct _GraphMediaModelosAlbumsImagenesPrivate GraphMediaModelosAlbumsImagenesPrivate;
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))
typedef struct _Block7Data Block7Data;
#define __g_list_free__gtk_tree_path_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__gtk_tree_path_free0_ (var), NULL)))
#define _gtk_tree_path_free0(var) ((var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GraphMediaModelosAlbum {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GraphMediaModelosAlbumPrivate * priv;
	gint64 id;
	gchar* nombre;
	gchar* descripcion;
};

struct _GraphMediaModelosAlbumClass {
	GTypeClass parent_class;
	void (*finalize) (GraphMediaModelosAlbum *self);
};

struct _GraphMediaModelosParamSpecAlbum {
	GParamSpec parent_instance;
};

struct _GraphMediaModelosEpoca {
	GDateTime* fecha;
};

struct _GraphMediaModelosAlbumImagenes {
	GraphMediaModelosAlbum parent_instance;
	GraphMediaModelosAlbumImagenesPrivate * priv;
	GraphMediaModelosEpoca epoca;
	GeeArrayList* imagenes;
};

struct _GraphMediaModelosAlbumImagenesClass {
	GraphMediaModelosAlbumClass parent_class;
};

struct _GraphMediaModelosTablas {
	GObject parent_instance;
	GraphMediaModelosTablasPrivate * priv;
	gchar* nombre_tabla;
};

struct _GraphMediaModelosTablasClass {
	GObjectClass parent_class;
};

struct _GraphMediaModelosFiltrableIface {
	GTypeInterface parent_iface;
	GtkIconView* (*filtrar) (GraphMediaModelosFiltrable* self, const gchar* consulta, gint lim);
};

struct _GraphMediaModelosAlbumsImagenes {
	GraphMediaModelosTablas parent_instance;
	GraphMediaModelosAlbumsImagenesPrivate * priv;
};

struct _GraphMediaModelosAlbumsImagenesClass {
	GraphMediaModelosTablasClass parent_class;
};

typedef enum  {
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_ARCHIVO_NO_ENCONTRADO,
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_ARCHIVO_INVALIDO,
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_CONSULTA
} GraphMediaModelosErrorBaseDatos;
#define GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS graph_media_modelos_error_base_datos_quark ()
struct _Block7Data {
	int _ref_count_;
	GraphMediaModelosAlbumsImagenes* self;
	GtkListStore* model;
	GtkIconView* vista;
	GtkTreeIter iter;
};


static gpointer graph_media_modelos_album_parent_class = NULL;
static gpointer graph_media_modelos_album_imagenes_parent_class = NULL;
static gpointer graph_media_modelos_albums_imagenes_parent_class = NULL;
static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_instancia;
static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_instancia = NULL;
extern sqlite3* graph_media_modelos_tablas_bd;
extern gint64 graph_media_modelos_app_gui_index_actual;
static GraphMediaModelosFiltrableIface* graph_media_modelos_albums_imagenes_graph_media_modelos_filtrable_parent_iface = NULL;

gpointer graph_media_modelos_album_ref (gpointer instance);
void graph_media_modelos_album_unref (gpointer instance);
GParamSpec* graph_media_modelos_param_spec_album (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void graph_media_modelos_value_set_album (GValue* value, gpointer v_object);
void graph_media_modelos_value_take_album (GValue* value, gpointer v_object);
gpointer graph_media_modelos_value_get_album (const GValue* value);
GType graph_media_modelos_album_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_ALBUM_DUMMY_PROPERTY
};
GraphMediaModelosAlbum* graph_media_modelos_album_construct (GType object_type);
gboolean graph_media_modelos_album_es_valido (GraphMediaModelosAlbum* self);
GType graph_media_modelos_album_imagenes_get_type (void) G_GNUC_CONST;
GraphMediaModelosAlbumImagenes* graph_media_modelos_album_cast_album_imagenes (GraphMediaModelosAlbum* a);
GraphMediaModelosAlbumImagenes* graph_media_modelos_album_imagenes_new (void);
GraphMediaModelosAlbumImagenes* graph_media_modelos_album_imagenes_construct (GType object_type);
GType graph_media_modelos_album_canciones_get_type (void) G_GNUC_CONST;
GraphMediaModelosAlbumCanciones* graph_media_modelos_album_cast_album_canciones (GraphMediaModelosAlbum* a);
static void graph_media_modelos_album_finalize (GraphMediaModelosAlbum* obj);
GType graph_media_modelos_epoca_get_type (void) G_GNUC_CONST;
GraphMediaModelosEpoca* graph_media_modelos_epoca_dup (const GraphMediaModelosEpoca* self);
void graph_media_modelos_epoca_free (GraphMediaModelosEpoca* self);
void graph_media_modelos_epoca_copy (const GraphMediaModelosEpoca* self, GraphMediaModelosEpoca* dest);
void graph_media_modelos_epoca_destroy (GraphMediaModelosEpoca* self);
gpointer graph_media_modelos_archivo_ref (gpointer instance);
void graph_media_modelos_archivo_unref (gpointer instance);
GParamSpec* graph_media_modelos_param_spec_archivo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void graph_media_modelos_value_set_archivo (GValue* value, gpointer v_object);
void graph_media_modelos_value_take_archivo (GValue* value, gpointer v_object);
gpointer graph_media_modelos_value_get_archivo (const GValue* value);
GType graph_media_modelos_archivo_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_imagen_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_ALBUM_IMAGENES_DUMMY_PROPERTY
};
void graph_media_modelos_epoca_init (GraphMediaModelosEpoca *self, gint dia, gint mes, gint anio);
void graph_media_modelos_album_imagenes_agregar_imagen (GraphMediaModelosAlbumImagenes* self, GraphMediaModelosImagen* i);
gboolean graph_media_modelos_album_imagenes_es_valido (GraphMediaModelosAlbumImagenes* self);
static void graph_media_modelos_album_imagenes_finalize (GraphMediaModelosAlbum* obj);
GType graph_media_modelos_tablas_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_filtrable_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_albums_imagenes_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES_DUMMY_PROPERTY
};
static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_new (void);
static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_construct (GType object_type);
GraphMediaModelosTablas* graph_media_modelos_tablas_construct (GType object_type);
void graph_media_modelos_tablas_set_nombre_tabla (GraphMediaModelosTablas* self, const gchar* nombre_tabla);
GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_get_instancia (void);
GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_agregar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* album);
gchar* graph_media_modelos_epoca_to_string (GraphMediaModelosEpoca *self);
GQuark graph_media_modelos_error_base_datos_quark (void);
GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_eliminar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* p, GError** error);
gboolean graph_media_modelos_tablas_eliminar_celda_por_id (GraphMediaModelosTablas* self, gint64 id);
GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_get_album_por_id (GraphMediaModelosAlbumsImagenes* self, gint64 id);
GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_get_album_id (GraphMediaModelosAlbumsImagenes* self, gint64 id);
GeeArrayList* graph_media_modelos_albums_imagenes_buscar_albums_por_nombre (GraphMediaModelosAlbumsImagenes* self, const gchar* nombre, gint lim);
static GeeArrayList* graph_media_modelos_albums_imagenes_buscar (GraphMediaModelosAlbumsImagenes* self, const gchar* busqueda, gint limite);
GeeArrayList* graph_media_modelos_albums_imagenes_get_albums (GraphMediaModelosAlbumsImagenes* self, const gchar* where, gint limite, const gchar* orden);
gboolean graph_media_modelos_albums_imagenes_editar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* album);
gboolean graph_media_modelos_tablas_existe_id (GraphMediaModelosTablas* self, gint64 id);
void graph_media_modelos_epoca_init_cadena (GraphMediaModelosEpoca *self, const gchar* iso8601);
gint graph_media_modelos_albums_imagenes_get_total_albums (GraphMediaModelosAlbumsImagenes* self);
gint graph_media_modelos_tablas_get_total_celdas (GraphMediaModelosTablas* self, const gchar* columna);
static GtkIconView* graph_media_modelos_albums_imagenes_real_filtrar (GraphMediaModelosFiltrable* base, const gchar* consulta, gint lim);
static Block7Data* block7_data_ref (Block7Data* _data7_);
static void block7_data_unref (void * _userdata_);
GdkPixbuf* graph_media_modelos_filtrable_cargar_icono_ubicacion (GraphMediaModelosFiltrable* self, const gchar* ubicacion, gint h, gint w);
#define GRAPH_MEDIA_MODELOS_APP_GUI_TAM_ICONO 170
static void __lambda8_ (Block7Data* _data7_);
static void _gtk_tree_path_free0_ (gpointer var);
static void _g_list_free__gtk_tree_path_free0_ (GList* self);
static void ___lambda8__gtk_icon_view_selection_changed (GtkIconView* _sender, gpointer self);
static void graph_media_modelos_albums_imagenes_finalize (GObject* obj);


GraphMediaModelosAlbum* graph_media_modelos_album_construct (GType object_type) {
	GraphMediaModelosAlbum* self = NULL;
	gchar* _tmp0_ = NULL;
	self = (GraphMediaModelosAlbum*) g_type_create_instance (object_type);
	self->id = (gint64) (-1);
	_tmp0_ = g_strdup ("Sin descripcion");
	_g_free0 (self->descripcion);
	self->descripcion = _tmp0_;
	return self;
}


gboolean graph_media_modelos_album_es_valido (GraphMediaModelosAlbum* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp1_ = self->nombre;
	if (_tmp1_ != NULL) {
		const gchar* _tmp2_ = NULL;
		_tmp2_ = self->nombre;
		_tmp0_ = g_strcmp0 (_tmp2_, "") != 0;
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	return result;
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_album_cast_album_imagenes (GraphMediaModelosAlbum* a) {
	GraphMediaModelosAlbumImagenes* result = NULL;
	GraphMediaModelosAlbumImagenes* ai = NULL;
	GraphMediaModelosAlbumImagenes* _tmp0_ = NULL;
	GraphMediaModelosAlbum* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	GraphMediaModelosAlbum* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GraphMediaModelosAlbum* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	g_return_val_if_fail (a != NULL, NULL);
	_tmp0_ = graph_media_modelos_album_imagenes_new ();
	ai = _tmp0_;
	_tmp1_ = a;
	_tmp2_ = _tmp1_->id;
	((GraphMediaModelosAlbum*) ai)->id = _tmp2_;
	_tmp3_ = a;
	_tmp4_ = _tmp3_->nombre;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 (((GraphMediaModelosAlbum*) ai)->nombre);
	((GraphMediaModelosAlbum*) ai)->nombre = _tmp5_;
	_tmp6_ = a;
	_tmp7_ = _tmp6_->descripcion;
	_tmp8_ = g_strdup (_tmp7_);
	_g_free0 (((GraphMediaModelosAlbum*) ai)->descripcion);
	((GraphMediaModelosAlbum*) ai)->descripcion = _tmp8_;
	result = ai;
	return result;
}


static gpointer _graph_media_modelos_album_ref0 (gpointer self) {
	return self ? graph_media_modelos_album_ref (self) : NULL;
}


GraphMediaModelosAlbumCanciones* graph_media_modelos_album_cast_album_canciones (GraphMediaModelosAlbum* a) {
	GraphMediaModelosAlbumCanciones* result = NULL;
	GraphMediaModelosAlbumCanciones* ai = NULL;
	GraphMediaModelosAlbum* _tmp0_ = NULL;
	GraphMediaModelosAlbumCanciones* _tmp1_ = NULL;
	g_return_val_if_fail (a != NULL, NULL);
	_tmp0_ = a;
	_tmp1_ = _graph_media_modelos_album_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GRAPH_MEDIA_MODELOS_TYPE_ALBUM_CANCIONES, GraphMediaModelosAlbumCanciones));
	ai = _tmp1_;
	result = ai;
	return result;
}


static void graph_media_modelos_value_album_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void graph_media_modelos_value_album_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		graph_media_modelos_album_unref (value->data[0].v_pointer);
	}
}


static void graph_media_modelos_value_album_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = graph_media_modelos_album_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer graph_media_modelos_value_album_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* graph_media_modelos_value_album_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GraphMediaModelosAlbum* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = graph_media_modelos_album_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* graph_media_modelos_value_album_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GraphMediaModelosAlbum** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = graph_media_modelos_album_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* graph_media_modelos_param_spec_album (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GraphMediaModelosParamSpecAlbum* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GRAPH_MEDIA_MODELOS_TYPE_ALBUM), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer graph_media_modelos_value_get_album (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_ALBUM), NULL);
	return value->data[0].v_pointer;
}


void graph_media_modelos_value_set_album (GValue* value, gpointer v_object) {
	GraphMediaModelosAlbum* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_ALBUM));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_MODELOS_TYPE_ALBUM));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		graph_media_modelos_album_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_modelos_album_unref (old);
	}
}


void graph_media_modelos_value_take_album (GValue* value, gpointer v_object) {
	GraphMediaModelosAlbum* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_ALBUM));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_MODELOS_TYPE_ALBUM));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_modelos_album_unref (old);
	}
}


static void graph_media_modelos_album_class_init (GraphMediaModelosAlbumClass * klass) {
	graph_media_modelos_album_parent_class = g_type_class_peek_parent (klass);
	((GraphMediaModelosAlbumClass *) klass)->finalize = graph_media_modelos_album_finalize;
}


static void graph_media_modelos_album_instance_init (GraphMediaModelosAlbum * self) {
	self->ref_count = 1;
}


static void graph_media_modelos_album_finalize (GraphMediaModelosAlbum* obj) {
	GraphMediaModelosAlbum * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_ALBUM, GraphMediaModelosAlbum);
	g_signal_handlers_destroy (self);
	_g_free0 (self->nombre);
	_g_free0 (self->descripcion);
}


/**
 * Clase que almacena las propiedades de un album o carpeta que se
 * usara para modelar un album de canciones o de fotografias
 */
GType graph_media_modelos_album_get_type (void) {
	static volatile gsize graph_media_modelos_album_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_album_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { graph_media_modelos_value_album_init, graph_media_modelos_value_album_free_value, graph_media_modelos_value_album_copy_value, graph_media_modelos_value_album_peek_pointer, "p", graph_media_modelos_value_album_collect_value, "p", graph_media_modelos_value_album_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosAlbumClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_album_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosAlbum), 0, (GInstanceInitFunc) graph_media_modelos_album_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType graph_media_modelos_album_type_id;
		graph_media_modelos_album_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GraphMediaModelosAlbum", &g_define_type_info, &g_define_type_fundamental_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&graph_media_modelos_album_type_id__volatile, graph_media_modelos_album_type_id);
	}
	return graph_media_modelos_album_type_id__volatile;
}


gpointer graph_media_modelos_album_ref (gpointer instance) {
	GraphMediaModelosAlbum* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void graph_media_modelos_album_unref (gpointer instance) {
	GraphMediaModelosAlbum* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GRAPH_MEDIA_MODELOS_ALBUM_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_album_imagenes_construct (GType object_type) {
	GraphMediaModelosAlbumImagenes* self = NULL;
	gchar* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self = (GraphMediaModelosAlbumImagenes*) graph_media_modelos_album_construct (object_type);
	_tmp0_ = g_strdup ("sin nombre");
	_g_free0 (((GraphMediaModelosAlbum*) self)->nombre);
	((GraphMediaModelosAlbum*) self)->nombre = _tmp0_;
	((GraphMediaModelosAlbum*) self)->id = (gint64) (-1);
	graph_media_modelos_epoca_destroy (&self->epoca);
	graph_media_modelos_epoca_init (&self->epoca, 1, 1, 2000);
	_tmp1_ = gee_array_list_new (GRAPH_MEDIA_MODELOS_TYPE_IMAGEN, (GBoxedCopyFunc) graph_media_modelos_archivo_ref, graph_media_modelos_archivo_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->imagenes);
	self->imagenes = _tmp1_;
	return self;
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_album_imagenes_new (void) {
	return graph_media_modelos_album_imagenes_construct (GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES);
}


void graph_media_modelos_album_imagenes_agregar_imagen (GraphMediaModelosAlbumImagenes* self, GraphMediaModelosImagen* i) {
	GeeArrayList* _tmp0_ = NULL;
	GraphMediaModelosImagen* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (i != NULL);
	_tmp0_ = self->imagenes;
	_tmp1_ = i;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp1_);
}


gboolean graph_media_modelos_album_imagenes_es_valido (GraphMediaModelosAlbumImagenes* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp1_ = ((GraphMediaModelosAlbum*) self)->nombre;
	if (_tmp1_ != NULL) {
		const gchar* _tmp2_ = NULL;
		_tmp2_ = ((GraphMediaModelosAlbum*) self)->nombre;
		_tmp0_ = g_strcmp0 (_tmp2_, "") != 0;
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	return result;
}


static void graph_media_modelos_album_imagenes_class_init (GraphMediaModelosAlbumImagenesClass * klass) {
	graph_media_modelos_album_imagenes_parent_class = g_type_class_peek_parent (klass);
	((GraphMediaModelosAlbumClass *) klass)->finalize = graph_media_modelos_album_imagenes_finalize;
}


static void graph_media_modelos_album_imagenes_instance_init (GraphMediaModelosAlbumImagenes * self) {
}


static void graph_media_modelos_album_imagenes_finalize (GraphMediaModelosAlbum* obj) {
	GraphMediaModelosAlbumImagenes * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, GraphMediaModelosAlbumImagenes);
	graph_media_modelos_epoca_destroy (&self->epoca);
	_g_object_unref0 (self->imagenes);
	GRAPH_MEDIA_MODELOS_ALBUM_CLASS (graph_media_modelos_album_imagenes_parent_class)->finalize (obj);
}


GType graph_media_modelos_album_imagenes_get_type (void) {
	static volatile gsize graph_media_modelos_album_imagenes_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_album_imagenes_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosAlbumImagenesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_album_imagenes_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosAlbumImagenes), 0, (GInstanceInitFunc) graph_media_modelos_album_imagenes_instance_init, NULL };
		GType graph_media_modelos_album_imagenes_type_id;
		graph_media_modelos_album_imagenes_type_id = g_type_register_static (GRAPH_MEDIA_MODELOS_TYPE_ALBUM, "GraphMediaModelosAlbumImagenes", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_modelos_album_imagenes_type_id__volatile, graph_media_modelos_album_imagenes_type_id);
	}
	return graph_media_modelos_album_imagenes_type_id__volatile;
}


static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_construct (GType object_type) {
	GraphMediaModelosAlbumsImagenes * self = NULL;
	self = (GraphMediaModelosAlbumsImagenes*) graph_media_modelos_tablas_construct (object_type);
	graph_media_modelos_tablas_set_nombre_tabla ((GraphMediaModelosTablas*) self, "album_imagenes");
	return self;
}


static GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_new (void) {
	return graph_media_modelos_albums_imagenes_construct (GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_get_instancia (void) {
	GraphMediaModelosAlbumsImagenes* result = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp0_ = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp2_ = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp3_ = NULL;
	_tmp0_ = graph_media_modelos_albums_imagenes_instancia;
	if (_tmp0_ == NULL) {
		GraphMediaModelosAlbumsImagenes* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_albums_imagenes_new ();
		_g_object_unref0 (graph_media_modelos_albums_imagenes_instancia);
		graph_media_modelos_albums_imagenes_instancia = _tmp1_;
	}
	_tmp2_ = graph_media_modelos_albums_imagenes_instancia;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


/**
* Agrega una album nueva a la base de datos 
*/
GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_agregar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* album) {
	GraphMediaModelosAlbumImagenes* result = NULL;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gint res = 0;
	sqlite3* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	sqlite3_stmt* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	FILE* _tmp10_ = NULL;
	sqlite3_stmt* _tmp11_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GDestroyNotify _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	FILE* _tmp18_ = NULL;
	sqlite3_stmt* _tmp19_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	GDestroyNotify _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	FILE* _tmp26_ = NULL;
	sqlite3_stmt* _tmp27_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	GDestroyNotify _tmp30_ = NULL;
	gint _tmp31_ = 0;
	gint _tmp32_ = 0;
	FILE* _tmp33_ = NULL;
	sqlite3_stmt* _tmp34_ = NULL;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
	GraphMediaModelosAlbumImagenes* _tmp37_ = NULL;
	sqlite3* _tmp38_ = NULL;
	gint64 _tmp39_ = 0LL;
	GraphMediaModelosAlbumImagenes* _tmp40_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp41_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (album != NULL, NULL);
	_tmp0_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp1_ = g_strdup_printf ("INSERT INTO %s (nombre, descripcion, fecha)", _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, " VALUES (?, ?, ?)", NULL);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	sql = _tmp4_;
	_tmp5_ = graph_media_modelos_tablas_bd;
	_tmp6_ = sql;
	_tmp8_ = sqlite3_prepare_v2 (_tmp5_, _tmp6_, -1, &_tmp7_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp7_;
	res = _tmp8_;
	_tmp9_ = res;
	_vala_assert (_tmp9_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp10_ = stdout;
	fprintf (_tmp10_, "0");
	_tmp11_ = query;
	_tmp12_ = album;
	_tmp13_ = ((GraphMediaModelosAlbum*) _tmp12_)->nombre;
	_tmp14_ = g_strdup (_tmp13_);
	_tmp15_ = g_free;
	_tmp16_ = sqlite3_bind_text (_tmp11_, 1, _tmp14_, -1, _tmp15_);
	res = _tmp16_;
	_tmp17_ = res;
	_vala_assert (_tmp17_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp18_ = stdout;
	fprintf (_tmp18_, "1");
	_tmp19_ = query;
	_tmp20_ = album;
	_tmp21_ = ((GraphMediaModelosAlbum*) _tmp20_)->descripcion;
	_tmp22_ = g_strdup (_tmp21_);
	_tmp23_ = g_free;
	_tmp24_ = sqlite3_bind_text (_tmp19_, 2, _tmp22_, -1, _tmp23_);
	res = _tmp24_;
	_tmp25_ = res;
	_vala_assert (_tmp25_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp26_ = stdout;
	fprintf (_tmp26_, "2");
	_tmp27_ = query;
	_tmp28_ = album;
	_tmp29_ = graph_media_modelos_epoca_to_string (&_tmp28_->epoca);
	_tmp30_ = g_free;
	_tmp31_ = sqlite3_bind_text (_tmp27_, 3, _tmp29_, -1, _tmp30_);
	res = _tmp31_;
	_tmp32_ = res;
	_vala_assert (_tmp32_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp33_ = stdout;
	fprintf (_tmp33_, "3");
	_tmp34_ = query;
	_tmp35_ = sqlite3_step (_tmp34_);
	res = _tmp35_;
	_tmp36_ = res;
	if (_tmp36_ != SQLITE_DONE) {
		result = NULL;
		_g_free0 (sql);
		_sqlite3_finalize0 (query);
		return result;
	}
	_tmp37_ = album;
	_tmp38_ = graph_media_modelos_tablas_bd;
	_tmp39_ = sqlite3_last_insert_rowid (_tmp38_);
	((GraphMediaModelosAlbum*) _tmp37_)->id = _tmp39_;
	_tmp40_ = album;
	_tmp41_ = _graph_media_modelos_album_ref0 (_tmp40_);
	result = _tmp41_;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_eliminar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* p, GError** error) {
	GraphMediaModelosAlbumImagenes* result = NULL;
	GraphMediaModelosAlbumImagenes* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	GraphMediaModelosAlbumImagenes* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	gboolean _tmp4_ = FALSE;
	GraphMediaModelosAlbumImagenes* _tmp11_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp12_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp13_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = p;
	_tmp1_ = ((GraphMediaModelosAlbum*) _tmp0_)->id;
	_vala_assert (_tmp1_ != ((gint64) (-1)), "p.id != -1");
	_tmp2_ = p;
	_tmp3_ = ((GraphMediaModelosAlbum*) _tmp2_)->id;
	_tmp4_ = graph_media_modelos_tablas_eliminar_celda_por_id ((GraphMediaModelosTablas*) self, _tmp3_);
	if (!_tmp4_) {
		GraphMediaModelosAlbumImagenes* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		GError* _tmp10_ = NULL;
		_tmp5_ = p;
		_tmp6_ = ((GraphMediaModelosAlbum*) _tmp5_)->nombre;
		_tmp7_ = g_strdup_printf ("No se pudo eliminar a %s", _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_error_new_literal (GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS, GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_CONSULTA, _tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		_inner_error_ = _tmp10_;
		if (_inner_error_->domain == GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp11_ = p;
	((GraphMediaModelosAlbum*) _tmp11_)->id = (gint64) (-1);
	_tmp12_ = p;
	_tmp13_ = _graph_media_modelos_album_ref0 (_tmp12_);
	result = _tmp13_;
	return result;
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_get_album_por_id (GraphMediaModelosAlbumsImagenes* self, gint64 id) {
	GraphMediaModelosAlbumImagenes* result = NULL;
	gint64 _tmp0_ = 0LL;
	GraphMediaModelosAlbumImagenes* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = id;
	_tmp1_ = graph_media_modelos_albums_imagenes_get_album_id (self, _tmp0_);
	result = _tmp1_;
	return result;
}


GeeArrayList* graph_media_modelos_albums_imagenes_buscar_albums_por_nombre (GraphMediaModelosAlbumsImagenes* self, const gchar* nombre, gint lim) {
	GeeArrayList* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GeeArrayList* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (nombre != NULL, NULL);
	_tmp0_ = nombre;
	_tmp1_ = lim;
	_tmp2_ = graph_media_modelos_albums_imagenes_buscar (self, _tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


static GeeArrayList* graph_media_modelos_albums_imagenes_buscar (GraphMediaModelosAlbumsImagenes* self, const gchar* busqueda, gint limite) {
	GeeArrayList* result = NULL;
	GeeArrayList* resultados = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GeeArrayList* _tmp6_ = NULL;
	GeeArrayList* _tmp7_ = NULL;
	GeeArrayList* albums = NULL;
	GeeArrayList* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (busqueda != NULL, NULL);
	_tmp0_ = busqueda;
	_tmp1_ = g_strconcat ("nombre LIKE '%", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, "%'", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = limite;
	_tmp6_ = graph_media_modelos_albums_imagenes_get_albums (self, _tmp4_, _tmp5_, "fecha");
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	resultados = _tmp7_;
	_tmp8_ = gee_array_list_new (GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, (GBoxedCopyFunc) graph_media_modelos_album_ref, graph_media_modelos_album_unref, NULL, NULL, NULL);
	albums = _tmp8_;
	{
		GeeArrayList* _a_list = NULL;
		GeeArrayList* _tmp9_ = NULL;
		GeeArrayList* _tmp10_ = NULL;
		gint _a_size = 0;
		GeeArrayList* _tmp11_ = NULL;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		gint _a_index = 0;
		_tmp9_ = resultados;
		_tmp10_ = _g_object_ref0 (_tmp9_);
		_a_list = _tmp10_;
		_tmp11_ = _a_list;
		_tmp12_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp11_);
		_tmp13_ = _tmp12_;
		_a_size = _tmp13_;
		_a_index = -1;
		while (TRUE) {
			gint _tmp14_ = 0;
			gint _tmp15_ = 0;
			gint _tmp16_ = 0;
			GraphMediaModelosAlbum* a = NULL;
			GeeArrayList* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			gpointer _tmp19_ = NULL;
			GeeArrayList* _tmp20_ = NULL;
			GraphMediaModelosAlbum* _tmp21_ = NULL;
			GraphMediaModelosAlbumImagenes* _tmp22_ = NULL;
			GraphMediaModelosAlbumImagenes* _tmp23_ = NULL;
			_tmp14_ = _a_index;
			_a_index = _tmp14_ + 1;
			_tmp15_ = _a_index;
			_tmp16_ = _a_size;
			if (!(_tmp15_ < _tmp16_)) {
				break;
			}
			_tmp17_ = _a_list;
			_tmp18_ = _a_index;
			_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
			a = (GraphMediaModelosAlbum*) _tmp19_;
			_tmp20_ = albums;
			_tmp21_ = a;
			_tmp22_ = graph_media_modelos_album_cast_album_imagenes (_tmp21_);
			_tmp23_ = _tmp22_;
			gee_abstract_collection_add ((GeeAbstractCollection*) _tmp20_, _tmp23_);
			_graph_media_modelos_album_unref0 (_tmp23_);
			_graph_media_modelos_album_unref0 (a);
		}
		_g_object_unref0 (_a_list);
	}
	result = albums;
	_g_object_unref0 (resultados);
	return result;
}


gboolean graph_media_modelos_albums_imagenes_editar (GraphMediaModelosAlbumsImagenes* self, GraphMediaModelosAlbumImagenes* album) {
	gboolean result = FALSE;
	GraphMediaModelosAlbumImagenes* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gchar* columnas = NULL;
	gchar* _tmp2_ = NULL;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gint res = 0;
	sqlite3* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	sqlite3_stmt* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	sqlite3_stmt* _tmp11_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GDestroyNotify _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	sqlite3_stmt* _tmp18_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	GDestroyNotify _tmp22_ = NULL;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	sqlite3_stmt* _tmp25_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	GDestroyNotify _tmp28_ = NULL;
	gint _tmp29_ = 0;
	gint _tmp30_ = 0;
	sqlite3_stmt* _tmp31_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp32_ = NULL;
	gint64 _tmp33_ = 0LL;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	sqlite3_stmt* _tmp36_ = NULL;
	gint _tmp37_ = 0;
	gint _tmp38_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (album != NULL, FALSE);
	_tmp0_ = album;
	_tmp1_ = graph_media_modelos_album_imagenes_es_valido (_tmp0_);
	if (!_tmp1_) {
		result = FALSE;
		return result;
	}
	_tmp2_ = g_strdup ("nombre=?, descripcion=?, fecha=?");
	columnas = _tmp2_;
	_tmp3_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp4_ = columnas;
	_tmp5_ = g_strdup_printf ("UPDATE %s SET %s WHERE id=?", _tmp3_, _tmp4_);
	sql = _tmp5_;
	_tmp6_ = graph_media_modelos_tablas_bd;
	_tmp7_ = sql;
	_tmp9_ = sqlite3_prepare_v2 (_tmp6_, _tmp7_, -1, &_tmp8_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp8_;
	res = _tmp9_;
	_tmp10_ = res;
	_vala_assert (_tmp10_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp11_ = query;
	_tmp12_ = album;
	_tmp13_ = ((GraphMediaModelosAlbum*) _tmp12_)->nombre;
	_tmp14_ = g_strdup (_tmp13_);
	_tmp15_ = g_free;
	_tmp16_ = sqlite3_bind_text (_tmp11_, 1, _tmp14_, -1, _tmp15_);
	res = _tmp16_;
	_tmp17_ = res;
	_vala_assert (_tmp17_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp18_ = query;
	_tmp19_ = album;
	_tmp20_ = ((GraphMediaModelosAlbum*) _tmp19_)->descripcion;
	_tmp21_ = g_strdup (_tmp20_);
	_tmp22_ = g_free;
	_tmp23_ = sqlite3_bind_text (_tmp18_, 2, _tmp21_, -1, _tmp22_);
	res = _tmp23_;
	_tmp24_ = res;
	_vala_assert (_tmp24_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp25_ = query;
	_tmp26_ = album;
	_tmp27_ = graph_media_modelos_epoca_to_string (&_tmp26_->epoca);
	_tmp28_ = g_free;
	_tmp29_ = sqlite3_bind_text (_tmp25_, 3, _tmp27_, -1, _tmp28_);
	res = _tmp29_;
	_tmp30_ = res;
	_vala_assert (_tmp30_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp31_ = query;
	_tmp32_ = album;
	_tmp33_ = ((GraphMediaModelosAlbum*) _tmp32_)->id;
	_tmp34_ = sqlite3_bind_int64 (_tmp31_, 4, _tmp33_);
	res = _tmp34_;
	_tmp35_ = res;
	_vala_assert (_tmp35_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp36_ = query;
	_tmp37_ = sqlite3_step (_tmp36_);
	res = _tmp37_;
	_tmp38_ = res;
	result = _tmp38_ == SQLITE_DONE;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	_g_free0 (columnas);
	return result;
}


GraphMediaModelosAlbumImagenes* graph_media_modelos_albums_imagenes_get_album_id (GraphMediaModelosAlbumsImagenes* self, gint64 id) {
	GraphMediaModelosAlbumImagenes* result = NULL;
	sqlite3_stmt* query = NULL;
	gint64 _tmp0_ = 0LL;
	gboolean _tmp1_ = FALSE;
	gchar* sql = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gint res = 0;
	sqlite3* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	sqlite3_stmt* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	sqlite3_stmt* _tmp9_ = NULL;
	gint64 _tmp10_ = 0LL;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	sqlite3_stmt* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	GraphMediaModelosAlbumImagenes* celda = NULL;
	GraphMediaModelosAlbumImagenes* _tmp16_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp17_ = NULL;
	sqlite3_stmt* _tmp18_ = NULL;
	gint64 _tmp19_ = 0LL;
	GraphMediaModelosAlbumImagenes* _tmp20_ = NULL;
	sqlite3_stmt* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp24_ = NULL;
	sqlite3_stmt* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	GraphMediaModelosAlbumImagenes* _tmp28_ = NULL;
	sqlite3_stmt* _tmp29_ = NULL;
	const gchar* _tmp30_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = id;
	_tmp1_ = graph_media_modelos_tablas_existe_id ((GraphMediaModelosTablas*) self, _tmp0_);
	if (!_tmp1_) {
		result = NULL;
		_sqlite3_finalize0 (query);
		return result;
	}
	_tmp2_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp3_ = g_strdup_printf ("SELECT %s FROM %s WHERE id=?", "*", _tmp2_);
	sql = _tmp3_;
	_tmp4_ = graph_media_modelos_tablas_bd;
	_tmp5_ = sql;
	_tmp7_ = sqlite3_prepare_v2 (_tmp4_, _tmp5_, -1, &_tmp6_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp6_;
	res = _tmp7_;
	_tmp8_ = res;
	_vala_assert (_tmp8_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp9_ = query;
	_tmp10_ = id;
	_tmp11_ = sqlite3_bind_int64 (_tmp9_, 1, _tmp10_);
	res = _tmp11_;
	_tmp12_ = res;
	_vala_assert (_tmp12_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp13_ = query;
	_tmp14_ = sqlite3_step (_tmp13_);
	res = _tmp14_;
	_tmp15_ = res;
	_vala_assert (_tmp15_ == SQLITE_ROW, "res == Sqlite.ROW");
	_tmp16_ = graph_media_modelos_album_imagenes_new ();
	celda = _tmp16_;
	_tmp17_ = celda;
	_tmp18_ = query;
	_tmp19_ = sqlite3_column_int64 (_tmp18_, 0);
	((GraphMediaModelosAlbum*) _tmp17_)->id = _tmp19_;
	_tmp20_ = celda;
	_tmp21_ = query;
	_tmp22_ = sqlite3_column_text (_tmp21_, 1);
	_tmp23_ = g_strdup (_tmp22_);
	_g_free0 (((GraphMediaModelosAlbum*) _tmp20_)->nombre);
	((GraphMediaModelosAlbum*) _tmp20_)->nombre = _tmp23_;
	_tmp24_ = celda;
	_tmp25_ = query;
	_tmp26_ = sqlite3_column_text (_tmp25_, 2);
	_tmp27_ = g_strdup (_tmp26_);
	_g_free0 (((GraphMediaModelosAlbum*) _tmp24_)->descripcion);
	((GraphMediaModelosAlbum*) _tmp24_)->descripcion = _tmp27_;
	_tmp28_ = celda;
	_tmp29_ = query;
	_tmp30_ = sqlite3_column_text (_tmp29_, 3);
	graph_media_modelos_epoca_destroy (&_tmp28_->epoca);
	graph_media_modelos_epoca_init_cadena (&_tmp28_->epoca, _tmp30_);
	result = celda;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


gint graph_media_modelos_albums_imagenes_get_total_albums (GraphMediaModelosAlbumsImagenes* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = graph_media_modelos_tablas_get_total_celdas ((GraphMediaModelosTablas*) self, "1");
	result = _tmp0_;
	return result;
}


GeeArrayList* graph_media_modelos_albums_imagenes_get_albums (GraphMediaModelosAlbumsImagenes* self, const gchar* where, gint limite, const gchar* orden) {
	GeeArrayList* result = NULL;
	gint _tmp0_ = 0;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gint res = 0;
	sqlite3* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	sqlite3_stmt* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	GeeArrayList* albums = NULL;
	GeeArrayList* _tmp13_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (where != NULL, NULL);
	g_return_val_if_fail (orden != NULL, NULL);
	_tmp0_ = limite;
	_vala_assert (_tmp0_ >= 0, "limite >= 0");
	_tmp1_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp2_ = where;
	_tmp3_ = orden;
	_tmp4_ = g_strdup_printf (" FROM %s WHERE %s ORDER BY %s DESC", _tmp1_, _tmp2_, _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat ("SELECT id, nombre, descripcion, fecha", _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	sql = _tmp7_;
	_tmp8_ = graph_media_modelos_tablas_bd;
	_tmp9_ = sql;
	_tmp11_ = sqlite3_prepare_v2 (_tmp8_, _tmp9_, -1, &_tmp10_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp10_;
	res = _tmp11_;
	_tmp12_ = res;
	_vala_assert (_tmp12_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp13_ = gee_array_list_new (GRAPH_MEDIA_MODELOS_TYPE_ALBUM_IMAGENES, (GBoxedCopyFunc) graph_media_modelos_album_ref, graph_media_modelos_album_unref, NULL, NULL, NULL);
	albums = _tmp13_;
	while (TRUE) {
		sqlite3_stmt* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
		gboolean _tmp17_ = FALSE;
		gint _tmp18_ = 0;
		GraphMediaModelosAlbumImagenes* celda = NULL;
		GraphMediaModelosAlbumImagenes* _tmp23_ = NULL;
		GraphMediaModelosAlbumImagenes* _tmp24_ = NULL;
		sqlite3_stmt* _tmp25_ = NULL;
		gint64 _tmp26_ = 0LL;
		GraphMediaModelosAlbumImagenes* _tmp27_ = NULL;
		sqlite3_stmt* _tmp28_ = NULL;
		const gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		GraphMediaModelosAlbumImagenes* _tmp31_ = NULL;
		sqlite3_stmt* _tmp32_ = NULL;
		const gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		GraphMediaModelosAlbumImagenes* _tmp35_ = NULL;
		sqlite3_stmt* _tmp36_ = NULL;
		const gchar* _tmp37_ = NULL;
		GeeArrayList* _tmp38_ = NULL;
		GraphMediaModelosAlbumImagenes* _tmp39_ = NULL;
		_tmp14_ = query;
		_tmp15_ = sqlite3_step (_tmp14_);
		res = _tmp15_;
		_tmp16_ = res;
		if (!(_tmp16_ == SQLITE_ROW)) {
			break;
		}
		_tmp18_ = limite;
		if (_tmp18_ != 0) {
			GeeArrayList* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			gint _tmp22_ = 0;
			_tmp19_ = albums;
			_tmp20_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp19_);
			_tmp21_ = _tmp20_;
			_tmp22_ = limite;
			_tmp17_ = _tmp21_ == _tmp22_;
		} else {
			_tmp17_ = FALSE;
		}
		if (_tmp17_) {
			break;
		}
		_tmp23_ = graph_media_modelos_album_imagenes_new ();
		celda = _tmp23_;
		_tmp24_ = celda;
		_tmp25_ = query;
		_tmp26_ = sqlite3_column_int64 (_tmp25_, 0);
		((GraphMediaModelosAlbum*) _tmp24_)->id = _tmp26_;
		_tmp27_ = celda;
		_tmp28_ = query;
		_tmp29_ = sqlite3_column_text (_tmp28_, 1);
		_tmp30_ = g_strdup (_tmp29_);
		_g_free0 (((GraphMediaModelosAlbum*) _tmp27_)->nombre);
		((GraphMediaModelosAlbum*) _tmp27_)->nombre = _tmp30_;
		_tmp31_ = celda;
		_tmp32_ = query;
		_tmp33_ = sqlite3_column_text (_tmp32_, 2);
		_tmp34_ = g_strdup (_tmp33_);
		_g_free0 (((GraphMediaModelosAlbum*) _tmp31_)->descripcion);
		((GraphMediaModelosAlbum*) _tmp31_)->descripcion = _tmp34_;
		_tmp35_ = celda;
		_tmp36_ = query;
		_tmp37_ = sqlite3_column_text (_tmp36_, 3);
		graph_media_modelos_epoca_destroy (&_tmp35_->epoca);
		graph_media_modelos_epoca_init_cadena (&_tmp35_->epoca, _tmp37_);
		_tmp38_ = albums;
		_tmp39_ = celda;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp38_, _tmp39_);
		_graph_media_modelos_album_unref0 (celda);
	}
	result = albums;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


static Block7Data* block7_data_ref (Block7Data* _data7_) {
	g_atomic_int_inc (&_data7_->_ref_count_);
	return _data7_;
}


static void block7_data_unref (void * _userdata_) {
	Block7Data* _data7_;
	_data7_ = (Block7Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data7_->_ref_count_)) {
		GraphMediaModelosAlbumsImagenes* self;
		self = _data7_->self;
		_g_object_unref0 (_data7_->vista);
		_g_object_unref0 (_data7_->model);
		_g_object_unref0 (self);
		g_slice_free (Block7Data, _data7_);
	}
}


static void _gtk_tree_path_free0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL));
}


static void _g_list_free__gtk_tree_path_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _gtk_tree_path_free0_, NULL);
	g_list_free (self);
}


static gpointer _gtk_tree_path_copy0 (gpointer self) {
	return self ? gtk_tree_path_copy (self) : NULL;
}


static void __lambda8_ (Block7Data* _data7_) {
	GraphMediaModelosAlbumsImagenes* self;
	GList* paths = NULL;
	GtkIconView* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	GtkTreePath* path = NULL;
	GList* _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	GtkTreePath* _tmp5_ = NULL;
	GValue title = {0};
	GValue icon = {0};
	GValue index = {0};
	gboolean tmp = FALSE;
	GtkListStore* _tmp6_ = NULL;
	GtkTreePath* _tmp7_ = NULL;
	GtkTreeIter _tmp8_ = {0};
	gboolean _tmp9_ = FALSE;
	gboolean _tmp10_ = FALSE;
	GtkListStore* _tmp11_ = NULL;
	GtkTreeIter _tmp12_ = {0};
	GValue _tmp13_ = {0};
	GtkListStore* _tmp14_ = NULL;
	GtkTreeIter _tmp15_ = {0};
	GValue _tmp16_ = {0};
	GtkListStore* _tmp17_ = NULL;
	GtkTreeIter _tmp18_ = {0};
	GValue _tmp19_ = {0};
	GValue _tmp20_ = {0};
	GValue _tmp21_ = {0};
	GValue _tmp22_ = {0};
	GValue _tmp23_ = {0};
	self = _data7_->self;
	_tmp0_ = _data7_->vista;
	_tmp1_ = gtk_icon_view_get_selected_items (_tmp0_);
	paths = _tmp1_;
	_tmp2_ = paths;
	if (_tmp2_ == NULL) {
		__g_list_free__gtk_tree_path_free0_0 (paths);
		return;
	}
	_tmp3_ = paths;
	_tmp4_ = g_list_nth_data (_tmp3_, (guint) 0);
	_tmp5_ = _gtk_tree_path_copy0 ((GtkTreePath*) _tmp4_);
	path = _tmp5_;
	_tmp6_ = _data7_->model;
	_tmp7_ = path;
	_tmp9_ = gtk_tree_model_get_iter ((GtkTreeModel*) _tmp6_, &_tmp8_, _tmp7_);
	_data7_->iter = _tmp8_;
	tmp = _tmp9_;
	_tmp10_ = tmp;
	_vala_assert (_tmp10_ == TRUE, "tmp == true");
	_tmp11_ = _data7_->model;
	_tmp12_ = _data7_->iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp11_, &_tmp12_, 0, &_tmp13_);
	G_IS_VALUE (&icon) ? (g_value_unset (&icon), NULL) : NULL;
	icon = _tmp13_;
	_tmp14_ = _data7_->model;
	_tmp15_ = _data7_->iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp14_, &_tmp15_, 1, &_tmp16_);
	G_IS_VALUE (&title) ? (g_value_unset (&title), NULL) : NULL;
	title = _tmp16_;
	_tmp17_ = _data7_->model;
	_tmp18_ = _data7_->iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp17_, &_tmp18_, 2, &_tmp19_);
	G_IS_VALUE (&index) ? (g_value_unset (&index), NULL) : NULL;
	index = _tmp19_;
	_tmp20_ = index;
	graph_media_modelos_app_gui_index_actual = g_value_get_int64 (&_tmp20_);
	_tmp21_ = title;
	_tmp22_ = icon;
	_tmp23_ = index;
	g_warning ("album.vala:266: %s: %p - %lld \n", g_value_get_string (&_tmp21_), g_value_get_object (&_tmp22_), g_value_get_int64 (&_tmp23_));
	G_IS_VALUE (&index) ? (g_value_unset (&index), NULL) : NULL;
	G_IS_VALUE (&icon) ? (g_value_unset (&icon), NULL) : NULL;
	G_IS_VALUE (&title) ? (g_value_unset (&title), NULL) : NULL;
	_gtk_tree_path_free0 (path);
	__g_list_free__gtk_tree_path_free0_0 (paths);
}


static void ___lambda8__gtk_icon_view_selection_changed (GtkIconView* _sender, gpointer self) {
	__lambda8_ (self);
}


static GtkIconView* graph_media_modelos_albums_imagenes_real_filtrar (GraphMediaModelosFiltrable* base, const gchar* consulta, gint lim) {
	GraphMediaModelosAlbumsImagenes * self;
	GtkIconView* result = NULL;
	Block7Data* _data7_;
	GeeArrayList* albums = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GeeArrayList* _tmp2_ = NULL;
	GtkListStore* _tmp3_ = NULL;
	GtkListStore* _tmp4_ = NULL;
	GtkIconView* _tmp5_ = NULL;
	GtkIconView* _tmp6_ = NULL;
	GtkIconView* _tmp7_ = NULL;
	GtkIconView* _tmp8_ = NULL;
	GtkIconView* _tmp30_ = NULL;
	GtkIconView* _tmp31_ = NULL;
	GtkIconView* _tmp32_ = NULL;
	self = (GraphMediaModelosAlbumsImagenes*) base;
	g_return_val_if_fail (consulta != NULL, NULL);
	_data7_ = g_slice_new0 (Block7Data);
	_data7_->_ref_count_ = 1;
	_data7_->self = g_object_ref (self);
	_tmp0_ = consulta;
	_tmp1_ = lim;
	_tmp2_ = graph_media_modelos_albums_imagenes_buscar_albums_por_nombre (self, _tmp0_, _tmp1_);
	albums = _tmp2_;
	_tmp3_ = gtk_list_store_new (3, GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_INT64, -1);
	_data7_->model = _tmp3_;
	_tmp4_ = _data7_->model;
	_tmp5_ = (GtkIconView*) gtk_icon_view_new_with_model ((GtkTreeModel*) _tmp4_);
	g_object_ref_sink (_tmp5_);
	_data7_->vista = _tmp5_;
	_tmp6_ = _data7_->vista;
	gtk_icon_view_set_pixbuf_column (_tmp6_, 0);
	_tmp7_ = _data7_->vista;
	gtk_icon_view_set_text_column (_tmp7_, 1);
	_tmp8_ = _data7_->vista;
	gtk_icon_view_set_item_width (_tmp8_, 120);
	memset (&_data7_->iter, 0, sizeof (GtkTreeIter));
	{
		GeeArrayList* _a_list = NULL;
		GeeArrayList* _tmp9_ = NULL;
		GeeArrayList* _tmp10_ = NULL;
		gint _a_size = 0;
		GeeArrayList* _tmp11_ = NULL;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		gint _a_index = 0;
		_tmp9_ = albums;
		_tmp10_ = _g_object_ref0 (_tmp9_);
		_a_list = _tmp10_;
		_tmp11_ = _a_list;
		_tmp12_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp11_);
		_tmp13_ = _tmp12_;
		_a_size = _tmp13_;
		_a_index = -1;
		while (TRUE) {
			gint _tmp14_ = 0;
			gint _tmp15_ = 0;
			gint _tmp16_ = 0;
			GraphMediaModelosAlbumImagenes* a = NULL;
			GeeArrayList* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			gpointer _tmp19_ = NULL;
			GtkListStore* _tmp20_ = NULL;
			GtkTreeIter _tmp21_ = {0};
			GtkListStore* _tmp22_ = NULL;
			GtkTreeIter _tmp23_ = {0};
			GdkPixbuf* _tmp24_ = NULL;
			GdkPixbuf* _tmp25_ = NULL;
			GraphMediaModelosAlbumImagenes* _tmp26_ = NULL;
			const gchar* _tmp27_ = NULL;
			GraphMediaModelosAlbumImagenes* _tmp28_ = NULL;
			gint64 _tmp29_ = 0LL;
			_tmp14_ = _a_index;
			_a_index = _tmp14_ + 1;
			_tmp15_ = _a_index;
			_tmp16_ = _a_size;
			if (!(_tmp15_ < _tmp16_)) {
				break;
			}
			_tmp17_ = _a_list;
			_tmp18_ = _a_index;
			_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
			a = (GraphMediaModelosAlbumImagenes*) _tmp19_;
			_tmp20_ = _data7_->model;
			gtk_list_store_append (_tmp20_, &_tmp21_);
			_data7_->iter = _tmp21_;
			_tmp22_ = _data7_->model;
			_tmp23_ = _data7_->iter;
			_tmp24_ = graph_media_modelos_filtrable_cargar_icono_ubicacion ((GraphMediaModelosFiltrable*) self, "caratula", GRAPH_MEDIA_MODELOS_APP_GUI_TAM_ICONO, GRAPH_MEDIA_MODELOS_APP_GUI_TAM_ICONO);
			_tmp25_ = _tmp24_;
			_tmp26_ = a;
			_tmp27_ = ((GraphMediaModelosAlbum*) _tmp26_)->nombre;
			_tmp28_ = a;
			_tmp29_ = ((GraphMediaModelosAlbum*) _tmp28_)->id;
			gtk_list_store_set (_tmp22_, &_tmp23_, 0, _tmp25_, 1, _tmp27_, 2, _tmp29_, -1);
			_g_object_unref0 (_tmp25_);
			_graph_media_modelos_album_unref0 (a);
		}
		_g_object_unref0 (_a_list);
	}
	_tmp30_ = _data7_->vista;
	g_signal_connect_data (_tmp30_, "selection-changed", (GCallback) ___lambda8__gtk_icon_view_selection_changed, block7_data_ref (_data7_), (GClosureNotify) block7_data_unref, 0);
	_tmp31_ = _data7_->vista;
	_tmp32_ = _g_object_ref0 (_tmp31_);
	result = _tmp32_;
	_g_object_unref0 (albums);
	block7_data_unref (_data7_);
	_data7_ = NULL;
	return result;
}


static void graph_media_modelos_albums_imagenes_class_init (GraphMediaModelosAlbumsImagenesClass * klass) {
	graph_media_modelos_albums_imagenes_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = graph_media_modelos_albums_imagenes_finalize;
}


static void graph_media_modelos_albums_imagenes_graph_media_modelos_filtrable_interface_init (GraphMediaModelosFiltrableIface * iface) {
	graph_media_modelos_albums_imagenes_graph_media_modelos_filtrable_parent_iface = g_type_interface_peek_parent (iface);
	iface->filtrar = (GtkIconView* (*)(GraphMediaModelosFiltrable*, const gchar*, gint)) graph_media_modelos_albums_imagenes_real_filtrar;
}


static void graph_media_modelos_albums_imagenes_instance_init (GraphMediaModelosAlbumsImagenes * self) {
}


static void graph_media_modelos_albums_imagenes_finalize (GObject* obj) {
	GraphMediaModelosAlbumsImagenes * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenes);
	G_OBJECT_CLASS (graph_media_modelos_albums_imagenes_parent_class)->finalize (obj);
}


GType graph_media_modelos_albums_imagenes_get_type (void) {
	static volatile gsize graph_media_modelos_albums_imagenes_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_albums_imagenes_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosAlbumsImagenesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_albums_imagenes_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosAlbumsImagenes), 0, (GInstanceInitFunc) graph_media_modelos_albums_imagenes_instance_init, NULL };
		static const GInterfaceInfo graph_media_modelos_filtrable_info = { (GInterfaceInitFunc) graph_media_modelos_albums_imagenes_graph_media_modelos_filtrable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType graph_media_modelos_albums_imagenes_type_id;
		graph_media_modelos_albums_imagenes_type_id = g_type_register_static (GRAPH_MEDIA_MODELOS_TYPE_TABLAS, "GraphMediaModelosAlbumsImagenes", &g_define_type_info, 0);
		g_type_add_interface_static (graph_media_modelos_albums_imagenes_type_id, GRAPH_MEDIA_MODELOS_TYPE_FILTRABLE, &graph_media_modelos_filtrable_info);
		g_once_init_leave (&graph_media_modelos_albums_imagenes_type_id__volatile, graph_media_modelos_albums_imagenes_type_id);
	}
	return graph_media_modelos_albums_imagenes_type_id__volatile;
}



