/* basedatos.c generated by valac 0.26.0, the Vala compiler
 * generated from basedatos.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define GRAPH_MEDIA_TYPE_BASE_DATOS (graph_media_base_datos_get_type ())
#define GRAPH_MEDIA_BASE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_TYPE_BASE_DATOS, GraphMediaBaseDatos))
#define GRAPH_MEDIA_BASE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_TYPE_BASE_DATOS, GraphMediaBaseDatosClass))
#define GRAPH_MEDIA_IS_BASE_DATOS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_TYPE_BASE_DATOS))
#define GRAPH_MEDIA_IS_BASE_DATOS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_TYPE_BASE_DATOS))
#define GRAPH_MEDIA_BASE_DATOS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_TYPE_BASE_DATOS, GraphMediaBaseDatosClass))

typedef struct _GraphMediaBaseDatos GraphMediaBaseDatos;
typedef struct _GraphMediaBaseDatosClass GraphMediaBaseDatosClass;
typedef struct _GraphMediaBaseDatosPrivate GraphMediaBaseDatosPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_TABLAS (graph_media_modelos_tablas_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablas))
#define GRAPH_MEDIA_MODELOS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_TABLAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))

typedef struct _GraphMediaModelosTablas GraphMediaModelosTablas;
typedef struct _GraphMediaModelosTablasClass GraphMediaModelosTablasClass;

#define GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS (graph_media_modelos_tabla_personas_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonas))
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonasClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_PERSONAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_PERSONAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS))
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonasClass))

typedef struct _GraphMediaModelosTablaPersonas GraphMediaModelosTablaPersonas;
typedef struct _GraphMediaModelosTablaPersonasClass GraphMediaModelosTablaPersonasClass;

#define GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS (graph_media_modelos_artistas_get_type ())
#define GRAPH_MEDIA_MODELOS_ARTISTAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS, GraphMediaModelosArtistas))
#define GRAPH_MEDIA_MODELOS_ARTISTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS, GraphMediaModelosArtistasClass))
#define GRAPH_MEDIA_MODELOS_IS_ARTISTAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS))
#define GRAPH_MEDIA_MODELOS_IS_ARTISTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS))
#define GRAPH_MEDIA_MODELOS_ARTISTAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTAS, GraphMediaModelosArtistasClass))

typedef struct _GraphMediaModelosArtistas GraphMediaModelosArtistas;
typedef struct _GraphMediaModelosArtistasClass GraphMediaModelosArtistasClass;

#define GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES (graph_media_modelos_albums_musicales_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUMS_MUSICALES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES, GraphMediaModelosAlbumsMusicales))
#define GRAPH_MEDIA_MODELOS_ALBUMS_MUSICALES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES, GraphMediaModelosAlbumsMusicalesClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_MUSICALES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_MUSICALES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES))
#define GRAPH_MEDIA_MODELOS_ALBUMS_MUSICALES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_MUSICALES, GraphMediaModelosAlbumsMusicalesClass))

typedef struct _GraphMediaModelosAlbumsMusicales GraphMediaModelosAlbumsMusicales;
typedef struct _GraphMediaModelosAlbumsMusicalesClass GraphMediaModelosAlbumsMusicalesClass;

#define GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS (graph_media_modelos_sentimientos_get_type ())
#define GRAPH_MEDIA_MODELOS_SENTIMIENTOS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS, GraphMediaModelosSentimientos))
#define GRAPH_MEDIA_MODELOS_SENTIMIENTOS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS, GraphMediaModelosSentimientosClass))
#define GRAPH_MEDIA_MODELOS_IS_SENTIMIENTOS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS))
#define GRAPH_MEDIA_MODELOS_IS_SENTIMIENTOS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS))
#define GRAPH_MEDIA_MODELOS_SENTIMIENTOS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_SENTIMIENTOS, GraphMediaModelosSentimientosClass))

typedef struct _GraphMediaModelosSentimientos GraphMediaModelosSentimientos;
typedef struct _GraphMediaModelosSentimientosClass GraphMediaModelosSentimientosClass;

#define GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO (graph_media_modelos_tabla_archivo_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLA_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO, GraphMediaModelosTablaArchivo))
#define GRAPH_MEDIA_MODELOS_TABLA_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO, GraphMediaModelosTablaArchivoClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_TABLA_ARCHIVO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_ARCHIVO, GraphMediaModelosTablaArchivoClass))

typedef struct _GraphMediaModelosTablaArchivo GraphMediaModelosTablaArchivo;
typedef struct _GraphMediaModelosTablaArchivoClass GraphMediaModelosTablaArchivoClass;

#define GRAPH_MEDIA_MODELOS_TYPE_CANCIONES (graph_media_modelos_canciones_get_type ())
#define GRAPH_MEDIA_MODELOS_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_CANCIONES, GraphMediaModelosCanciones))
#define GRAPH_MEDIA_MODELOS_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_CANCIONES, GraphMediaModelosCancionesClass))
#define GRAPH_MEDIA_MODELOS_IS_CANCIONES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_CANCIONES))
#define GRAPH_MEDIA_MODELOS_IS_CANCIONES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_CANCIONES))
#define GRAPH_MEDIA_MODELOS_CANCIONES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_CANCIONES, GraphMediaModelosCancionesClass))

typedef struct _GraphMediaModelosCanciones GraphMediaModelosCanciones;
typedef struct _GraphMediaModelosCancionesClass GraphMediaModelosCancionesClass;

#define GRAPH_MEDIA_MODELOS_TYPE_IMAGENES (graph_media_modelos_imagenes_get_type ())
#define GRAPH_MEDIA_MODELOS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGENES, GraphMediaModelosImagenes))
#define GRAPH_MEDIA_MODELOS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_IMAGENES, GraphMediaModelosImagenesClass))
#define GRAPH_MEDIA_MODELOS_IS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGENES))
#define GRAPH_MEDIA_MODELOS_IS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_IMAGENES))
#define GRAPH_MEDIA_MODELOS_IMAGENES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_IMAGENES, GraphMediaModelosImagenesClass))

typedef struct _GraphMediaModelosImagenes GraphMediaModelosImagenes;
typedef struct _GraphMediaModelosImagenesClass GraphMediaModelosImagenesClass;

#define GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES (graph_media_modelos_albums_imagenes_get_type ())
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenes))
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenesClass))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_IMAGENES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES))
#define GRAPH_MEDIA_MODELOS_IS_ALBUMS_IMAGENES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES))
#define GRAPH_MEDIA_MODELOS_ALBUMS_IMAGENES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ALBUMS_IMAGENES, GraphMediaModelosAlbumsImagenesClass))

typedef struct _GraphMediaModelosAlbumsImagenes GraphMediaModelosAlbumsImagenes;
typedef struct _GraphMediaModelosAlbumsImagenesClass GraphMediaModelosAlbumsImagenesClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _GraphMediaParamSpecBaseDatos GraphMediaParamSpecBaseDatos;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GraphMediaBaseDatos {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GraphMediaBaseDatosPrivate * priv;
};

struct _GraphMediaBaseDatosClass {
	GTypeClass parent_class;
	void (*finalize) (GraphMediaBaseDatos *self);
};

struct _GraphMediaBaseDatosPrivate {
	gchar* nombre_archivo;
	GraphMediaModelosArtistas* artistas;
	GraphMediaModelosAlbumsMusicales* albums_musicales;
	GraphMediaModelosSentimientos* sentimientos;
	GraphMediaModelosCanciones* canciones;
	GraphMediaModelosImagenes* imagenes;
	GraphMediaModelosAlbumsImagenes* albums_imagenes;
};

struct _GraphMediaParamSpecBaseDatos {
	GParamSpec parent_instance;
};


static gpointer graph_media_base_datos_parent_class = NULL;

gpointer graph_media_base_datos_ref (gpointer instance);
void graph_media_base_datos_unref (gpointer instance);
GParamSpec* graph_media_param_spec_base_datos (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void graph_media_value_set_base_datos (GValue* value, gpointer v_object);
void graph_media_value_take_base_datos (GValue* value, gpointer v_object);
gpointer graph_media_value_get_base_datos (const GValue* value);
GType graph_media_base_datos_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_tablas_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_tabla_personas_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_artistas_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_albums_musicales_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_sentimientos_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_tabla_archivo_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_canciones_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_imagenes_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_albums_imagenes_get_type (void) G_GNUC_CONST;
#define GRAPH_MEDIA_BASE_DATOS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRAPH_MEDIA_TYPE_BASE_DATOS, GraphMediaBaseDatosPrivate))
enum  {
	GRAPH_MEDIA_BASE_DATOS_DUMMY_PROPERTY
};
void graph_media_base_datos_seleccionar_archivo (GraphMediaBaseDatos* self, const gchar* archivo);
void graph_media_base_datos_inicializar (GraphMediaBaseDatos* self);
void graph_media_modelos_tablas_inicializar (const gchar* archivo);
GraphMediaModelosArtistas* graph_media_base_datos_get_artistas (GraphMediaBaseDatos* self);
GraphMediaModelosArtistas* graph_media_modelos_artistas_get_instancia (void);
GraphMediaModelosAlbumsMusicales* graph_media_base_datos_get_albums_musicales (GraphMediaBaseDatos* self);
GraphMediaModelosAlbumsMusicales* graph_media_modelos_albums_musicales_get_instancia (void);
GraphMediaModelosAlbumsImagenes* graph_media_base_datos_get_albums_imagenes (GraphMediaBaseDatos* self);
GraphMediaModelosAlbumsImagenes* graph_media_modelos_albums_imagenes_get_instancia (void);
GraphMediaModelosSentimientos* graph_media_base_datos_get_sentimientos (GraphMediaBaseDatos* self);
GraphMediaModelosSentimientos* graph_media_modelos_sentimientos_get_instancia (void);
GraphMediaModelosCanciones* graph_media_base_datos_get_canciones (GraphMediaBaseDatos* self);
GraphMediaModelosCanciones* graph_media_modelos_canciones_get_instancia (void);
GraphMediaModelosImagenes* graph_media_base_datos_get_imagenes (GraphMediaBaseDatos* self);
GraphMediaModelosImagenes* graph_media_modelos_imagenes_get_instancia (void);
GraphMediaBaseDatos* graph_media_base_datos_new (void);
GraphMediaBaseDatos* graph_media_base_datos_construct (GType object_type);
static void graph_media_base_datos_finalize (GraphMediaBaseDatos* obj);


void graph_media_base_datos_seleccionar_archivo (GraphMediaBaseDatos* self, const gchar* archivo) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (archivo != NULL);
	_tmp0_ = archivo;
	_vala_assert (_tmp0_ != NULL, "archivo !=  null");
	_tmp1_ = archivo;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->nombre_archivo);
	self->priv->nombre_archivo = _tmp2_;
}


void graph_media_base_datos_inicializar (GraphMediaBaseDatos* self) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->nombre_archivo;
	_vala_assert (_tmp0_ != NULL, "nombre_archivo != null");
	_tmp1_ = self->priv->nombre_archivo;
	graph_media_modelos_tablas_inicializar (_tmp1_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GraphMediaModelosArtistas* graph_media_base_datos_get_artistas (GraphMediaBaseDatos* self) {
	GraphMediaModelosArtistas* result = NULL;
	GraphMediaModelosArtistas* _tmp0_ = NULL;
	GraphMediaModelosArtistas* _tmp2_ = NULL;
	GraphMediaModelosArtistas* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->artistas;
	if (_tmp0_ == NULL) {
		GraphMediaModelosArtistas* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_artistas_get_instancia ();
		_g_object_unref0 (self->priv->artistas);
		self->priv->artistas = _tmp1_;
	}
	_tmp2_ = self->priv->artistas;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaModelosAlbumsMusicales* graph_media_base_datos_get_albums_musicales (GraphMediaBaseDatos* self) {
	GraphMediaModelosAlbumsMusicales* result = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp0_ = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp2_ = NULL;
	GraphMediaModelosAlbumsMusicales* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->albums_musicales;
	if (_tmp0_ == NULL) {
		GraphMediaModelosAlbumsMusicales* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_albums_musicales_get_instancia ();
		_g_object_unref0 (self->priv->albums_musicales);
		self->priv->albums_musicales = _tmp1_;
	}
	_tmp2_ = self->priv->albums_musicales;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaModelosAlbumsImagenes* graph_media_base_datos_get_albums_imagenes (GraphMediaBaseDatos* self) {
	GraphMediaModelosAlbumsImagenes* result = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp0_ = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp2_ = NULL;
	GraphMediaModelosAlbumsImagenes* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->albums_imagenes;
	if (_tmp0_ == NULL) {
		GraphMediaModelosAlbumsImagenes* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_albums_imagenes_get_instancia ();
		_g_object_unref0 (self->priv->albums_imagenes);
		self->priv->albums_imagenes = _tmp1_;
	}
	_tmp2_ = self->priv->albums_imagenes;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaModelosSentimientos* graph_media_base_datos_get_sentimientos (GraphMediaBaseDatos* self) {
	GraphMediaModelosSentimientos* result = NULL;
	GraphMediaModelosSentimientos* _tmp0_ = NULL;
	GraphMediaModelosSentimientos* _tmp2_ = NULL;
	GraphMediaModelosSentimientos* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->sentimientos;
	if (_tmp0_ == NULL) {
		GraphMediaModelosSentimientos* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_sentimientos_get_instancia ();
		_g_object_unref0 (self->priv->sentimientos);
		self->priv->sentimientos = _tmp1_;
	}
	_tmp2_ = self->priv->sentimientos;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaModelosCanciones* graph_media_base_datos_get_canciones (GraphMediaBaseDatos* self) {
	GraphMediaModelosCanciones* result = NULL;
	GraphMediaModelosCanciones* _tmp0_ = NULL;
	GraphMediaModelosCanciones* _tmp2_ = NULL;
	GraphMediaModelosCanciones* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->canciones;
	if (_tmp0_ == NULL) {
		GraphMediaModelosCanciones* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_canciones_get_instancia ();
		_g_object_unref0 (self->priv->canciones);
		self->priv->canciones = _tmp1_;
	}
	_tmp2_ = self->priv->canciones;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaModelosImagenes* graph_media_base_datos_get_imagenes (GraphMediaBaseDatos* self) {
	GraphMediaModelosImagenes* result = NULL;
	GraphMediaModelosImagenes* _tmp0_ = NULL;
	GraphMediaModelosImagenes* _tmp2_ = NULL;
	GraphMediaModelosImagenes* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->imagenes;
	if (_tmp0_ == NULL) {
		GraphMediaModelosImagenes* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_imagenes_get_instancia ();
		_g_object_unref0 (self->priv->imagenes);
		self->priv->imagenes = _tmp1_;
	}
	_tmp2_ = self->priv->imagenes;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GraphMediaBaseDatos* graph_media_base_datos_construct (GType object_type) {
	GraphMediaBaseDatos* self = NULL;
	self = (GraphMediaBaseDatos*) g_type_create_instance (object_type);
	return self;
}


GraphMediaBaseDatos* graph_media_base_datos_new (void) {
	return graph_media_base_datos_construct (GRAPH_MEDIA_TYPE_BASE_DATOS);
}


static void graph_media_value_base_datos_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void graph_media_value_base_datos_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		graph_media_base_datos_unref (value->data[0].v_pointer);
	}
}


static void graph_media_value_base_datos_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = graph_media_base_datos_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer graph_media_value_base_datos_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* graph_media_value_base_datos_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GraphMediaBaseDatos* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = graph_media_base_datos_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* graph_media_value_base_datos_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GraphMediaBaseDatos** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = graph_media_base_datos_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* graph_media_param_spec_base_datos (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GraphMediaParamSpecBaseDatos* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GRAPH_MEDIA_TYPE_BASE_DATOS), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer graph_media_value_get_base_datos (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_TYPE_BASE_DATOS), NULL);
	return value->data[0].v_pointer;
}


void graph_media_value_set_base_datos (GValue* value, gpointer v_object) {
	GraphMediaBaseDatos* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_TYPE_BASE_DATOS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_TYPE_BASE_DATOS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		graph_media_base_datos_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_base_datos_unref (old);
	}
}


void graph_media_value_take_base_datos (GValue* value, gpointer v_object) {
	GraphMediaBaseDatos* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_TYPE_BASE_DATOS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_TYPE_BASE_DATOS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_base_datos_unref (old);
	}
}


static void graph_media_base_datos_class_init (GraphMediaBaseDatosClass * klass) {
	graph_media_base_datos_parent_class = g_type_class_peek_parent (klass);
	((GraphMediaBaseDatosClass *) klass)->finalize = graph_media_base_datos_finalize;
	g_type_class_add_private (klass, sizeof (GraphMediaBaseDatosPrivate));
}


static void graph_media_base_datos_instance_init (GraphMediaBaseDatos * self) {
	self->priv = GRAPH_MEDIA_BASE_DATOS_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void graph_media_base_datos_finalize (GraphMediaBaseDatos* obj) {
	GraphMediaBaseDatos * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_TYPE_BASE_DATOS, GraphMediaBaseDatos);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->nombre_archivo);
	_g_object_unref0 (self->priv->artistas);
	_g_object_unref0 (self->priv->albums_musicales);
	_g_object_unref0 (self->priv->sentimientos);
	_g_object_unref0 (self->priv->canciones);
	_g_object_unref0 (self->priv->imagenes);
	_g_object_unref0 (self->priv->albums_imagenes);
}


/**
* Clase que prove los singletones de cada una de las tablas
* para poder manipular la base de datos desde
* cualquier punto de la aplicacion con el mismo objeto para 
* no desperdiciar memoria.
*/
GType graph_media_base_datos_get_type (void) {
	static volatile gsize graph_media_base_datos_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_base_datos_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { graph_media_value_base_datos_init, graph_media_value_base_datos_free_value, graph_media_value_base_datos_copy_value, graph_media_value_base_datos_peek_pointer, "p", graph_media_value_base_datos_collect_value, "p", graph_media_value_base_datos_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaBaseDatosClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_base_datos_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaBaseDatos), 0, (GInstanceInitFunc) graph_media_base_datos_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType graph_media_base_datos_type_id;
		graph_media_base_datos_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GraphMediaBaseDatos", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&graph_media_base_datos_type_id__volatile, graph_media_base_datos_type_id);
	}
	return graph_media_base_datos_type_id__volatile;
}


gpointer graph_media_base_datos_ref (gpointer instance) {
	GraphMediaBaseDatos* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void graph_media_base_datos_unref (gpointer instance) {
	GraphMediaBaseDatos* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GRAPH_MEDIA_BASE_DATOS_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



