/* persona.c generated by valac 0.26.0, the Vala compiler
 * generated from persona.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <sqlite3.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define GRAPH_MEDIA_MODELOS_TYPE_PERSONA (graph_media_modelos_persona_get_type ())
#define GRAPH_MEDIA_MODELOS_PERSONA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA, GraphMediaModelosPersona))
#define GRAPH_MEDIA_MODELOS_PERSONA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_PERSONA, GraphMediaModelosPersonaClass))
#define GRAPH_MEDIA_MODELOS_IS_PERSONA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA))
#define GRAPH_MEDIA_MODELOS_IS_PERSONA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_PERSONA))
#define GRAPH_MEDIA_MODELOS_PERSONA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA, GraphMediaModelosPersonaClass))

typedef struct _GraphMediaModelosPersona GraphMediaModelosPersona;
typedef struct _GraphMediaModelosPersonaClass GraphMediaModelosPersonaClass;
typedef struct _GraphMediaModelosPersonaPrivate GraphMediaModelosPersonaPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define GRAPH_MEDIA_MODELOS_TYPE_ARTISTA (graph_media_modelos_artista_get_type ())
#define GRAPH_MEDIA_MODELOS_ARTISTA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTA, GraphMediaModelosArtista))
#define GRAPH_MEDIA_MODELOS_ARTISTA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARTISTA, GraphMediaModelosArtistaClass))
#define GRAPH_MEDIA_MODELOS_IS_ARTISTA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTA))
#define GRAPH_MEDIA_MODELOS_IS_ARTISTA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARTISTA))
#define GRAPH_MEDIA_MODELOS_ARTISTA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARTISTA, GraphMediaModelosArtistaClass))

typedef struct _GraphMediaModelosArtista GraphMediaModelosArtista;
typedef struct _GraphMediaModelosArtistaClass GraphMediaModelosArtistaClass;
#define _graph_media_modelos_persona_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_modelos_persona_unref (var), NULL)))
typedef struct _GraphMediaModelosParamSpecPersona GraphMediaModelosParamSpecPersona;

#define GRAPH_MEDIA_MODELOS_TYPE_TABLAS (graph_media_modelos_tablas_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablas))
#define GRAPH_MEDIA_MODELOS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_IS_TABLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLAS))
#define GRAPH_MEDIA_MODELOS_TABLAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLAS, GraphMediaModelosTablasClass))

typedef struct _GraphMediaModelosTablas GraphMediaModelosTablas;
typedef struct _GraphMediaModelosTablasClass GraphMediaModelosTablasClass;
typedef struct _GraphMediaModelosTablasPrivate GraphMediaModelosTablasPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS (graph_media_modelos_tabla_personas_get_type ())
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonas))
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonasClass))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_PERSONAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS))
#define GRAPH_MEDIA_MODELOS_IS_TABLA_PERSONAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS))
#define GRAPH_MEDIA_MODELOS_TABLA_PERSONAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonasClass))

typedef struct _GraphMediaModelosTablaPersonas GraphMediaModelosTablaPersonas;
typedef struct _GraphMediaModelosTablaPersonasClass GraphMediaModelosTablaPersonasClass;
typedef struct _GraphMediaModelosTablaPersonasPrivate GraphMediaModelosTablaPersonasPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))

#define GRAPH_MEDIA_MODELOS_TYPE_RELACION (graph_media_modelos_relacion_get_type ())
#define GRAPH_MEDIA_MODELOS_RELACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_RELACION, GraphMediaModelosRelacion))
#define GRAPH_MEDIA_MODELOS_RELACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_RELACION, GraphMediaModelosRelacionClass))
#define GRAPH_MEDIA_MODELOS_IS_RELACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_RELACION))
#define GRAPH_MEDIA_MODELOS_IS_RELACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_RELACION))
#define GRAPH_MEDIA_MODELOS_RELACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_RELACION, GraphMediaModelosRelacionClass))

typedef struct _GraphMediaModelosRelacion GraphMediaModelosRelacion;
typedef struct _GraphMediaModelosRelacionClass GraphMediaModelosRelacionClass;
typedef struct _GraphMediaModelosRelacionPrivate GraphMediaModelosRelacionPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO (graph_media_modelos_persona_archivo_get_type ())
#define GRAPH_MEDIA_MODELOS_PERSONA_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO, GraphMediaModelosPersonaArchivo))
#define GRAPH_MEDIA_MODELOS_PERSONA_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO, GraphMediaModelosPersonaArchivoClass))
#define GRAPH_MEDIA_MODELOS_IS_PERSONA_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_IS_PERSONA_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_PERSONA_ARCHIVO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO, GraphMediaModelosPersonaArchivoClass))

typedef struct _GraphMediaModelosPersonaArchivo GraphMediaModelosPersonaArchivo;
typedef struct _GraphMediaModelosPersonaArchivoClass GraphMediaModelosPersonaArchivoClass;
typedef struct _GraphMediaModelosPersonaArchivoPrivate GraphMediaModelosPersonaArchivoPrivate;

#define GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO (graph_media_modelos_archivo_get_type ())
#define GRAPH_MEDIA_MODELOS_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivo))
#define GRAPH_MEDIA_MODELOS_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivoClass))
#define GRAPH_MEDIA_MODELOS_IS_ARCHIVO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_IS_ARCHIVO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO))
#define GRAPH_MEDIA_MODELOS_ARCHIVO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, GraphMediaModelosArchivoClass))

typedef struct _GraphMediaModelosArchivo GraphMediaModelosArchivo;
typedef struct _GraphMediaModelosArchivoClass GraphMediaModelosArchivoClass;
typedef struct _GraphMediaModelosArchivoPrivate GraphMediaModelosArchivoPrivate;
#define _graph_media_modelos_archivo_unref0(var) ((var == NULL) ? NULL : (var = (graph_media_modelos_archivo_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GraphMediaModelosPersona {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GraphMediaModelosPersonaPrivate * priv;
	gint64 id;
	gchar* nombre;
	gchar* rol;
	gint edad;
	gdouble popularidad;
	gchar* nacionalidad;
	gchar* imagen;
};

struct _GraphMediaModelosPersonaClass {
	GTypeClass parent_class;
	void (*finalize) (GraphMediaModelosPersona *self);
};

struct _GraphMediaModelosParamSpecPersona {
	GParamSpec parent_instance;
};

struct _GraphMediaModelosTablas {
	GObject parent_instance;
	GraphMediaModelosTablasPrivate * priv;
	gchar* nombre_tabla;
};

struct _GraphMediaModelosTablasClass {
	GObjectClass parent_class;
};

struct _GraphMediaModelosTablaPersonas {
	GraphMediaModelosTablas parent_instance;
	GraphMediaModelosTablaPersonasPrivate * priv;
};

struct _GraphMediaModelosTablaPersonasClass {
	GraphMediaModelosTablasClass parent_class;
};

typedef enum  {
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_ARCHIVO_NO_ENCONTRADO,
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_ARCHIVO_INVALIDO,
	GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_CONSULTA
} GraphMediaModelosErrorBaseDatos;
#define GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS graph_media_modelos_error_base_datos_quark ()
struct _GraphMediaModelosRelacion {
	GraphMediaModelosTablas parent_instance;
	GraphMediaModelosRelacionPrivate * priv;
	gchar* llave;
	gchar* puerta;
	gchar* tabla_llave;
	gchar* tabla_puerta;
};

struct _GraphMediaModelosRelacionClass {
	GraphMediaModelosTablasClass parent_class;
};

struct _GraphMediaModelosPersonaArchivo {
	GraphMediaModelosRelacion parent_instance;
	GraphMediaModelosPersonaArchivoPrivate * priv;
};

struct _GraphMediaModelosPersonaArchivoClass {
	GraphMediaModelosRelacionClass parent_class;
};

struct _GraphMediaModelosArchivo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GraphMediaModelosArchivoPrivate * priv;
	gint64 id;
	gchar* nombre;
	gchar* ubicacion;
	gchar* tipo;
	gchar* u_acceso;
	gdouble popularidad;
	gboolean disponible;
};

struct _GraphMediaModelosArchivoClass {
	GTypeClass parent_class;
	void (*finalize) (GraphMediaModelosArchivo *self);
};


static gpointer graph_media_modelos_persona_parent_class = NULL;
static gpointer graph_media_modelos_tabla_personas_parent_class = NULL;
static GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_instancia;
static GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_instancia = NULL;
extern sqlite3* graph_media_modelos_tablas_bd;
static gpointer graph_media_modelos_persona_archivo_parent_class = NULL;
static GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_instancia;
static GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_instancia = NULL;

gpointer graph_media_modelos_persona_ref (gpointer instance);
void graph_media_modelos_persona_unref (gpointer instance);
GParamSpec* graph_media_modelos_param_spec_persona (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void graph_media_modelos_value_set_persona (GValue* value, gpointer v_object);
void graph_media_modelos_value_take_persona (GValue* value, gpointer v_object);
gpointer graph_media_modelos_value_get_persona (const GValue* value);
GType graph_media_modelos_persona_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_PERSONA_DUMMY_PROPERTY
};
GraphMediaModelosPersona* graph_media_modelos_persona_new (void);
GraphMediaModelosPersona* graph_media_modelos_persona_construct (GType object_type);
GType graph_media_modelos_artista_get_type (void) G_GNUC_CONST;
GraphMediaModelosArtista* graph_media_modelos_persona_cast_artista (GraphMediaModelosPersona* p);
GraphMediaModelosArtista* graph_media_modelos_artista_new (void);
GraphMediaModelosArtista* graph_media_modelos_artista_construct (GType object_type);
gboolean graph_media_modelos_persona_es_valida (GraphMediaModelosPersona* self);
static void graph_media_modelos_persona_finalize (GraphMediaModelosPersona* obj);
GType graph_media_modelos_tablas_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_tabla_personas_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_TABLA_PERSONAS_DUMMY_PROPERTY
};
GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_new (void);
GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_construct (GType object_type);
GraphMediaModelosTablas* graph_media_modelos_tablas_construct (GType object_type);
void graph_media_modelos_tablas_set_nombre_tabla (GraphMediaModelosTablas* self, const gchar* nombre_tabla);
GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_get_instancia (void);
GraphMediaModelosPersona* graph_media_modelos_tabla_personas_agregar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* persona);
GQuark graph_media_modelos_error_base_datos_quark (void);
GraphMediaModelosPersona* graph_media_modelos_tabla_personas_eliminar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* p, GError** error);
gboolean graph_media_modelos_tablas_eliminar_celda_por_id (GraphMediaModelosTablas* self, gint64 id);
gboolean graph_media_modelos_tabla_personas_editar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* p);
GraphMediaModelosPersona* graph_media_modelos_tabla_personas_get_persona_id (GraphMediaModelosTablaPersonas* self, gint64 id);
gboolean graph_media_modelos_tablas_existe_id (GraphMediaModelosTablas* self, gint64 id);
gint graph_media_modelos_tabla_personas_get_total_personas (GraphMediaModelosTablaPersonas* self);
gint graph_media_modelos_tablas_get_total_celdas (GraphMediaModelosTablas* self, const gchar* columna);
GeeArrayList* graph_media_modelos_tabla_personas_get_personas (GraphMediaModelosTablaPersonas* self, const gchar* where, gint limite, const gchar* orden);
static void graph_media_modelos_tabla_personas_finalize (GObject* obj);
GType graph_media_modelos_relacion_get_type (void) G_GNUC_CONST;
GType graph_media_modelos_persona_archivo_get_type (void) G_GNUC_CONST;
enum  {
	GRAPH_MEDIA_MODELOS_PERSONA_ARCHIVO_DUMMY_PROPERTY
};
GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_new (void);
GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_construct (GType object_type);
GraphMediaModelosRelacion* graph_media_modelos_relacion_construct (GType object_type);
void graph_media_modelos_relacion_set_llave (GraphMediaModelosRelacion* self, const gchar* columna);
void graph_media_modelos_relacion_set_puerta (GraphMediaModelosRelacion* self, const gchar* columna);
void graph_media_modelos_relacion_set_tabla_llave (GraphMediaModelosRelacion* self, const gchar* columna);
void graph_media_modelos_relacion_set_tabla_puerta (GraphMediaModelosRelacion* self, const gchar* columna);
GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_get_instancia (void);
gpointer graph_media_modelos_archivo_ref (gpointer instance);
void graph_media_modelos_archivo_unref (gpointer instance);
GParamSpec* graph_media_modelos_param_spec_archivo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void graph_media_modelos_value_set_archivo (GValue* value, gpointer v_object);
void graph_media_modelos_value_take_archivo (GValue* value, gpointer v_object);
gpointer graph_media_modelos_value_get_archivo (const GValue* value);
GType graph_media_modelos_archivo_get_type (void) G_GNUC_CONST;
void graph_media_modelos_persona_archivo_relaciona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona, GraphMediaModelosArchivo* cancion);
gboolean graph_media_modelos_relacion_relaciona_ids (GraphMediaModelosRelacion* self, gint64 id1, gint64 id2);
void graph_media_modelos_persona_archivo_eliminar_relaciones_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona);
void graph_media_modelos_relacion_eliminar_relaciones_id (GraphMediaModelosRelacion* self, gint64 id);
void graph_media_modelos_persona_archivo_eliminar_relaciones_archivo (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosArchivo* archivo);
void graph_media_modelos_relacion_eliminar_relaciones_secundarias_id (GraphMediaModelosRelacion* self, gint64 id);
gint graph_media_modelos_persona_archivo_n_archivos_por_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona);
gint graph_media_modelos_relacion_total_relaciones_llave (GraphMediaModelosRelacion* self, gint64 id);
gint graph_media_modelos_persona_archivo_n_personas_por_archivo (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosArchivo* archivo);
gint graph_media_modelos_relacion_total_relaciones_puerta (GraphMediaModelosRelacion* self, gint64 id);
GeeArrayList* graph_media_modelos_persona_archivo_archivos_por_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* p);
GraphMediaModelosArchivo* graph_media_modelos_archivo_new (void);
GraphMediaModelosArchivo* graph_media_modelos_archivo_construct (GType object_type);
static void graph_media_modelos_persona_archivo_finalize (GObject* obj);


GraphMediaModelosPersona* graph_media_modelos_persona_construct (GType object_type) {
	GraphMediaModelosPersona* self = NULL;
	self = (GraphMediaModelosPersona*) g_type_create_instance (object_type);
	self->id = (gint64) (-1);
	return self;
}


GraphMediaModelosPersona* graph_media_modelos_persona_new (void) {
	return graph_media_modelos_persona_construct (GRAPH_MEDIA_MODELOS_TYPE_PERSONA);
}


GraphMediaModelosArtista* graph_media_modelos_persona_cast_artista (GraphMediaModelosPersona* p) {
	GraphMediaModelosArtista* result = NULL;
	GraphMediaModelosPersona* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GraphMediaModelosArtista* a = NULL;
	GraphMediaModelosArtista* _tmp2_ = NULL;
	GraphMediaModelosPersona* _tmp3_ = NULL;
	gint64 _tmp4_ = 0LL;
	GraphMediaModelosPersona* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GraphMediaModelosPersona* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	GraphMediaModelosPersona* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	GraphMediaModelosPersona* _tmp13_ = NULL;
	gdouble _tmp14_ = 0.0;
	GraphMediaModelosPersona* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	GraphMediaModelosPersona* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = p;
	_tmp1_ = _tmp0_->rol;
	_vala_assert (g_strcmp0 (_tmp1_, "artista") == 0, "p.rol == \"artista\"");
	_tmp2_ = graph_media_modelos_artista_new ();
	a = _tmp2_;
	_tmp3_ = p;
	_tmp4_ = _tmp3_->id;
	((GraphMediaModelosPersona*) a)->id = _tmp4_;
	_tmp5_ = p;
	_tmp6_ = _tmp5_->nombre;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (((GraphMediaModelosPersona*) a)->nombre);
	((GraphMediaModelosPersona*) a)->nombre = _tmp7_;
	_tmp8_ = p;
	_tmp9_ = _tmp8_->rol;
	_tmp10_ = g_strdup (_tmp9_);
	_g_free0 (((GraphMediaModelosPersona*) a)->rol);
	((GraphMediaModelosPersona*) a)->rol = _tmp10_;
	_tmp11_ = p;
	_tmp12_ = _tmp11_->edad;
	((GraphMediaModelosPersona*) a)->edad = _tmp12_;
	_tmp13_ = p;
	_tmp14_ = _tmp13_->popularidad;
	((GraphMediaModelosPersona*) a)->popularidad = _tmp14_;
	_tmp15_ = p;
	_tmp16_ = _tmp15_->nacionalidad;
	_tmp17_ = g_strdup (_tmp16_);
	_g_free0 (((GraphMediaModelosPersona*) a)->nacionalidad);
	((GraphMediaModelosPersona*) a)->nacionalidad = _tmp17_;
	_tmp18_ = p;
	_tmp19_ = _tmp18_->imagen;
	_tmp20_ = g_strdup (_tmp19_);
	_g_free0 (((GraphMediaModelosPersona*) a)->imagen);
	((GraphMediaModelosPersona*) a)->imagen = _tmp20_;
	result = a;
	return result;
}


gboolean graph_media_modelos_persona_es_valida (GraphMediaModelosPersona* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_ = NULL;
	gboolean valido = FALSE;
	gboolean _tmp7_ = FALSE;
	const gchar* _tmp8_ = NULL;
	gboolean _tmp10_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp2_ = self->nombre;
	if (g_strcmp0 (_tmp2_, "") != 0) {
		const gchar* _tmp3_ = NULL;
		_tmp3_ = self->nombre;
		_tmp1_ = _tmp3_ != NULL;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		gboolean _tmp4_ = FALSE;
		const gchar* _tmp5_ = NULL;
		_tmp5_ = self->rol;
		if (g_strcmp0 (_tmp5_, "artista") == 0) {
			_tmp4_ = TRUE;
		} else {
			const gchar* _tmp6_ = NULL;
			_tmp6_ = self->rol;
			_tmp4_ = g_strcmp0 (_tmp6_, "amigo") == 0;
		}
		_tmp0_ = _tmp4_;
	} else {
		_tmp0_ = FALSE;
	}
	valido = _tmp0_;
	_tmp8_ = self->nacionalidad;
	if (_tmp8_ != NULL) {
		gint64 _tmp9_ = 0LL;
		_tmp9_ = self->id;
		_tmp7_ = _tmp9_ != ((gint64) (-1));
	} else {
		_tmp7_ = FALSE;
	}
	_tmp10_ = valido;
	valido = _tmp10_ & _tmp7_;
	result = valido;
	return result;
}


static void graph_media_modelos_value_persona_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void graph_media_modelos_value_persona_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		graph_media_modelos_persona_unref (value->data[0].v_pointer);
	}
}


static void graph_media_modelos_value_persona_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = graph_media_modelos_persona_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer graph_media_modelos_value_persona_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* graph_media_modelos_value_persona_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GraphMediaModelosPersona* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = graph_media_modelos_persona_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* graph_media_modelos_value_persona_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GraphMediaModelosPersona** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = graph_media_modelos_persona_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* graph_media_modelos_param_spec_persona (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GraphMediaModelosParamSpecPersona* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GRAPH_MEDIA_MODELOS_TYPE_PERSONA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer graph_media_modelos_value_get_persona (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_PERSONA), NULL);
	return value->data[0].v_pointer;
}


void graph_media_modelos_value_set_persona (GValue* value, gpointer v_object) {
	GraphMediaModelosPersona* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_PERSONA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_MODELOS_TYPE_PERSONA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		graph_media_modelos_persona_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_modelos_persona_unref (old);
	}
}


void graph_media_modelos_value_take_persona (GValue* value, gpointer v_object) {
	GraphMediaModelosPersona* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRAPH_MEDIA_MODELOS_TYPE_PERSONA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRAPH_MEDIA_MODELOS_TYPE_PERSONA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		graph_media_modelos_persona_unref (old);
	}
}


static void graph_media_modelos_persona_class_init (GraphMediaModelosPersonaClass * klass) {
	graph_media_modelos_persona_parent_class = g_type_class_peek_parent (klass);
	((GraphMediaModelosPersonaClass *) klass)->finalize = graph_media_modelos_persona_finalize;
}


static void graph_media_modelos_persona_instance_init (GraphMediaModelosPersona * self) {
	self->ref_count = 1;
}


static void graph_media_modelos_persona_finalize (GraphMediaModelosPersona* obj) {
	GraphMediaModelosPersona * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_PERSONA, GraphMediaModelosPersona);
	g_signal_handlers_destroy (self);
	_g_free0 (self->nombre);
	_g_free0 (self->rol);
	_g_free0 (self->nacionalidad);
	_g_free0 (self->imagen);
}


/**
* clase que modela  a una persona, permite modificar sus atributos
* y acceder desde ellos
*/
GType graph_media_modelos_persona_get_type (void) {
	static volatile gsize graph_media_modelos_persona_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_persona_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { graph_media_modelos_value_persona_init, graph_media_modelos_value_persona_free_value, graph_media_modelos_value_persona_copy_value, graph_media_modelos_value_persona_peek_pointer, "p", graph_media_modelos_value_persona_collect_value, "p", graph_media_modelos_value_persona_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosPersonaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_persona_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosPersona), 0, (GInstanceInitFunc) graph_media_modelos_persona_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType graph_media_modelos_persona_type_id;
		graph_media_modelos_persona_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GraphMediaModelosPersona", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&graph_media_modelos_persona_type_id__volatile, graph_media_modelos_persona_type_id);
	}
	return graph_media_modelos_persona_type_id__volatile;
}


gpointer graph_media_modelos_persona_ref (gpointer instance) {
	GraphMediaModelosPersona* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void graph_media_modelos_persona_unref (gpointer instance) {
	GraphMediaModelosPersona* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GRAPH_MEDIA_MODELOS_PERSONA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_construct (GType object_type) {
	GraphMediaModelosTablaPersonas * self = NULL;
	self = (GraphMediaModelosTablaPersonas*) graph_media_modelos_tablas_construct (object_type);
	graph_media_modelos_tablas_set_nombre_tabla ((GraphMediaModelosTablas*) self, "personas");
	return self;
}


GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_new (void) {
	return graph_media_modelos_tabla_personas_construct (GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GraphMediaModelosTablaPersonas* graph_media_modelos_tabla_personas_get_instancia (void) {
	GraphMediaModelosTablaPersonas* result = NULL;
	GraphMediaModelosTablaPersonas* _tmp0_ = NULL;
	GraphMediaModelosTablaPersonas* _tmp2_ = NULL;
	GraphMediaModelosTablaPersonas* _tmp3_ = NULL;
	_tmp0_ = graph_media_modelos_tabla_personas_instancia;
	if (_tmp0_ == NULL) {
		GraphMediaModelosTablaPersonas* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_tabla_personas_new ();
		_g_object_unref0 (graph_media_modelos_tabla_personas_instancia);
		graph_media_modelos_tabla_personas_instancia = _tmp1_;
	}
	_tmp2_ = graph_media_modelos_tabla_personas_instancia;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


/**
* Agrega una persona nueva a la base de datos 
*/
static gpointer _graph_media_modelos_persona_ref0 (gpointer self) {
	return self ? graph_media_modelos_persona_ref (self) : NULL;
}


GraphMediaModelosPersona* graph_media_modelos_tabla_personas_agregar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* persona) {
	GraphMediaModelosPersona* result = NULL;
	sqlite3_stmt* query = NULL;
	gint res = 0;
	sqlite3* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	sqlite3_stmt* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	sqlite3_stmt* _tmp10_ = NULL;
	GraphMediaModelosPersona* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GDestroyNotify _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	sqlite3_stmt* _tmp17_ = NULL;
	GraphMediaModelosPersona* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	GDestroyNotify _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	sqlite3_stmt* _tmp24_ = NULL;
	GraphMediaModelosPersona* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	sqlite3_stmt* _tmp29_ = NULL;
	GraphMediaModelosPersona* _tmp30_ = NULL;
	gdouble _tmp31_ = 0.0;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	sqlite3_stmt* _tmp34_ = NULL;
	GraphMediaModelosPersona* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	GDestroyNotify _tmp38_ = NULL;
	gint _tmp39_ = 0;
	gint _tmp40_ = 0;
	sqlite3_stmt* _tmp41_ = NULL;
	GraphMediaModelosPersona* _tmp42_ = NULL;
	const gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	GDestroyNotify _tmp45_ = NULL;
	gint _tmp46_ = 0;
	sqlite3_stmt* _tmp47_ = NULL;
	gint _tmp48_ = 0;
	gint _tmp49_ = 0;
	GraphMediaModelosPersona* _tmp50_ = NULL;
	sqlite3* _tmp51_ = NULL;
	gint64 _tmp52_ = 0LL;
	GraphMediaModelosPersona* _tmp53_ = NULL;
	gboolean _tmp54_ = FALSE;
	GraphMediaModelosPersona* _tmp55_ = NULL;
	GraphMediaModelosPersona* _tmp56_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (persona != NULL, NULL);
	_tmp0_ = graph_media_modelos_tablas_bd;
	_tmp1_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp2_ = g_strdup_printf ("INSERT INTO %s (nombre, rol, edad, popularidad, nacionalidad, imagen)", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp3_, "VALUES (?, ?, ?, ?, ?, ? )", NULL);
	_tmp5_ = _tmp4_;
	_tmp7_ = sqlite3_prepare_v2 (_tmp0_, _tmp5_, -1, &_tmp6_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp6_;
	_tmp8_ = _tmp7_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	res = _tmp8_;
	_tmp9_ = res;
	_vala_assert (_tmp9_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp10_ = query;
	_tmp11_ = persona;
	_tmp12_ = _tmp11_->nombre;
	_tmp13_ = g_strdup (_tmp12_);
	_tmp14_ = g_free;
	_tmp15_ = sqlite3_bind_text (_tmp10_, 1, _tmp13_, -1, _tmp14_);
	res = _tmp15_;
	_tmp16_ = res;
	_vala_assert (_tmp16_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp17_ = query;
	_tmp18_ = persona;
	_tmp19_ = _tmp18_->rol;
	_tmp20_ = g_strdup (_tmp19_);
	_tmp21_ = g_free;
	_tmp22_ = sqlite3_bind_text (_tmp17_, 2, _tmp20_, -1, _tmp21_);
	res = _tmp22_;
	_tmp23_ = res;
	_vala_assert (_tmp23_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp24_ = query;
	_tmp25_ = persona;
	_tmp26_ = _tmp25_->edad;
	_tmp27_ = sqlite3_bind_int (_tmp24_, 3, _tmp26_);
	res = _tmp27_;
	_tmp28_ = res;
	_vala_assert (_tmp28_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp29_ = query;
	_tmp30_ = persona;
	_tmp31_ = _tmp30_->popularidad;
	_tmp32_ = sqlite3_bind_double (_tmp29_, 4, _tmp31_);
	res = _tmp32_;
	_tmp33_ = res;
	_vala_assert (_tmp33_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp34_ = query;
	_tmp35_ = persona;
	_tmp36_ = _tmp35_->nacionalidad;
	_tmp37_ = g_strdup (_tmp36_);
	_tmp38_ = g_free;
	_tmp39_ = sqlite3_bind_text (_tmp34_, 5, _tmp37_, -1, _tmp38_);
	res = _tmp39_;
	_tmp40_ = res;
	_vala_assert (_tmp40_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp41_ = query;
	_tmp42_ = persona;
	_tmp43_ = _tmp42_->imagen;
	_tmp44_ = g_strdup (_tmp43_);
	_tmp45_ = g_free;
	_tmp46_ = sqlite3_bind_text (_tmp41_, 6, _tmp44_, -1, _tmp45_);
	res = _tmp46_;
	_tmp47_ = query;
	_tmp48_ = sqlite3_step (_tmp47_);
	res = _tmp48_;
	_tmp49_ = res;
	if (_tmp49_ != SQLITE_DONE) {
		result = NULL;
		_sqlite3_finalize0 (query);
		return result;
	}
	_tmp50_ = persona;
	_tmp51_ = graph_media_modelos_tablas_bd;
	_tmp52_ = sqlite3_last_insert_rowid (_tmp51_);
	_tmp50_->id = _tmp52_;
	_tmp53_ = persona;
	_tmp54_ = graph_media_modelos_persona_es_valida (_tmp53_);
	_vala_assert (_tmp54_, "persona.es_valida()");
	_tmp55_ = persona;
	_tmp56_ = _graph_media_modelos_persona_ref0 (_tmp55_);
	result = _tmp56_;
	_sqlite3_finalize0 (query);
	return result;
}


GraphMediaModelosPersona* graph_media_modelos_tabla_personas_eliminar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* p, GError** error) {
	GraphMediaModelosPersona* result = NULL;
	GraphMediaModelosPersona* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	GraphMediaModelosPersona* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	gboolean _tmp4_ = FALSE;
	GraphMediaModelosPersona* _tmp11_ = NULL;
	GraphMediaModelosPersona* _tmp12_ = NULL;
	GraphMediaModelosPersona* _tmp13_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = p;
	_tmp1_ = _tmp0_->id;
	_vala_assert (_tmp1_ != ((gint64) (-1)), "p.id != -1");
	_tmp2_ = p;
	_tmp3_ = _tmp2_->id;
	_tmp4_ = graph_media_modelos_tablas_eliminar_celda_por_id ((GraphMediaModelosTablas*) self, _tmp3_);
	if (!_tmp4_) {
		GraphMediaModelosPersona* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		GError* _tmp10_ = NULL;
		_tmp5_ = p;
		_tmp6_ = _tmp5_->nombre;
		_tmp7_ = g_strdup_printf ("No se pudo eliminar a %s", _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_error_new_literal (GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS, GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS_CONSULTA, _tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		_inner_error_ = _tmp10_;
		if (_inner_error_->domain == GRAPH_MEDIA_MODELOS_ERROR_BASE_DATOS) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp11_ = p;
	_tmp11_->id = (gint64) (-1);
	_tmp12_ = p;
	_tmp13_ = _graph_media_modelos_persona_ref0 (_tmp12_);
	result = _tmp13_;
	return result;
}


gboolean graph_media_modelos_tabla_personas_editar (GraphMediaModelosTablaPersonas* self, GraphMediaModelosPersona* p) {
	gboolean result = FALSE;
	GraphMediaModelosPersona* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gchar* columnas = NULL;
	gchar* _tmp2_ = NULL;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gint res = 0;
	sqlite3* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	sqlite3_stmt* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	sqlite3_stmt* _tmp11_ = NULL;
	GraphMediaModelosPersona* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GDestroyNotify _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	sqlite3_stmt* _tmp18_ = NULL;
	GraphMediaModelosPersona* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	GDestroyNotify _tmp22_ = NULL;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	sqlite3_stmt* _tmp25_ = NULL;
	GraphMediaModelosPersona* _tmp26_ = NULL;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	sqlite3_stmt* _tmp30_ = NULL;
	GraphMediaModelosPersona* _tmp31_ = NULL;
	gdouble _tmp32_ = 0.0;
	gint _tmp33_ = 0;
	gint _tmp34_ = 0;
	sqlite3_stmt* _tmp35_ = NULL;
	GraphMediaModelosPersona* _tmp36_ = NULL;
	const gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	GDestroyNotify _tmp39_ = NULL;
	gint _tmp40_ = 0;
	gint _tmp41_ = 0;
	sqlite3_stmt* _tmp42_ = NULL;
	GraphMediaModelosPersona* _tmp43_ = NULL;
	const gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	GDestroyNotify _tmp46_ = NULL;
	gint _tmp47_ = 0;
	gint _tmp48_ = 0;
	sqlite3_stmt* _tmp49_ = NULL;
	GraphMediaModelosPersona* _tmp50_ = NULL;
	gint64 _tmp51_ = 0LL;
	gint _tmp52_ = 0;
	gint _tmp53_ = 0;
	sqlite3_stmt* _tmp54_ = NULL;
	gint _tmp55_ = 0;
	gint _tmp56_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (p != NULL, FALSE);
	_tmp0_ = p;
	_tmp1_ = graph_media_modelos_persona_es_valida (_tmp0_);
	if (!_tmp1_) {
		result = FALSE;
		return result;
	}
	_tmp2_ = g_strdup ("nombre=?, rol=?, edad=?, popularidad=?, nacionalidad=?, imagen=?");
	columnas = _tmp2_;
	_tmp3_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp4_ = columnas;
	_tmp5_ = g_strdup_printf ("UPDATE %s SET %s WHERE id=?", _tmp3_, _tmp4_);
	sql = _tmp5_;
	_tmp6_ = graph_media_modelos_tablas_bd;
	_tmp7_ = sql;
	_tmp9_ = sqlite3_prepare_v2 (_tmp6_, _tmp7_, -1, &_tmp8_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp8_;
	res = _tmp9_;
	_tmp10_ = res;
	_vala_assert (_tmp10_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp11_ = query;
	_tmp12_ = p;
	_tmp13_ = _tmp12_->nombre;
	_tmp14_ = g_strdup (_tmp13_);
	_tmp15_ = g_free;
	_tmp16_ = sqlite3_bind_text (_tmp11_, 1, _tmp14_, -1, _tmp15_);
	res = _tmp16_;
	_tmp17_ = res;
	_vala_assert (_tmp17_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp18_ = query;
	_tmp19_ = p;
	_tmp20_ = _tmp19_->rol;
	_tmp21_ = g_strdup (_tmp20_);
	_tmp22_ = g_free;
	_tmp23_ = sqlite3_bind_text (_tmp18_, 2, _tmp21_, -1, _tmp22_);
	res = _tmp23_;
	_tmp24_ = res;
	_vala_assert (_tmp24_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp25_ = query;
	_tmp26_ = p;
	_tmp27_ = _tmp26_->edad;
	_tmp28_ = sqlite3_bind_int (_tmp25_, 3, _tmp27_);
	res = _tmp28_;
	_tmp29_ = res;
	_vala_assert (_tmp29_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp30_ = query;
	_tmp31_ = p;
	_tmp32_ = _tmp31_->popularidad;
	_tmp33_ = sqlite3_bind_double (_tmp30_, 4, _tmp32_);
	res = _tmp33_;
	_tmp34_ = res;
	_vala_assert (_tmp34_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp35_ = query;
	_tmp36_ = p;
	_tmp37_ = _tmp36_->nacionalidad;
	_tmp38_ = g_strdup (_tmp37_);
	_tmp39_ = g_free;
	_tmp40_ = sqlite3_bind_text (_tmp35_, 5, _tmp38_, -1, _tmp39_);
	res = _tmp40_;
	_tmp41_ = res;
	_vala_assert (_tmp41_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp42_ = query;
	_tmp43_ = p;
	_tmp44_ = _tmp43_->imagen;
	_tmp45_ = g_strdup (_tmp44_);
	_tmp46_ = g_free;
	_tmp47_ = sqlite3_bind_text (_tmp42_, 6, _tmp45_, -1, _tmp46_);
	res = _tmp47_;
	_tmp48_ = res;
	_vala_assert (_tmp48_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp49_ = query;
	_tmp50_ = p;
	_tmp51_ = _tmp50_->id;
	_tmp52_ = sqlite3_bind_int64 (_tmp49_, 7, _tmp51_);
	res = _tmp52_;
	_tmp53_ = res;
	_vala_assert (_tmp53_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp54_ = query;
	_tmp55_ = sqlite3_step (_tmp54_);
	res = _tmp55_;
	_tmp56_ = res;
	result = _tmp56_ == SQLITE_DONE;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	_g_free0 (columnas);
	return result;
}


GraphMediaModelosPersona* graph_media_modelos_tabla_personas_get_persona_id (GraphMediaModelosTablaPersonas* self, gint64 id) {
	GraphMediaModelosPersona* result = NULL;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	gboolean _tmp3_ = FALSE;
	gint res = 0;
	sqlite3* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	sqlite3_stmt* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	sqlite3_stmt* _tmp9_ = NULL;
	gint64 _tmp10_ = 0LL;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	sqlite3_stmt* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	GraphMediaModelosPersona* celda = NULL;
	GraphMediaModelosPersona* _tmp16_ = NULL;
	GraphMediaModelosPersona* _tmp17_ = NULL;
	sqlite3_stmt* _tmp18_ = NULL;
	gint64 _tmp19_ = 0LL;
	GraphMediaModelosPersona* _tmp20_ = NULL;
	sqlite3_stmt* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	GraphMediaModelosPersona* _tmp24_ = NULL;
	sqlite3_stmt* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	GraphMediaModelosPersona* _tmp28_ = NULL;
	sqlite3_stmt* _tmp29_ = NULL;
	gint _tmp30_ = 0;
	GraphMediaModelosPersona* _tmp31_ = NULL;
	sqlite3_stmt* _tmp32_ = NULL;
	gdouble _tmp33_ = 0.0;
	GraphMediaModelosPersona* _tmp34_ = NULL;
	sqlite3_stmt* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	GraphMediaModelosPersona* _tmp38_ = NULL;
	sqlite3_stmt* _tmp39_ = NULL;
	const gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp1_ = g_strdup_printf ("SELECT %s FROM %s WHERE id=?", "*", _tmp0_);
	sql = _tmp1_;
	_tmp2_ = id;
	_tmp3_ = graph_media_modelos_tablas_existe_id ((GraphMediaModelosTablas*) self, _tmp2_);
	if (!_tmp3_) {
		result = NULL;
		_g_free0 (sql);
		_sqlite3_finalize0 (query);
		return result;
	}
	_tmp4_ = graph_media_modelos_tablas_bd;
	_tmp5_ = sql;
	_tmp7_ = sqlite3_prepare_v2 (_tmp4_, _tmp5_, -1, &_tmp6_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp6_;
	res = _tmp7_;
	_tmp8_ = res;
	_vala_assert (_tmp8_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp9_ = query;
	_tmp10_ = id;
	_tmp11_ = sqlite3_bind_int64 (_tmp9_, 1, _tmp10_);
	res = _tmp11_;
	_tmp12_ = res;
	_vala_assert (_tmp12_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp13_ = query;
	_tmp14_ = sqlite3_step (_tmp13_);
	res = _tmp14_;
	_tmp15_ = res;
	_vala_assert (_tmp15_ == SQLITE_ROW, "res == Sqlite.ROW");
	_tmp16_ = graph_media_modelos_persona_new ();
	celda = _tmp16_;
	_tmp17_ = celda;
	_tmp18_ = query;
	_tmp19_ = sqlite3_column_int64 (_tmp18_, 0);
	_tmp17_->id = _tmp19_;
	_tmp20_ = celda;
	_tmp21_ = query;
	_tmp22_ = sqlite3_column_text (_tmp21_, 1);
	_tmp23_ = g_strdup (_tmp22_);
	_g_free0 (_tmp20_->nombre);
	_tmp20_->nombre = _tmp23_;
	_tmp24_ = celda;
	_tmp25_ = query;
	_tmp26_ = sqlite3_column_text (_tmp25_, 2);
	_tmp27_ = g_strdup (_tmp26_);
	_g_free0 (_tmp24_->rol);
	_tmp24_->rol = _tmp27_;
	_tmp28_ = celda;
	_tmp29_ = query;
	_tmp30_ = sqlite3_column_int (_tmp29_, 3);
	_tmp28_->edad = _tmp30_;
	_tmp31_ = celda;
	_tmp32_ = query;
	_tmp33_ = sqlite3_column_double (_tmp32_, 4);
	_tmp31_->popularidad = _tmp33_;
	_tmp34_ = celda;
	_tmp35_ = query;
	_tmp36_ = sqlite3_column_text (_tmp35_, 5);
	_tmp37_ = g_strdup (_tmp36_);
	_g_free0 (_tmp34_->nacionalidad);
	_tmp34_->nacionalidad = _tmp37_;
	_tmp38_ = celda;
	_tmp39_ = query;
	_tmp40_ = sqlite3_column_text (_tmp39_, 6);
	_tmp41_ = g_strdup (_tmp40_);
	_g_free0 (_tmp38_->imagen);
	_tmp38_->imagen = _tmp41_;
	result = celda;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


gint graph_media_modelos_tabla_personas_get_total_personas (GraphMediaModelosTablaPersonas* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = graph_media_modelos_tablas_get_total_celdas ((GraphMediaModelosTablas*) self, "1");
	result = _tmp0_;
	return result;
}


GeeArrayList* graph_media_modelos_tabla_personas_get_personas (GraphMediaModelosTablaPersonas* self, const gchar* where, gint limite, const gchar* orden) {
	GeeArrayList* result = NULL;
	gint _tmp0_ = 0;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gint res = 0;
	sqlite3* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	sqlite3_stmt* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	GeeArrayList* personas = NULL;
	GeeArrayList* _tmp13_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (where != NULL, NULL);
	g_return_val_if_fail (orden != NULL, NULL);
	_tmp0_ = limite;
	_vala_assert (_tmp0_ >= 0, "limite >= 0");
	_tmp1_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp2_ = where;
	_tmp3_ = orden;
	_tmp4_ = g_strdup_printf ("FROM %s WHERE %s ORDER BY %s DESC", _tmp1_, _tmp2_, _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat ("SELECT id, nombre, rol, edad, popularidad, nacionalidad, imagen ", _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	sql = _tmp7_;
	_tmp8_ = graph_media_modelos_tablas_bd;
	_tmp9_ = sql;
	_tmp11_ = sqlite3_prepare_v2 (_tmp8_, _tmp9_, -1, &_tmp10_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp10_;
	res = _tmp11_;
	_tmp12_ = res;
	_vala_assert (_tmp12_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp13_ = gee_array_list_new (GRAPH_MEDIA_MODELOS_TYPE_PERSONA, (GBoxedCopyFunc) graph_media_modelos_persona_ref, graph_media_modelos_persona_unref, NULL, NULL, NULL);
	personas = _tmp13_;
	while (TRUE) {
		sqlite3_stmt* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
		gboolean _tmp17_ = FALSE;
		gint _tmp18_ = 0;
		GraphMediaModelosPersona* celda = NULL;
		GraphMediaModelosPersona* _tmp23_ = NULL;
		GraphMediaModelosPersona* _tmp24_ = NULL;
		sqlite3_stmt* _tmp25_ = NULL;
		gint64 _tmp26_ = 0LL;
		GraphMediaModelosPersona* _tmp27_ = NULL;
		sqlite3_stmt* _tmp28_ = NULL;
		const gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		GraphMediaModelosPersona* _tmp31_ = NULL;
		sqlite3_stmt* _tmp32_ = NULL;
		const gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		GraphMediaModelosPersona* _tmp35_ = NULL;
		sqlite3_stmt* _tmp36_ = NULL;
		gint _tmp37_ = 0;
		GraphMediaModelosPersona* _tmp38_ = NULL;
		sqlite3_stmt* _tmp39_ = NULL;
		gdouble _tmp40_ = 0.0;
		GraphMediaModelosPersona* _tmp41_ = NULL;
		sqlite3_stmt* _tmp42_ = NULL;
		const gchar* _tmp43_ = NULL;
		gchar* _tmp44_ = NULL;
		GraphMediaModelosPersona* _tmp45_ = NULL;
		sqlite3_stmt* _tmp46_ = NULL;
		const gchar* _tmp47_ = NULL;
		gchar* _tmp48_ = NULL;
		GeeArrayList* _tmp49_ = NULL;
		GraphMediaModelosPersona* _tmp50_ = NULL;
		_tmp14_ = query;
		_tmp15_ = sqlite3_step (_tmp14_);
		res = _tmp15_;
		_tmp16_ = res;
		if (!(_tmp16_ == SQLITE_ROW)) {
			break;
		}
		_tmp18_ = limite;
		if (_tmp18_ != 0) {
			GeeArrayList* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			gint _tmp22_ = 0;
			_tmp19_ = personas;
			_tmp20_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp19_);
			_tmp21_ = _tmp20_;
			_tmp22_ = limite;
			_tmp17_ = _tmp21_ == _tmp22_;
		} else {
			_tmp17_ = FALSE;
		}
		if (_tmp17_) {
			break;
		}
		_tmp23_ = graph_media_modelos_persona_new ();
		celda = _tmp23_;
		_tmp24_ = celda;
		_tmp25_ = query;
		_tmp26_ = sqlite3_column_int64 (_tmp25_, 0);
		_tmp24_->id = _tmp26_;
		_tmp27_ = celda;
		_tmp28_ = query;
		_tmp29_ = sqlite3_column_text (_tmp28_, 1);
		_tmp30_ = g_strdup (_tmp29_);
		_g_free0 (_tmp27_->nombre);
		_tmp27_->nombre = _tmp30_;
		_tmp31_ = celda;
		_tmp32_ = query;
		_tmp33_ = sqlite3_column_text (_tmp32_, 2);
		_tmp34_ = g_strdup (_tmp33_);
		_g_free0 (_tmp31_->rol);
		_tmp31_->rol = _tmp34_;
		_tmp35_ = celda;
		_tmp36_ = query;
		_tmp37_ = sqlite3_column_int (_tmp36_, 3);
		_tmp35_->edad = _tmp37_;
		_tmp38_ = celda;
		_tmp39_ = query;
		_tmp40_ = sqlite3_column_double (_tmp39_, 4);
		_tmp38_->popularidad = _tmp40_;
		_tmp41_ = celda;
		_tmp42_ = query;
		_tmp43_ = sqlite3_column_text (_tmp42_, 5);
		_tmp44_ = g_strdup (_tmp43_);
		_g_free0 (_tmp41_->nacionalidad);
		_tmp41_->nacionalidad = _tmp44_;
		_tmp45_ = celda;
		_tmp46_ = query;
		_tmp47_ = sqlite3_column_text (_tmp46_, 6);
		_tmp48_ = g_strdup (_tmp47_);
		_g_free0 (_tmp45_->imagen);
		_tmp45_->imagen = _tmp48_;
		_tmp49_ = personas;
		_tmp50_ = celda;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp49_, _tmp50_);
		_graph_media_modelos_persona_unref0 (celda);
	}
	result = personas;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


static void graph_media_modelos_tabla_personas_class_init (GraphMediaModelosTablaPersonasClass * klass) {
	graph_media_modelos_tabla_personas_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = graph_media_modelos_tabla_personas_finalize;
}


static void graph_media_modelos_tabla_personas_instance_init (GraphMediaModelosTablaPersonas * self) {
}


static void graph_media_modelos_tabla_personas_finalize (GObject* obj) {
	GraphMediaModelosTablaPersonas * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_TABLA_PERSONAS, GraphMediaModelosTablaPersonas);
	G_OBJECT_CLASS (graph_media_modelos_tabla_personas_parent_class)->finalize (obj);
}


GType graph_media_modelos_tabla_personas_get_type (void) {
	static volatile gsize graph_media_modelos_tabla_personas_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_tabla_personas_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosTablaPersonasClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_tabla_personas_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosTablaPersonas), 0, (GInstanceInitFunc) graph_media_modelos_tabla_personas_instance_init, NULL };
		GType graph_media_modelos_tabla_personas_type_id;
		graph_media_modelos_tabla_personas_type_id = g_type_register_static (GRAPH_MEDIA_MODELOS_TYPE_TABLAS, "GraphMediaModelosTablaPersonas", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_modelos_tabla_personas_type_id__volatile, graph_media_modelos_tabla_personas_type_id);
	}
	return graph_media_modelos_tabla_personas_type_id__volatile;
}


GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_construct (GType object_type) {
	GraphMediaModelosPersonaArchivo * self = NULL;
	self = (GraphMediaModelosPersonaArchivo*) graph_media_modelos_relacion_construct (object_type);
	graph_media_modelos_tablas_set_nombre_tabla ((GraphMediaModelosTablas*) self, "r_persona_archivo");
	graph_media_modelos_relacion_set_llave ((GraphMediaModelosRelacion*) self, "id_persona");
	graph_media_modelos_relacion_set_puerta ((GraphMediaModelosRelacion*) self, "id_archivo");
	graph_media_modelos_relacion_set_tabla_llave ((GraphMediaModelosRelacion*) self, "personas");
	graph_media_modelos_relacion_set_tabla_puerta ((GraphMediaModelosRelacion*) self, "archivos");
	return self;
}


GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_new (void) {
	return graph_media_modelos_persona_archivo_construct (GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO);
}


GraphMediaModelosPersonaArchivo* graph_media_modelos_persona_archivo_get_instancia (void) {
	GraphMediaModelosPersonaArchivo* result = NULL;
	GraphMediaModelosPersonaArchivo* _tmp0_ = NULL;
	GraphMediaModelosPersonaArchivo* _tmp2_ = NULL;
	GraphMediaModelosPersonaArchivo* _tmp3_ = NULL;
	_tmp0_ = graph_media_modelos_persona_archivo_instancia;
	if (_tmp0_ == NULL) {
		GraphMediaModelosPersonaArchivo* _tmp1_ = NULL;
		_tmp1_ = graph_media_modelos_persona_archivo_new ();
		_g_object_unref0 (graph_media_modelos_persona_archivo_instancia);
		graph_media_modelos_persona_archivo_instancia = _tmp1_;
	}
	_tmp2_ = graph_media_modelos_persona_archivo_instancia;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


void graph_media_modelos_persona_archivo_relaciona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona, GraphMediaModelosArchivo* cancion) {
	GraphMediaModelosPersona* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	GraphMediaModelosArchivo* _tmp2_ = NULL;
	gint64 _tmp3_ = 0LL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (persona != NULL);
	g_return_if_fail (cancion != NULL);
	_tmp0_ = persona;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = cancion;
	_tmp3_ = _tmp2_->id;
	graph_media_modelos_relacion_relaciona_ids ((GraphMediaModelosRelacion*) self, _tmp1_, _tmp3_);
}


void graph_media_modelos_persona_archivo_eliminar_relaciones_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona) {
	GraphMediaModelosPersona* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (persona != NULL);
	_tmp0_ = persona;
	_tmp1_ = _tmp0_->id;
	graph_media_modelos_relacion_eliminar_relaciones_id ((GraphMediaModelosRelacion*) self, _tmp1_);
}


void graph_media_modelos_persona_archivo_eliminar_relaciones_archivo (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosArchivo* archivo) {
	GraphMediaModelosArchivo* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (archivo != NULL);
	_tmp0_ = archivo;
	_tmp1_ = _tmp0_->id;
	graph_media_modelos_relacion_eliminar_relaciones_secundarias_id ((GraphMediaModelosRelacion*) self, _tmp1_);
}


gint graph_media_modelos_persona_archivo_n_archivos_por_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* persona) {
	gint result = 0;
	GraphMediaModelosPersona* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (persona != NULL, 0);
	_tmp0_ = persona;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = graph_media_modelos_relacion_total_relaciones_llave ((GraphMediaModelosRelacion*) self, _tmp1_);
	result = _tmp2_;
	return result;
}


gint graph_media_modelos_persona_archivo_n_personas_por_archivo (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosArchivo* archivo) {
	gint result = 0;
	GraphMediaModelosArchivo* _tmp0_ = NULL;
	gint64 _tmp1_ = 0LL;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (archivo != NULL, 0);
	_tmp0_ = archivo;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = graph_media_modelos_relacion_total_relaciones_puerta ((GraphMediaModelosRelacion*) self, _tmp1_);
	result = _tmp2_;
	return result;
}


GeeArrayList* graph_media_modelos_persona_archivo_archivos_por_persona (GraphMediaModelosPersonaArchivo* self, GraphMediaModelosPersona* p) {
	GeeArrayList* result = NULL;
	sqlite3_stmt* query = NULL;
	gchar* sql = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GraphMediaModelosPersona* _tmp4_ = NULL;
	gint64 _tmp5_ = 0LL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gint res = 0;
	sqlite3* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	sqlite3_stmt* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	GeeArrayList* archivos = NULL;
	GeeArrayList* _tmp15_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = ((GraphMediaModelosRelacion*) self)->tabla_puerta;
	_tmp1_ = ((GraphMediaModelosRelacion*) self)->puerta;
	_tmp2_ = ((GraphMediaModelosTablas*) self)->nombre_tabla;
	_tmp3_ = ((GraphMediaModelosRelacion*) self)->llave;
	_tmp4_ = p;
	_tmp5_ = _tmp4_->id;
	_tmp6_ = g_strdup_printf ("FROM %s WHERE id IN ( SELECT %s FROM %s WHERE %s=%lld) ", _tmp0_, _tmp1_, _tmp2_, _tmp3_, _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat ("SELECT id, nombre, ubicacion, tipo, ultimoAcceso, popularidad, disponi" \
"ble ", _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	sql = _tmp9_;
	_tmp10_ = graph_media_modelos_tablas_bd;
	_tmp11_ = sql;
	_tmp13_ = sqlite3_prepare_v2 (_tmp10_, _tmp11_, -1, &_tmp12_, NULL);
	_sqlite3_finalize0 (query);
	query = _tmp12_;
	res = _tmp13_;
	_tmp14_ = res;
	_vala_assert (_tmp14_ == SQLITE_OK, "res == Sqlite.OK");
	_tmp15_ = gee_array_list_new (GRAPH_MEDIA_MODELOS_TYPE_ARCHIVO, (GBoxedCopyFunc) graph_media_modelos_archivo_ref, graph_media_modelos_archivo_unref, NULL, NULL, NULL);
	archivos = _tmp15_;
	while (TRUE) {
		sqlite3_stmt* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		GraphMediaModelosArchivo* c = NULL;
		GraphMediaModelosArchivo* _tmp19_ = NULL;
		GraphMediaModelosArchivo* _tmp20_ = NULL;
		sqlite3_stmt* _tmp21_ = NULL;
		gint64 _tmp22_ = 0LL;
		GraphMediaModelosArchivo* _tmp23_ = NULL;
		sqlite3_stmt* _tmp24_ = NULL;
		const gchar* _tmp25_ = NULL;
		gchar* _tmp26_ = NULL;
		GraphMediaModelosArchivo* _tmp27_ = NULL;
		sqlite3_stmt* _tmp28_ = NULL;
		const gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		GraphMediaModelosArchivo* _tmp31_ = NULL;
		sqlite3_stmt* _tmp32_ = NULL;
		const gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		GraphMediaModelosArchivo* _tmp35_ = NULL;
		sqlite3_stmt* _tmp36_ = NULL;
		const gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
		GraphMediaModelosArchivo* _tmp39_ = NULL;
		sqlite3_stmt* _tmp40_ = NULL;
		gdouble _tmp41_ = 0.0;
		GraphMediaModelosArchivo* _tmp42_ = NULL;
		sqlite3_stmt* _tmp43_ = NULL;
		gint _tmp44_ = 0;
		GeeArrayList* _tmp45_ = NULL;
		GraphMediaModelosArchivo* _tmp46_ = NULL;
		_tmp16_ = query;
		_tmp17_ = sqlite3_step (_tmp16_);
		res = _tmp17_;
		_tmp18_ = res;
		if (!(_tmp18_ == SQLITE_ROW)) {
			break;
		}
		_tmp19_ = graph_media_modelos_archivo_new ();
		c = _tmp19_;
		_tmp20_ = c;
		_tmp21_ = query;
		_tmp22_ = sqlite3_column_int64 (_tmp21_, 0);
		_tmp20_->id = _tmp22_;
		_tmp23_ = c;
		_tmp24_ = query;
		_tmp25_ = sqlite3_column_text (_tmp24_, 1);
		_tmp26_ = g_strdup (_tmp25_);
		_g_free0 (_tmp23_->nombre);
		_tmp23_->nombre = _tmp26_;
		_tmp27_ = c;
		_tmp28_ = query;
		_tmp29_ = sqlite3_column_text (_tmp28_, 2);
		_tmp30_ = g_strdup (_tmp29_);
		_g_free0 (_tmp27_->ubicacion);
		_tmp27_->ubicacion = _tmp30_;
		_tmp31_ = c;
		_tmp32_ = query;
		_tmp33_ = sqlite3_column_text (_tmp32_, 2);
		_tmp34_ = g_strdup (_tmp33_);
		_g_free0 (_tmp31_->tipo);
		_tmp31_->tipo = _tmp34_;
		_tmp35_ = c;
		_tmp36_ = query;
		_tmp37_ = sqlite3_column_text (_tmp36_, 2);
		_tmp38_ = g_strdup (_tmp37_);
		_g_free0 (_tmp35_->u_acceso);
		_tmp35_->u_acceso = _tmp38_;
		_tmp39_ = c;
		_tmp40_ = query;
		_tmp41_ = sqlite3_column_double (_tmp40_, 3);
		_tmp39_->popularidad = _tmp41_;
		_tmp42_ = c;
		_tmp43_ = query;
		_tmp44_ = sqlite3_column_int (_tmp43_, 2);
		_tmp42_->disponible = _tmp44_ == 0;
		_tmp45_ = archivos;
		_tmp46_ = c;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp45_, _tmp46_);
		_graph_media_modelos_archivo_unref0 (c);
	}
	result = archivos;
	_g_free0 (sql);
	_sqlite3_finalize0 (query);
	return result;
}


static void graph_media_modelos_persona_archivo_class_init (GraphMediaModelosPersonaArchivoClass * klass) {
	graph_media_modelos_persona_archivo_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = graph_media_modelos_persona_archivo_finalize;
}


static void graph_media_modelos_persona_archivo_instance_init (GraphMediaModelosPersonaArchivo * self) {
}


static void graph_media_modelos_persona_archivo_finalize (GObject* obj) {
	GraphMediaModelosPersonaArchivo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRAPH_MEDIA_MODELOS_TYPE_PERSONA_ARCHIVO, GraphMediaModelosPersonaArchivo);
	G_OBJECT_CLASS (graph_media_modelos_persona_archivo_parent_class)->finalize (obj);
}


GType graph_media_modelos_persona_archivo_get_type (void) {
	static volatile gsize graph_media_modelos_persona_archivo_type_id__volatile = 0;
	if (g_once_init_enter (&graph_media_modelos_persona_archivo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraphMediaModelosPersonaArchivoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) graph_media_modelos_persona_archivo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraphMediaModelosPersonaArchivo), 0, (GInstanceInitFunc) graph_media_modelos_persona_archivo_instance_init, NULL };
		GType graph_media_modelos_persona_archivo_type_id;
		graph_media_modelos_persona_archivo_type_id = g_type_register_static (GRAPH_MEDIA_MODELOS_TYPE_RELACION, "GraphMediaModelosPersonaArchivo", &g_define_type_info, 0);
		g_once_init_leave (&graph_media_modelos_persona_archivo_type_id__volatile, graph_media_modelos_persona_archivo_type_id);
	}
	return graph_media_modelos_persona_archivo_type_id__volatile;
}



